;;; eziam-light-theme.el --- The light Eziam theme for Emacs

;; Copyright (C) 2016 Thibault Polge <thibault@thb.lt>
;; Heavily based on Tao Theme (C) 2014 Peter  <11111000000 at email.com>,
;; with contributions from Jasonm23 <jasonm23@gmail.com>
;; Original faces taken from Zenburn theme port (c) by Bozhidar Batsov
;;
;; Package-Requires:            ((cl-lib "0.5"))
;;
;; URL: http://github.com/thblt/eziam-theme-emacs
;; Version: 0.0

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:
;;; Code:




(require 'eziam-common)

(deftheme eziam-light "The VARIANT Eziam color theme")

(let ((class '((class color) (min-colors 89)))

      ;; Eziam generic colors.
      (ol1 `(,@(when eziam-scale-outline-headlines (list :height 1.9)) :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0"))
      (ol2 '(:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB"))
      (ol3 '(:height 1.0 :weight bold :foreground "#005522" :background "#EFFFEF"))
      (ol4 '(:height 1.0 :weight bold :slant normal :foreground "#EA6300"))
      (ol5 '(:height 1.0 :weight bold :slant normal :foreground "#E3258D"))
      (ol6 '(:height 1.0 :weight bold :slant italic :foreground "#0077CC"))
      (ol7 '(:height 1.0 :weight bold :slant italic :foreground "#2EAE2C"))
      (ol8 '(:height 1.0 :weight bold :slant italic :foreground "#FD8008"))
      )
  
  (custom-theme-set-faces
   'eziam-light
   ;; Built-in
   `(button                                           ((t (:underline t))))
   `(link                                             ((t (:foreground "#080808" :underline t :weight bold))))
   `(link-visited                                     ((t (:foreground "#0E0E0E" :underline t :weight normal))))
   `(default                                          ((t (:foreground "#252525" :background "#F0F0F0"))))
   `(hl-paren-face                                    ((t (:foreground "#080808" :background "#D9D9D9" :weight bold))))
   `(cursor                                           ((t (:foreground "#080808" :background "#080808"))))
   `(escape-glyph                                     ((t (:foreground "#080808" :bold t))))
   `(fringe                                           ((t (:foreground "#E8E8E8" :background "#F0F0F0"))))
   `(header-line                                      ((t (:inherit mode-line))))
   `(highlight                                        ((t (:background "#F0F0F0"))))
   `(success                                          ((t (:foreground "#252525" :weight bold))))
   `(warning                                          ((t (:foreground "#0E0E0E" :weight bold))))
   ;; compilation
   `(compilation-column-face                          ((t (:foreground "#080808"))))
   `(compilation-enter-directory-face                 ((t (:foreground "#252525"))))
   `(compilation-error-face                           ((t (:foreground "#252525" :weight bold :underline t))))
   `(compilation-face                                 ((t (:foreground "#080808"))))
   `(compilation-info-face                            ((t (:foreground "#0E0E0E"))))
   `(compilation-info                                 ((t (:foreground "#080808" :underline t))))
   `(compilation-leave-directory-face                 ((t (:foreground "#252525"))))
   `(compilation-line-face                            ((t (:foreground "#080808"))))
   `(compilation-line-number                          ((t (:foreground "#080808"))))
   `(compilation-message-face                         ((t (:foreground "#0E0E0E"))))
   `(compilation-warning-face                         ((t (:foreground "#0E0E0E" :weight bold :underline t))))
   `(compilation-mode-line-exit                       ((t (:foreground "#0E0E0E" :weight bold))))
   `(compilation-mode-line-fail                       ((t (:foreground "#161616" :weight bold))))
   `(compilation-mode-line-run                        ((t (:foreground "#080808" :weight bold))))
   ;; grep
   `(grep-context-face                                ((t (:foreground "#080808"))))
   `(grep-error-face                                  ((t (:foreground "#252525" :weight bold :underline t))))
   `(grep-hit-face                                    ((t (:foreground "#0E0E0E"))))
   `(grep-match-face                                  ((t (:foreground "#0E0E0E" :weight bold))))
   `(match                                            ((t (:background "#D9D9D9" :foreground "#0E0E0E" :weight bold))))
   ;; make
   `(makefile-space                                   ((t (:background "#F0F0F0"))))
   `(makefile-targets                                 ((t (:underline t))))
   `(makefile-shell                                   ((t (:slant italic))))
   ;; isearch
   `(isearch                                          ((t (:background ,"#ffff00" :foreground "#E8E8E8" :weight normal))))
   `(isearch-fail                                     ((t (:foreground "#080808" :background "#616161"))))
   `(lazy-highlight                                   ((t (:foreground "#0E0E0E" :weight bold :background "#C2C2C2"))))
   `(menu                                             ((t (:foreground "#080808" :background "#F0F0F0"))))
   `(minibuffer-prompt                                ((t (:foreground "#080808" :color "#C2C2C2"))))
   `(mode-line                                        ((,class (:foreground "#E8E8E8" :background "#3C3C3C" :box nil )) (t :inverse-video t)))
   `(mode-line-inactive                               ((t (:foreground "#D9D9D9" :background "#9D9D9D" :box nil))))
   `(mode-line-buffer-id                              ((t (:foreground "#F0F0F0" :weight bold))))
   `(region                                           ((,class (:background "#252525" :foreground "#D9D9D9")) (t :inverse-video t)))
   `(secondary-selection                              ((t (:background "#F0F0F0"))))
   `(cua-rectangle                                    ((t (:background "#F0F0F0"))))
   `(trailing-whitespace                              ((t (:background "#161616"))))
   `(vertical-border                                  ((t (:foreground "#616161" :background "#F0F0F0"))))
   ;; font lock
   `(font-lock-builtin-face                           ((t (:foreground "#080808" :weight bold))))
   `(font-lock-comment-face                           ((t (:foreground "#616161" :weight bold))))
   `(font-lock-comment-delimiter-face                 ((t (:foreground "#3C3C3C"))))
   `(font-lock-constant-face                          ((t (:foreground "#3C3C3C" :weight bold))))
   `(font-lock-doc-face                               ((t (:foreground "#616161"))))
   `(font-lock-function-name-face                     ((t (:background "#BBCCFF" :box (:color "#99AADD")))))
   `(font-lock-keyword-face                           ((t (:foreground "#080808" :weight bold))))
   `(font-lock-negation-char-face                     ((t (:foreground "#080808" :weight bold))))
   `(font-lock-preprocessor-face                      ((t (:foreground "#0E0E0E"))))
   `(font-lock-regexp-grouping-construct              ((t (:foreground "#080808" :weight bold))))
   `(font-lock-regexp-grouping-backslash              ((t (:foreground "#252525" :weight bold))))
   `(font-lock-string-face                            ((t (:foreground "#3C3C3C" :slant oblique))))
   `(font-lock-type-face                              ((t (:foreground "#161616" :underline t))))
   `(font-lock-variable-name-face                     ((t (:foreground "#080808" ))))
   `(font-lock-warning-face                           ((t (:foreground "#0E0E0E" :weight bold))))
   `(c-annotation-face                                ((t (:inherit font-lock-constant-face))))
   ;; newsticker
   `(newsticker-date-face                             ((t (:foreground "#080808"))))
   `(newsticker-default-face                          ((t (:foreground "#080808"))))
   `(newsticker-enclosure-face                        ((t (:foreground "#080808"))))
   `(newsticker-extra-face                            ((t (:foreground "#616161" ,@(when eziam-scale-non-headline-faces (list :height 0.8)))))) ;; FIXME
   `(newsticker-feed-face ((t (:foreground "#080808"))))
   `(newsticker-immortal-item-face                    ((t (:foreground "#252525"))))
   `(newsticker-new-item-face                         ((t (:foreground "#0E0E0E"))))
   `(newstickerphone-obsolete-item-face                    ((t (:foreground "#161616"))))
   `(newsticker-old-item-face                         ((t (:foreground "#3C3C3C"))))
   `(newsticker-statistics-face                       ((t (:foreground "#080808"))))
   `(newsticker-treeview-face                         ((t (:foreground "#080808"))))
   `(newsticker-treeview-immortal-face                ((t (:foreground "#252525"))))
   `(newsticker-treeview-listwindow-face              ((t (:foreground "#080808"))))
   `(newsticker-treeview-new-face                     ((t (:foreground "#0E0E0E" :weight bold))))
   `(newsticker-treeview-obsolete-face                ((t (:foreground "#161616"))))
   `(newsticker-treeview-old-face                     ((t (:foreground "#3C3C3C"))))
   `(newsticker-treeview-selection-face               ((t (:background "#D9D9D9" :foreground "#080808"))))
   ;; Third-party
   ;; highlight-symbol
   `(highlight-symbol-face                            ((t (:background "#F0F0F0") )))
   ;; ace-jump
   `(ace-jump-face-background                         ((t (:foreground "#9D9D9D" :background "#E8E8E8" :inverse-video nil))))
   `(ace-jump-face-foreground                         ((t (:foreground "#0E0E0E" :background "#C2C2C2" :inverse-video nil))))
   ;; anzu
   `(anzu-mode-line                                   ((t (:foreground "#080808" :weight bold))))
   ;; full-ack
   `(ack-separator                                    ((t (:foreground "#080808"))))
   `(ack-file                                         ((t (:foreground "#0E0E0E"))))
   `(ack-line                                         ((t (:foreground "#080808"))))
   `(ack-match                                        ((t (:foreground "#0E0E0E" :background "#D9D9D9" :weight bold))))
   ;; auctex
   `(font-latex-bold-face                             ((t (:inherit bold))))
   `(font-latex-warning-face                          ((t (:foreground nil :inherit font-lock-warning-face))))
   `(font-latex-sectioning-5-face                     ((t (:foreground "#161616" :weight bold ))))
   `(font-latex-sedate-face                           ((t (:foreground "#080808"))))
   `(font-latex-italic-face                           ((t (:foreground "#080808" :slant italic))))
   `(font-latex-string-face                           ((t (:inherit ,font-lock-string-face))))
   `(font-latex-math-face                             ((t (:foreground "#0E0E0E"))))
   ;; auto-complete
   `(ac-candidate-face                                ((t (:background "#3C3C3C" :foreground "#E8E8E8" :underline nil))))
   `(ac-selection-face                                ((t (:background "#616161" :foreground "#080808" :underline nil))))
   `(ac-yasnippet-candidate-face                      ((t (:background "#3C3C3C" :foreground "#D9D9D9"))))
   `(ac-yasnippet-selection-face                      ((t (:background "#616161" :foreground "#080808"))))
   `(ac-slime-menu-face                               ((t (:background "#3C3C3C" :foreground "#C2C2C2"))))
   `(ac-slime-selection-face                          ((t (:background "#616161" :foreground "#080808"))))
   `(ac-gtags-candidate-face                          ((t (:background "#3C3C3C" :foreground "#C2C2C2"))))
   `(ac-gtags-selection-face                          ((t (:background "#616161" :foreground "#080808"))))
   `(ac-emmet-candidate-face                          ((t (:background "#3C3C3C" :foreground "#E8E8E8"))))
   `(ac-emmet-selection-face                          ((t (:background "#616161" :foreground "#080808"))))

   `(popup-tip-face                                   ((t (:background "#0E0E0E" :foreground "#E8E8E8"))))
   `(popup-scroll-bar-foreground-face                 ((t (:background "#9D9D9D"))))
   `(popup-scroll-bar-background-face                 ((t (:background "#D9D9D9"))))
   `(popup-isearch-match                              ((t (:background "#F0F0F0" :foreground "#080808"))))
   ;; android mode
   `(android-mode-debug-face                          ((t (:foreground "#161616"))))
   `(android-mode-error-face                          ((t (:foreground "#0E0E0E" :weight bold))))
   `(android-mode-info-face                           ((t (:foreground "#080808"))))
   `(android-mode-verbose-face                        ((t (:foreground "#252525"))))
   `(android-mode-warning-face                        ((t (:foreground "#080808"))))
   ;; bm
   `(bm-face                                          ((t (:background "#080808" :foreground "#C2C2C2"))))
   `(bm-fringe-face                                   ((t (:background "#F0F0F0" :foreground "#E8E8E8"))))
   `(bm-fringe-persistent-face                        ((t (:background "#F0F0F0" :foreground "#E8E8E8"))))
   `(bm-persistent-face                               ((t (:background "#3C3C3C" :foreground "#C2C2C2"))))
   ;; clojure-test-mode
   `(clojure-test-failure-face                        ((t (:foreground "#0E0E0E" :weight bold :underline t))))
   `(clojure-test-error-face                          ((t (:foreground "#161616" :weight bold :underline t))))
   `(clojure-test-success-face                        ((t (:foreground "#161616" :weight bold :underline t))))
   ;; coq
   `(coq-solve-tactics-face                           ((t (:foreground nil :inherit font-lock-constant-face))))
   ;; ctable
   `(ctbl:face-cell-select                            ((t (:background "#0E0E0E" :foreground "#C2C2C2"))))
   `(ctbl:face-continue-bar                           ((t (:background "#F0F0F0" :foreground "#C2C2C2"))))
   `(ctbl:face-row-select                             ((t (:background "#080808" :foreground "#C2C2C2"))))
   ;; diff
   `(diff-added                                       ((,class (:foreground "#080808" :background nil)) (t (:foreground "#3C3C3C" :background nil))))
   `(diff-changed                                     ((t (:foreground "#080808"))))
   `(diff-removed                                     ((,class (:foreground "#161616" :background nil)) (t (:foreground "#3C3C3C" :background nil))))
   `(diff-refine-added                                ((t :inherit diff-added :weight bold)))
   `(diff-refine-change                               ((t :inherit diff-changed :weight bold)))
   `(diff-refine-removed                              ((t :inherit diff-removed :weight bold)))
   `(diff-header                                      ((,class (:background "#616161")) (t (:background "#080808" :foreground "#C2C2C2"))))
   `(diff-file-header                                 ((,class (:background "#616161" :foreground "#080808" :bold t)) (t (:background "#080808" :foreground "#C2C2C2" :bold t))))
   ;; dired
   `(dired-directory                                  ((t (:foreground "#080808" :bold t))))
   ;; dired+
   `(diredp-display-msg                               ((t (:foreground "#0E0E0E"))))
   `(diredp-compressed-file-suffix                    ((t (:foreground "#0E0E0E"))))
   `(diredp-date-time                                 ((t (:foreground "#161616"))))
   `(diredp-deletion                                  ((t (:foreground "#080808"))))
   `(diredp-deletion-file-name                        ((t (:foreground "#161616"))))
   `(diredp-dir-heading                               ((t (:foreground "#080808" :background "#D9D9D9" :bold t))))
   `(diredp-dir-priv                                  ((t (:foreground "#080808" :bold t))))
   `(diredp-dir-name                                  ((t (:foreground "#080808" :bold t))))
   `(diredp-exec-priv                                 ((t (:foreground "#161616"))))
   `(diredp-executable-tag                            ((t (:foreground "#161616"))))
   `(diredp-file-name                                 ((t (:foreground "#0E0E0E"))))
   `(diredp-file-suffix                               ((t (:foreground "#0E0E0E" :bold t))))
   `(diredp-flag-mark                                 ((t (:foreground "#080808"))))
   `(diredp-flag-mark-line                            ((t (:foreground "#0E0E0E"))))
   `(diredp-ignored-file-name                         ((t (:foreground "#9D9D9D"))))
   `(diredp-link-priv                                 ((t (:foreground "#080808"))))
   `(diredp-mode-line-flagged                         ((t (:foreground "#080808"))))
   `(diredp-mode-line-marked                          ((t (:foreground "#0E0E0E"))))
   `(diredp-no-priv                                   ((t (:foreground "#080808"))))
   `(diredp-number                                    ((t (:foreground "#161616"))))
   `(diredp-other-priv                                ((t (:foreground "#080808"))))
   `(diredp-rare-priv                                 ((t (:foreground "#252525"))))
   `(diredp-read-priv                                 ((t (:foreground "#3C3C3C"))))
   `(diredp-symlink                                   ((t (:foreground "#080808"))))
   `(diredp-write-priv                                ((t (:foreground "#161616"))))
   ;; ediff
   `(ediff-current-diff-A                             ((t (:foreground "#080808" :background "#616161"))))
   `(ediff-current-diff-Ancestor                      ((t (:foreground "#080808" :background "#616161"))))
   `(ediff-current-diff-B                             ((t (:foreground "#080808" :background "#3C3C3C"))))
   `(ediff-current-diff-C                             ((t (:foreground "#080808" :background "#9D9D9D"))))
   `(ediff-even-diff-A                                ((t (:background "#9D9D9D"))))
   `(ediff-even-diff-Ancestor                         ((t (:background "#9D9D9D"))))
   `(ediff-even-diff-B                                ((t (:background "#9D9D9D"))))
   `(ediff-even-diff-C                                ((t (:background "#9D9D9D"))))
   `(ediff-fine-diff-A                                ((t (:foreground "#080808" :background "#252525" :weight bold))))
   `(ediff-fine-diff-Ancestor                         ((t (:foreground "#080808" :background "#252525" :weight bold))))
   `(ediff-fine-diff-B                                ((t (:foreground "#080808" :background "#252525" :weight bold))))
   `(ediff-fine-diff-C                                ((t (:foreground "#080808" :background "#3C3C3C" :weight bold ))))
   `(ediff-odd-diff-A                                 ((t (:background "#616161"))))
   `(ediff-odd-diff-Ancestor                          ((t (:background "#616161"))))
   `(ediff-odd-diff-B                                 ((t (:background "#616161"))))
   `(ediff-odd-diff-C                                 ((t (:background "#616161"))))
   ;; ert
   `(ert-test-result-expected                         ((t (:foreground "#080808" :background "#F0F0F0"))))
   `(ert-test-result-unexpected                       ((t (:foreground "#161616" :background "#F0F0F0"))))
   ;; eshell
   `(eshell-prompt                                    ((t (:foreground "#080808" :weight bold))))
   `(eshell-ls-archive                                ((t (:foreground "#252525" :weight bold))))
   `(eshell-ls-backup                                 ((t (:inherit font-lock-comment-face))))
   `(eshell-ls-clutter                                ((t (:inherit font-lock-comment-face))))
   `(eshell-ls-directory                              ((t (:foreground "#0E0E0E" :weight bold))))
   `(eshell-ls-executable                             ((t (:foreground "#0E0E0E" :weight bold))))
   `(eshell-ls-unreadable                             ((t (:foreground "#080808"))))
   `(eshell-ls-missing                                ((t (:inherit font-lock-warning-face))))
   `(eshell-ls-product                                ((t (:inherit font-lock-doc-face))))
   `(eshell-ls-special                                ((t (:foreground "#080808" :weight bold))))
   `(eshell-ls-symlink                                ((t (:foreground "#080808" :weight bold))))
   ;; flx
   `(flx-highlight-face                               ((t (:foreground "#0E0E0E" :weight bold))))
   ;; flycheck
   `(flycheck-error                                   ((((supports :underline (:style wave))) (:underline (:style wave :color "#616161") :inherit unspecified)) (t (:foreground "#080808" :weight bold :underline t))))
   `(flycheck-warning                                 ((((supports :underline (:style wave))) (:underline (:style wave :color "#9D9D9D") :inherit unspecified)) (t (:foreground "#0E0E0E" :weight bold :underline t))))
   `(flycheck-info                                    ((((supports :underline (:style wave))) (:underline (:style wave :color "#C2C2C2") :inherit unspecified)) (t (:foreground "#161616" :weight bold :underline t))))
   `(flycheck-fringe-error                            ((t (:foreground "#C2C2C2" :weight bold))))
   `(flycheck-fringe-warning                          ((t (:foreground "#F0F0F0" :weight bold))))
   `(flycheck-fringe-info                             ((t (:foreground "#F0F0F0" :weight bold))))
   ;; flymake
   `(flymake-errline                                  ((((supports :underline (:style wave))) (:underline (:style wave :color "#161616") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#252525" :weight bold :underline t))))
   `(flymake-warnline                                 ((((supports :underline (:style wave))) (:underline (:style wave :color "#0E0E0E") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#0E0E0E" :weight bold :underline t))))
   `(flymake-infoline                                 ((((supports :underline (:style wave))) (:underline (:style wave :color "#252525") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#3C3C3C" :weight bold :underline t))))
   ;; flyspell
   `(flyspell-duplicate                               ((((supports :underline (:style wave))) (:underline (:style wave :color "#0E0E0E") :inherit unspecified)) (t (:foreground "#0E0E0E" :weight bold :underline t))))
   `(flyspell-incorrect                               ((((supports :underline (:style wave))) (:underline (:style wave :color "#161616") :inherit unspecified)) (t (:foreground "#252525" :weight bold :underline t))))
   ;; erc
   `(erc-action-face                                  ((t (:inherit erc-default-face))))
   `(erc-bold-face                                    ((t (:weight bold))))
   `(erc-current-nick-face                            ((t (:foreground "#0E0E0E" :weight bold))))
   `(erc-dangerous-host-face                          ((t (:inherit font-lock-warning-face))))
   `(erc-default-face                                 ((t (:foreground "#080808"))))
   `(erc-direct-msg-face                              ((t (:inherit erc-default))))
   `(erc-error-face                                   ((t (:inherit font-lock-warning-face))))
   `(erc-fool-face                                    ((t (:inherit erc-default))))
   `(erc-highlight-face                               ((t (:inherit hover-highlight))))
   `(erc-input-face                                   ((t (:foreground "#080808"))))
   `(erc-keyword-face                                 ((t (:foreground "#0E0E0E" :weight bold))))
   `(erc-nick-default-face                            ((t (:foreground "#080808" :weight bold))))
   `(erc-my-nick-face                                 ((t (:foreground "#161616" :weight bold))))
   `(erc-nick-msg-face                                ((t (:inherit erc-default))))
   `(erc-notice-face                                  ((t (:foreground "#252525"))))
   `(erc-pal-face                                     ((t (:foreground "#0E0E0E" :weight bold))))
   `(erc-prompt-face                                  ((t (:foreground "#0E0E0E" :background "#F0F0F0" :weight bold))))
   `(erc-timestamp-face                               ((t (:foreground "#080808"))))
   `(erc-underline-face                               ((t (:underline t))))
   ;; git-gutter
   `(git-gutter:added                                 ((t (:background "#F0F0F0" :foreground "#C2C2C2" :weight bold ))))
   `(git-gutter:deleted                               ((t (:background "#F0F0F0" :foreground "#C2C2C2" :weight bold ))))
   `(git-gutter:modified                              ((t (:background "#F0F0F0" :foreground "#C2C2C2" :weight bold ))))
   `(git-gutter:unchanged                             ((t (:background "#F0F0F0" :foreground "#C2C2C2" :weight bold ))))
   ;; git-gutter-fr
   `(git-gutter-fr:added                              ((t (:foreground "#E8E8E8" :weight bold))))
   `(git-gutter-fr:deleted                            ((t (:foreground "#E8E8E8" :weight bold))))
   `(git-gutter-fr:modified                           ((t (:foreground "#E8E8E8" :weight bold))))
   ;; gnus
   `(gnus-group-mail-1                                ((t (:bold t :inherit gnus-group-mail-1-empty))))
   `(gnus-group-mail-1-empty                          ((t (:inherit gnus-group-news-1-empty))))
   `(gnus-group-mail-2                                ((t (:bold t :inherit gnus-group-mail-2-empty))))
   `(gnus-group-mail-2-empty                          ((t (:inherit gnus-group-news-2-empty))))
   `(gnus-group-mail-3                                ((t (:bold t :inherit gnus-group-mail-3-empty))))
   `(gnus-group-mail-3-empty                          ((t (:inherit gnus-group-news-3-empty))))
   `(gnus-group-mail-4                                ((t (:bold t :inherit gnus-group-mail-4-empty))))
   `(gnus-group-mail-4-empty                          ((t (:inherit gnus-group-news-4-empty))))
   `(gnus-group-mail-5                                ((t (:bold t :inherit gnus-group-mail-5-empty))))
   `(gnus-group-mail-5-empty                          ((t (:inherit gnus-group-news-5-empty))))
   `(gnus-group-mail-6                                ((t (:bold t :inherit gnus-group-mail-6-empty))))
   `(gnus-group-mail-6-empty                          ((t (:inherit gnus-group-news-6-empty))))
   `(gnus-group-mail-low                              ((t (:bold t :inherit gnus-group-mail-low-empty))))
   `(gnus-group-mail-low-empty                        ((t (:inherit gnus-group-news-low-empty))))
   `(gnus-group-news-1                                ((t (:bold t :inherit gnus-group-news-1-empty))))
   `(gnus-group-news-2                                ((t (:bold t :inherit gnus-group-news-2-empty))))
   `(gnus-group-news-3                                ((t (:bold t :inherit gnus-group-news-3-empty))))
   `(gnus-group-news-4                                ((t (:bold t :inherit gnus-group-news-4-empty))))
   `(gnus-group-news-5                                ((t (:bold t :inherit gnus-group-news-5-empty))))
   `(gnus-group-news-6                                ((t (:bold t :inherit gnus-group-news-6-empty))))
   `(gnus-group-news-low                              ((t (:bold t :inherit gnus-group-news-low-empty))))
   `(gnus-header-content                              ((t (:inherit message-header-other))))
   `(gnus-header-from                                 ((t (:inherit message-header-from))))
   `(gnus-header-name                                 ((t (:inherit message-header-name))))
   `(gnus-header-newsgroups                           ((t (:inherit message-header-other))))
   `(gnus-header-subject                              ((t (:inherit message-header-subject))))
   `(gnus-summary-cancelled                           ((t (:foreground "#0E0E0E"))))
   `(gnus-summary-high-ancient                        ((t (:foreground "#0E0E0E"))))
   `(gnus-summary-high-read                           ((t (:foreground "#252525" :weight bold))))
   `(gnus-summary-high-ticked                         ((t (:foreground "#0E0E0E" :weight bold))))
   `(gnus-summary-high-unread                         ((t (:foreground "#080808" :weight bold))))
   `(gnus-summary-low-ancient                         ((t (:foreground "#0E0E0E"))))
   `(gnus-summary-low-read                            ((t (:foreground "#252525"))))
   `(gnus-summary-low-ticked                          ((t (:foreground "#0E0E0E" :weight bold))))
   `(gnus-summary-low-unread                          ((t (:foreground "#080808"))))
   `(gnus-summary-normal-ancient                      ((t (:foreground "#0E0E0E"))))
   `(gnus-summary-normal-read                         ((t (:foreground "#252525"))))
   `(gnus-summary-normal-ticked                       ((t (:foreground "#0E0E0E" :weight bold))))
   `(gnus-summary-normal-unread                       ((t (:foreground "#080808"))))
   `(gnus-summary-selected                            ((t (:foreground "#080808" :weight bold))))
   `(gnus-cite-1                                      ((t (:foreground "#0E0E0E"))))
   `(gnus-cite-10                                     ((t (:foreground "#080808"))))
   `(gnus-cite-11                                     ((t (:foreground "#080808"))))
   `(gnus-cite-2                                      ((t (:foreground "#161616"))))
   `(gnus-cite-3                                      ((t (:foreground "#252525"))))
   `(gnus-cite-4                                      ((t (:foreground "#0E0E0E"))))
   `(gnus-cite-5                                      ((t (:foreground "#161616"))))
   `(gnus-cite-6                                      ((t (:foreground "#252525"))))
   `(gnus-cite-7                                      ((t (:foreground "#161616"))))
   `(gnus-cite-8                                      ((t (:foreground "#252525"))))
   `(gnus-cite-9                                      ((t (:foreground "#252525"))))
   `(gnus-group-news-1-empty                          ((t (:foreground "#080808"))))
   `(gnus-group-news-2-empty                          ((t (:foreground "#080808"))))
   `(gnus-group-news-3-empty                          ((t (:foreground "#161616"))))
   `(gnus-group-news-4-empty                          ((t (:foreground "#252525"))))
   `(gnus-group-news-5-empty                          ((t (:foreground "#3C3C3C"))))
   `(gnus-group-news-6-empty                          ((t (:foreground "#616161"))))
   `(gnus-group-news-low-empty                        ((t (:foreground "#616161"))))
   `(gnus-signature                                   ((t (:foreground "#080808"))))
   `(gnus-x                                           ((t (:background "#080808" :foreground "#C2C2C2"))))
   ;; guide-key
   `(guide-key/highlight-command-face                 ((t (:foreground "#0E0E0E"))))
   `(guide-key/key-face                               ((t (:foreground "#252525"))))
   `(guide-key/prefix-command-face                    ((t (:foreground "#161616"))))
   ;; helm
   `(helm-header                                      ((t (:foreground "#252525" :background "#F0F0F0" :underline nil :box nil))))
   `(helm-source-header                               ((t (:foreground "#080808" :background "#D9D9D9" :underline nil :weight bold :box (:line-width -1 :style released-button)))))
   `(helm-selection                                   ((t (:background "#9D9D9D" :underline nil))))
   `(helm-selection-line                              ((t (:background "#9D9D9D"))))
   `(helm-visible-mark                                ((t (:foreground "#C2C2C2" :background "#0E0E0E"))))
   `(helm-candidate-number                            ((t (:foreground "#080808" :background "#D9D9D9"))))
   `(helm-separator                                   ((t (:foreground "#161616" :background "#F0F0F0"))))
   `(helm-time-zone-current                           ((t (:foreground "#0E0E0E" :background "#F0F0F0"))))
   `(helm-time-zone-home                              ((t (:foreground "#161616" :background "#F0F0F0"))))
   `(helm-bookmark-addressbook                        ((t (:foreground "#0E0E0E" :background "#F0F0F0"))))
   `(helm-bookmark-directory                          ((t (:foreground nil :background nil :inherit helm-ff-directory))))
   `(helm-bookmark-file                               ((t (:foreground nil :background nil :inherit helm-ff-file))))
   `(helm-bookmark-gnus                               ((t (:foreground "#161616" :background "#F0F0F0"))))
   `(helm-bookmark-info                               ((t (:foreground "#0E0E0E" :background "#F0F0F0"))))
   `(helm-bookmark-man                                ((t (:foreground "#080808" :background "#F0F0F0"))))
   `(helm-bookmark-w3m                                ((t (:foreground "#161616" :background "#F0F0F0"))))
   `(helm-buffer-not-saved                            ((t (:foreground "#161616" :background "#F0F0F0"))))
   `(helm-buffer-process                              ((t (:foreground "#080808" :background "#F0F0F0"))))
   `(helm-buffer-saved-out                            ((t (:foreground "#080808" :background "#F0F0F0"))))
   `(helm-buffer-size                                 ((t (:foreground "#616161" :background "#F0F0F0"))))
   `(helm-buffer-directory                            ((t (:foreground "#161616" :background "#F0F0F0"))))
   `(helm-lisp-completion-info                        ((t (:foreground "#161616" :background "#F0F0F0"))))
   `(helm-lisp-show-completion                        ((t (:foreground "#080808" :background "#9D9D9D"))))
   `(helm-locate-finish                               ((t (:foreground "#3C3C3C" :background "#F0F0F0"))))
   `(helm-dotted-symlink-directory                    ((t (:foreground "#616161" :background "#C2C2C2"))))
   `(helm-ff-dotted-symlink-directory                 ((t (:foreground "#616161" :background "#C2C2C2"))))
   `(helm-ff-directory                                ((t (:foreground "#080808" :background "#F0F0F0" :weight bold))))
   `(helm-ff-file                                     ((t (:foreground "#080808" :background "#F0F0F0" :weight normal))))
   `(helm-ff-executable                               ((t (:foreground "#0E0E0E" :background "#F0F0F0" :weight normal))))
   `(helm-ff-invalid-symlink                          ((t (:foreground "#161616" :background "#F0F0F0" :weight bold))))
   `(helm-ff-symlink                                  ((t (:foreground "#080808" :background "#F0F0F0" :weight bold))))
   `(helm-ff-prefix                                   ((t (:foreground "#C2C2C2" :background "#080808" :weight normal))))
   `(helm-grep-cmd-line                               ((t (:foreground "#080808" :background "#F0F0F0"))))
   `(helm-grep-file                                   ((t (:foreground "#080808" :background "#F0F0F0"))))
   `(helm-grep-finish                                 ((t (:foreground "#0E0E0E" :background "#F0F0F0"))))
   `(helm-grep-lineno                                 ((t (:foreground "#616161" :background "#F0F0F0"))))
   `(helm-match                                       ((t (:foreground "#080808" :background "#C2C2C2"))))
   `(helm-grep-match                                  ((t ( :inherit helm-match))))
   `(helm-grep-running                                ((t (:foreground "#161616" :background "#F0F0F0"))))
   `(helm-moccur-buffer                               ((t (:foreground "#080808" :background "#F0F0F0"))))
   `(helm-mu-contacts-address-face                    ((t (:foreground "#616161" :background "#F0F0F0"))))
   `(helm-mu-contacts-name-face                       ((t (:foreground "#080808" :background "#F0F0F0"))))
   `(helm-M-x-key                                     ((t (:foreground "#080808" :background "#F0F0F0" :weight bold))))
   ;; hl-line-mode
   `(hl-line-face                                     ((,class (:background "#D9D9D9")) (t :weight bold)))
   `(hl-line                                          ((,class (:background "#D9D9D9")) (t :weight bold)))
   ;; hl-sexp
   `(hl-sexp-face                                     ((,class (:background "#9D9D9D")) (t :weight bold)))
   ;; ido-mode
   `(ido-first-match                                  ((t (:foreground "#080808" :weight bold))))
   `(ido-only-match                                   ((t (:foreground "#0E0E0E" :weight bold))))
   `(ido-subdir                                       ((t (:foreground "#080808"))))
   `(ido-indicator                                    ((t (:foreground "#080808" :background "#616161"))))
   ;; iedit-mode
   `(iedit-occurrence                                 ((t (:background "#616161" :weight bold))))
   ;; js2-mode

   `(js2-warning                                      ((t (:underline "#D9D9D9"))))
   `(js2-error                                        ((t (:foreground "#161616" :weight bold))))
   `(js2-jsdoc-tag                                    ((t (:foreground "#3C3C3C"))))
   `(js2-jsdoc-type                                   ((t (:foreground "#0E0E0E"))))
   `(js2-jsdoc-value                                  ((t (:foreground "#080808"))))
   `(js2-jsdoc-html-tag-name                          ((t (:foreground "#0E0E0E"))))
   `(js2-jsdoc-html-tag-delimiter                     ((t (:foreground "#080808"))))
   `(js2-function-param                               ((t (:foreground, "#080808"))))
   `(js2-function-call                                ((t (:foreground, "#080808" :underline t))))
   `(js2-object-property                              ((t (:foreground, "#080808"  :slant italic))))
   `(js2-external-variable                            ((t (:foreground "#616161"))))

   ;; jabber-mode
   `(jabber-roster-user-away                          ((t (:foreground "#0E0E0E"))))
   `(jabber-roster-user-online                        ((t (:foreground "#161616"))))
   `(jabber-roster-user-dnd                           ((t (:foreground "#0E0E0E"))))
   `(jabber-rare-time-face                            ((t (:foreground "#161616"))))
   `(jabber-chat-prompt-local                         ((t (:foreground "#161616"))))
   `(jabber-chat-prompt-foreign                       ((t (:foreground "#0E0E0E"))))
   `(jabber-activity-face                             ((t (:foreground "#0E0E0E"))))
   `(jabber-activity-personal-face                    ((t (:foreground "#0E0E0E"))))
   `(jabber-title-small                               ((t (,@(when eziam-scale-non-headline-faces (list :height 1.1)) :weight bold))))
   `(jabber-title-medium                              ((t (,@(when eziam-scale-non-headline-faces (list :height 1.2)) :weight bold))))
   `(jabber-title-large                               ((t (,@(when eziam-scale-non-headline-faces (list :height 1.3)) :weight bold))))
   ;; ledger-mode
   `(ledger-font-payee-uncleared-face                 ((t (:foreground "#252525" :weight bold))))
   `(ledger-font-payee-cleared-face                   ((t (:foreground "#080808" :weight normal))))
   `(ledger-font-xact-highlight-face                  ((t (:background "#9D9D9D"))))
   `(ledger-font-pending-face                         ((t (:foreground "#0E0E0E" :weight normal))))
   `(ledger-font-other-face                           ((t (:foreground "#080808"))))
   `(ledger-font-posting-account-face                 ((t (:foreground "#161616"))))
   `(ledger-font-posting-account-cleared-face         ((t (:foreground "#080808"))))
   `(ledger-font-posting-account-pending-face         ((t (:foreground "#0E0E0E"))))
   `(ledger-font-posting-amount-face                  ((t (:foreground "#0E0E0E"))))
   `(ledger-font-posting-account-pending-face         ((t (:foreground "#0E0E0E"))))
   `(ledger-occur-narrowed-face                       ((t (:foreground "#616161" :invisible t))))
   `(ledger-occur-xact-face                           ((t (:background "#9D9D9D"))))
   `(ledger-font-comment-face                         ((t (:foreground "#252525"))))
   `(ledger-font-reconciler-uncleared-face            ((t (:foreground "#252525" :weight bold))))
   `(ledger-font-reconciler-cleared-face              ((t (:foreground "#080808" :weight normal))))
   `(ledger-font-reconciler-pending-face              ((t (:foreground "#0E0E0E" :weight normal))))
   `(ledger-font-report-clickable-face                ((t (:foreground "#0E0E0E" :weight normal))))
   ;; linum-mode
   `(linum                                            ((t (:foreground "#0E0E0E" :background "#F0F0F0"))))
   ;; macrostep
   `(macrostep-gensym-1                               ((t (:foreground "#0E0E0E" :background "#D9D9D9"))))
   `(macrostep-gensym-2                               ((t (:foreground "#0E0E0E" :background "#D9D9D9"))))
   `(macrostep-gensym-3                               ((t (:foreground "#0E0E0E" :background "#D9D9D9"))))
   `(macrostep-gensym-4                               ((t (:foreground "#161616" :background "#D9D9D9"))))
   `(macrostep-gensym-5                               ((t (:foreground "#080808" :background "#D9D9D9"))))
   `(macrostep-expansion-highlight-face               ((t (:inherit highlight))))
   `(macrostep-macro-face                             ((t (:underline t))))
   ;; magit
   `(magit-section-title                              ((t (:foreground "#080808" :weight bold))))
   `(magit-branch                                     ((t (:foreground "#0E0E0E" :weight bold))))
   `(magit-item-highlight                             ((t (:inverse-video t))))
   ;; egg
   `(egg-text-base                                    ((t (:foreground "#080808"))))
   `(egg-help-header-1                                ((t (:foreground "#080808"))))
   `(egg-help-header-2                                ((t (:foreground "#080808"))))
   `(egg-branch                                       ((t (:foreground "#080808"))))
   `(egg-branch-mono                                  ((t (:foreground "#080808"))))
   `(egg-term                                         ((t (:foreground "#080808"))))
   `(egg-diff-add                                     ((t (:foreground "#080808"))))
   `(egg-diff-del                                     ((t (:foreground "#0E0E0E"))))
   `(egg-diff-file-header                             ((t (:foreground "#0E0E0E"))))
   `(egg-section-title                                ((t (:foreground "#080808"))))
   `(egg-stash-mono                                   ((t (:foreground "#080808"))))
   ;; message-mode
   `(message-cited-text                               ((t (:inherit font-lock-comment-face))))
   `(message-header-name                              ((t (:foreground "#161616"))))
   `(message-header-other                             ((t (:foreground "#252525"))))
   `(message-header-to                                ((t (:foreground "#080808" :weight bold))))
   `(message-header-from                              ((t (:foreground "#080808" :weight bold))))
   `(message-header-cc                                ((t (:foreground "#080808" :weight bold))))
   `(message-header-newsgroups                        ((t (:foreground "#080808" :weight bold))))
   `(message-header-subject                           ((t (:foreground "#0E0E0E" :weight bold))))
   `(message-header-xheader                           ((t (:foreground "#252525"))))
   `(message-mml                                      ((t (:foreground "#080808" :weight bold))))
   `(message-separator                                ((t (:inherit font-lock-comment-face))))
   ;; mew
   `(mew-face-header-subject                          ((t (:foreground "#0E0E0E"))))
   `(mew-face-header-from                             ((t (:foreground "#080808"))))
   `(mew-face-header-date                             ((t (:foreground "#252525"))))
   `(mew-face-header-to                               ((t (:foreground "#161616"))))
   `(mew-face-header-key                              ((t (:foreground "#252525"))))
   `(mew-face-header-private                          ((t (:foreground "#252525"))))
   `(mew-face-header-important                        ((t (:foreground "#0E0E0E"))))
   `(mew-face-header-marginal                         ((t (:foreground "#080808" :weight bold))))
   `(mew-face-header-warning                          ((t (:foreground "#161616"))))
   `(mew-face-header-xmew                             ((t (:foreground "#252525"))))
   `(mew-face-header-xmew-bad                         ((t (:foreground "#161616"))))
   `(mew-face-body-url                                ((t (:foreground "#0E0E0E"))))
   `(mew-face-body-comment                            ((t (:foreground "#080808" :slant italic))))
   `(mew-face-body-cite1                              ((t (:foreground "#252525"))))
   `(mew-face-body-cite2                              ((t (:foreground "#0E0E0E"))))
   `(mew-face-body-cite3                              ((t (:foreground "#0E0E0E"))))
   `(mew-face-body-cite4                              ((t (:foreground "#080808"))))
   `(mew-face-body-cite5                              ((t (:foreground "#161616"))))
   `(mew-face-mark-review                             ((t (:foreground "#0E0E0E"))))
   `(mew-face-mark-escape                             ((t (:foreground "#252525"))))
   `(mew-face-mark-delete                             ((t (:foreground "#161616"))))
   `(mew-face-mark-unlink                             ((t (:foreground "#080808"))))
   `(mew-face-mark-refile                             ((t (:foreground "#252525"))))
   `(mew-face-mark-unread                             ((t (:foreground "#252525"))))
   `(mew-face-eof-message                             ((t (:foreground "#252525"))))
   `(mew-face-eof-part                                ((t (:foreground "#080808"))))
   ;; mic-paren
   `(paren-face-match                                 ((t (:foreground "#080808" :background "#D9D9D9" ))))
   `(paren-face-mismatch                              ((t (:foreground "#E8E8E8" :background "#D9D9D9" ))))
   `(paren-face-no-match                              ((t (:foreground "#9D9D9D" :background "#D9D9D9" ))))
   ;; mingus
   `(mingus-directory-face                            ((t (:foreground "#0E0E0E"))))
   `(mingus-pausing-face                              ((t (:foreground "#161616"))))
   `(mingus-playing-face                              ((t (:foreground "#080808"))))
   `(mingus-playlist-face                             ((t (:foreground "#080808" ))))
   `(mingus-song-file-face                            ((t (:foreground "#080808"))))
   `(mingus-stopped-face                              ((t (:foreground "#161616"))))
   ;; nav
   `(nav-face-heading                                 ((t (:foreground "#080808"))))
   `(nav-face-button-num                              ((t (:foreground "#080808"))))
   `(nav-face-dir                                     ((t (:foreground "#252525"))))
   `(nav-face-hdir                                    ((t (:foreground "#161616"))))
   `(nav-face-file                                    ((t (:foreground "#080808"))))
   `(nav-face-hfile                                   ((t (:foreground "#616161"))))
   ;; mu4e
   `(mu4e-header-highlight-face                       ((t (:inverse-video t))))
   `(mu4e-cited-1-face                                ((t (:foreground "#0E0E0E"    :slant italic))))
   `(mu4e-cited-2-face                                ((t (:foreground "#0E0E0E" :slant italic))))
   `(mu4e-cited-3-face                                ((t (:foreground "#252525"  :slant italic))))
   `(mu4e-cited-4-face                                ((t (:foreground "#252525"   :slant italic))))
   `(mu4e-cited-5-face                                ((t (:foreground "#616161"  :slant italic))))
   `(mu4e-cited-6-face                                ((t (:foreground "#3C3C3C" :slant italic))))
   `(mu4e-cited-7-face                                ((t (:foreground "#0E0E0E"    :slant italic))))
   `(mu4e-replied-face                                ((t (:foreground "#3C3C3C"))))
   `(mu4e-trashed-face                                ((t (:foreground "#3C3C3C" :strike-through t))))
   ;; mumamo
   `(mumamo-background-chunk-major                    ((t (:background nil))))
   `(mumamo-background-chunk-submode1                 ((t (:background "#D9D9D9"))))
   `(mumamo-background-chunk-submode2                 ((t (:background "#616161"))))
   `(mumamo-background-chunk-submode3                 ((t (:background "#3C3C3C"))))
   `(mumamo-background-chunk-submode4                 ((t (:background "#9D9D9D"))))
   ;; org-mode
   `(org-agenda-date-today                            ((t (:foreground "#080808" :slant italic :weight bold))) t)
   `(org-agenda-structure                             ((t (:inherit font-lock-comment-face))))
   `(org-archived                                     ((t (:foreground "#080808" :weight bold))))
   `(org-checkbox                                     ((t (:background "#616161" :foreground "#080808" :box (:line-width 1 :style released-button)))))
   `(org-date                                         ((t (:foreground "#0E0E0E" :underline t))))
   `(org-deadline-announce                            ((t (:foreground "#252525"))))
   `(org-formula                                      ((t (:foreground "#0E0E0E"))))
   `(org-headline-done                                ((t (:foreground "#080808"))))
   `(org-hide                                         ((t (:foreground "#D9D9D9"))))
   `(org-document-title                               ((t (:foreground "#080808" ,@(when eziam-scale-non-headline-faces (list :height 1.9)) :bold t))))
   `(org-level-1 ((,class ,ol1)))   
   ;;   `(org-level-1                                      ((t (:foreground "#080808" ,@(when eziam-scale-non-headline-faces (list :height 1.5))))))
   `(org-level-2                                      ((t (:foreground "#161616" ,@(when eziam-scale-non-headline-faces (list :height 1.2))))))
   `(org-level-3                                      ((t (:foreground "#252525" ,@(when eziam-scale-non-headline-faces (list :height 1.1))))))
   `(org-level-4                                      ((t (:foreground "#252525" ,@(when eziam-scale-non-headline-faces (list :height 1.0))))))
   `(org-level-5                                      ((t (:foreground "#252525" ,@(when eziam-scale-non-headline-faces (list :height 1.0))))))
   `(org-level-6                                      ((t (:foreground "#252525" ,@(when eziam-scale-non-headline-faces (list :height 1.0))))))
   `(org-level-7                                      ((t (:foreground "#252525" ,@(when eziam-scale-non-headline-faces (list :height 1.0))))))
   `(org-level-8                                      ((t (:foreground "#3C3C3C" ,@(when eziam-scale-non-headline-faces (list :height 1.0))))))
   `(org-link                                         ((t (:foreground "#0E0E0E" :underline t))))
   `(org-scheduled                                      ((t (:foreground "#080808"))))
   `(org-scheduled-previously                         ((t (:foreground "#161616"))))
   `(org-scheduled-today                              ((t (:foreground "#0E0E0E"))))
   `(org-sexp-date                                    ((t (:foreground "#0E0E0E" :underline t))))
   `(org-special-keyword                              ((t (:inherit font-lock-comment-face))))
   `(org-table                                        ((t (:foreground "#0E0E0E"))))
   `(org-tag                                          ((t (:bold t :weight bold))))
   `(org-time-grid                                    ((t (:foreground "#0E0E0E"))))
   `(org-done                                         ((t (:bold t :background "#161616" :foreground "#C2C2C2" :weight bold))))
   `(org-todo                                         ((t (:bold t  :background "#161616"  :foreground "#F0F0F0" :weight bold))))
   `(org-upcoming-deadline                            ((t (:inherit font-lock-keyword-face))))
   `(org-warning                                      ((t (:bold t :foreground "#161616" :weight bold :underline nil))))
   `(org-column                                       ((t (:background "#D9D9D9"))))
   `(org-column-title                                 ((t (:background "#D9D9D9" :underline t :weight bold))))
   `(org-mode-line-clock                              ((t (:foreground "#080808" :background "#D9D9D9"))))
   `(org-mode-line-clock-overrun                      ((t (:foreground "#C2C2C2" :background "#252525"))))
   `(org-ellipsis                                     ((t (:foreground "#080808" :underline t))))
   `(org-footnote                                     ((t (:foreground "#080808" :underline t))))
   `(org-meta-line                                    ((t (:foreground "#3C3C3C" ,@(when eziam-scale-non-headline-faces (list :height 1.0))))))
   `(org-block-background                             ((t (:background "#F0F0F0" ,@(when eziam-scale-non-headline-faces (list :height 1.0))))))
   `(org-block                                        ((t (:foreground "#616161" ,@(when eziam-scale-non-headline-faces (list :height 1.0))))))
   `(org-block-begin-line                             ((t (:foreground "#9D9D9D" ,@(when eziam-scale-non-headline-faces (list :height .75))))))
   `(org-block-end-line                               ((t (:inherit org-block-begin-line))))
   ;; outline
   `(outline-1                                        ((t (:foreground "#0E0E0E"))))
   `(outline-2                                        ((t (:foreground "#080808"))))
   `(outline-3                                        ((t (:foreground "#161616"))))
   `(outline-4                                        ((t (:foreground "#0E0E0E"))))
   `(outline-5                                        ((t (:foreground "#080808"))))
   `(outline-6                                        ((t (:foreground "#0E0E0E"))))
   `(outline-7                                        ((t (:foreground "#616161"))))
   `(outline-8                                        ((t (:foreground "#616161"))))
   ;; p4
   `(p4-depot-added-face                              ((t :inherit diff-added)))
   `(p4-depot-branch-op-face                          ((t :inherit diff-changed)))
   `(p4-depot-deleted-face                            ((t :inherit diff-removed)))
   `(p4-depot-unmapped-face                           ((t :inherit diff-changed)))
   `(p4-diff-change-face                              ((t :inherit diff-changed)))
   `(p4-diff-del-face                                 ((t :inherit diff-removed)))
   `(p4-diff-file-face                                ((t :inherit diff-file-header)))
   `(p4-diff-head-face                                ((t :inherit diff-header)))
   `(p4-diff-ins-face                                 ((t :inherit diff-added)))
   ;; perspective
   `(persp-selected-face                              ((t (:foreground "#0E0E0E" :inherit mode-line))))
   ;; powerline
   `(powerline-active1                                ((t (:background "#9D9D9D" :foreground "#0E0E0E" :box nil :inherit mode-line ))))
   `(powerline-active2                                ((t (:background "#D9D9D9" :foreground "#3C3C3C" :box nil :inherit mode-line ))))
   `(powerline-inactive1                              ((t (:background "#D9D9D9" :foreground "#9D9D9D" :inherit mode-line-inactive))))
   `(powerline-inactive2                              ((t (:background "#E8E8E8" :foreground "#616161" :inherit mode-line-inactive))))
   ;; proofgeneral
   `(proof-active-area-face                           ((t (:underline t))))
   `(proof-boring-face                                ((t (:foreground "#080808" :background "#616161"))))
   `(proof-command-mouse-highlight-face               ((t (:inherit proof-mouse-highlight-face))))
   `(proof-debug-message-face                         ((t (:inherit proof-boring-face))))
   `(proof-declaration-name-face                      ((t (:inherit font-lock-keyword-face :foreground nil))))
   `(proof-eager-annotation-face                      ((t (:foreground "#C2C2C2" :background "#0E0E0E"))))
   `(proof-error-face                                 ((t (:foreground "#080808" :background "#616161"))))
   `(proof-highlight-dependency-face                  ((t (:foreground "#C2C2C2" :background "#080808"))))
   `(proof-highlight-dependent-face                   ((t (:foreground "#C2C2C2" :background "#0E0E0E"))))
   `(proof-locked-face                                ((t (:background "#9D9D9D"))))
   `(proof-mouse-highlight-face                       ((t (:foreground "#C2C2C2" :background "#0E0E0E"))))
   `(proof-queue-face                                 ((t (:background "#616161"))))
   `(proof-region-mouse-highlight-face                ((t (:inherit proof-mouse-highlight-face))))
   `(proof-script-highlight-error-face                ((t (:background "#252525"))))
   `(proof-tacticals-name-face                        ((t (:inherit font-lock-constant-face :foreground nil :background "#F0F0F0"))))
   `(proof-tactics-name-face                          ((t (:inherit font-lock-constant-face :foreground nil :background "#F0F0F0"))))
   `(proof-warning-face                               ((t (:foreground "#C2C2C2" :background "#080808"))))
   ;; rainbow-delimiters
   `(rainbow-delimiters-depth-1-face                  ((t (:foreground "#616161"))))
   `(rainbow-delimiters-depth-2-face                  ((t (:foreground "#3C3C3C"))))
   `(rainbow-delimiters-depth-3-face                  ((t (:foreground "#252525"))))
   `(rainbow-delimiters-depth-4-face                  ((t (:foreground "#161616"))))
   `(rainbow-delimiters-depth-5-face                  ((t (:foreground "#0E0E0E"))))
   `(rainbow-delimiters-depth-6-face                  ((t (:foreground "#080808"))))
   `(rainbow-delimiters-depth-7-face                  ((t (:foreground "#080808"))))
   `(rainbow-delimiters-depth-8-face                  ((t (:foreground "#080808"))))
   `(rainbow-delimiters-depth-9-face                  ((t (:foreground "#080808"))))
   `(rainbow-delimiters-depth-10-face                 ((t (:foreground "#080808"))))
   `(rainbow-delimiters-depth-11-face                 ((t (:foreground "#080808"))))
   `(rainbow-delimiters-depth-12-face                 ((t (:foreground "#080808"))))
   ;; rcirc
   `(rcirc-my-nick                                    ((t (:foreground "#0E0E0E"))))
   `(rcirc-other-nick                                 ((t (:foreground "#0E0E0E"))))
   `(rcirc-bright-nick                                ((t (:foreground "#0E0E0E"))))
   `(rcirc-dim-nick                                   ((t (:foreground "#252525"))))
   `(rcirc-server                                     ((t (:foreground "#252525"))))
   `(rcirc-server-prefix                              ((t (:foreground "#161616"))))
   `(rcirc-timestamp                                  ((t (:foreground "#0E0E0E"))))
   `(rcirc-nick-in-message                            ((t (:foreground "#080808"))))
   `(rcirc-nick-in-message-full-line                  ((t (:bold t))))
   `(rcirc-prompt                                     ((t (:foreground "#080808" :bold t))))
   `(rcirc-track-nick                                 ((t (:inverse-video t))))
   `(rcirc-track-keyword                              ((t (:bold t))))
   `(rcirc-url                                        ((t (:bold t))))
   `(rcirc-keyword                                    ((t (:foreground "#080808" :bold t))))
   ;; rpm-mode
   `(rpm-spec-dir-face                                ((t (:foreground "#252525"))))
   `(rpm-spec-doc-face                                ((t (:foreground "#252525"))))
   `(rpm-spec-ghost-face                              ((t (:foreground "#161616"))))
   `(rpm-spec-macro-face                              ((t (:foreground "#080808"))))
   `(rpm-spec-obsolete-tag-face                       ((t (:foreground "#161616"))))
   `(rpm-spec-package-face                            ((t (:foreground "#161616"))))
   `(rpm-spec-section-face                            ((t (:foreground "#080808"))))
   `(rpm-spec-tag-face                                ((t (:foreground "#0E0E0E"))))
   `(rpm-spec-var-face                                ((t (:foreground "#161616"))))
   ;; rst-mode
   `(rst-level-1-face                                 ((t (:foreground "#0E0E0E"))))
   `(rst-level-2-face                                 ((t (:foreground "#161616"))))
   `(rst-level-3-face                                 ((t (:foreground "#161616"))))
   `(rst-level-4-face                                 ((t (:foreground "#0E0E0E"))))
   `(rst-level-5-face                                 ((t (:foreground "#080808"))))
   `(rst-level-6-face                                 ((t (:foreground "#3C3C3C"))))
   ;; sh-mode
   `(sh-heredoc                                       ((t (:foreground "#080808" :bold t))))
   `(sh-quoted-exec                                   ((t (:foreground "#161616"))))
   ;; show-paren
   `(show-paren-mismatch                         ((t (:foreground "#C2C2C2" :background "#616161" :weight bold))))
   `(show-paren-match                            ((t (:foreground "#0E0E0E" :background "#D9D9D9"  :weight bold))))
   ;; smartparens
   `(sp-show-pair-mismatch-face                       ((t (:foreground "#080808" :background "#D9D9D9"))))
   `(sp-show-pair-match-face                          ((t (:foreground "#080808" :background "#9D9D9D" :underline nil))))
   ;; sml-mode-line
   `(sml-modeline-end-face                            ((t :inherit default :width condensed)))
   ;; SLIME
   `(slime-repl-output-face                           ((t (:foreground "#161616"))))
   `(slime-repl-inputed-output-face                   ((t (:foreground "#252525"))))
   `(slime-error-face                                 ((((supports :underline (:style wave))) (:underline (:style wave :color "#161616"))) (t (:underline "#161616"))))
   `(slime-warning-face                               ((((supports :underline (:style wave))) (:underline (:style wave :color "#0E0E0E"))) (t (:underline "#0E0E0E"))))
   `(slime-style-warning-face                         ((((supports :underline (:style wave))) (:underline (:style wave :color "#080808"))) (t (:underline "#080808"))))
   `(slime-note-face                                  ((((supports :underline (:style wave))) (:underline (:style wave :color "#252525"))) (t (:underline "#252525"))))
   `(slime-highlight-face                             ((t (:inherit highlight))))
   ;; speedbar
   `(speedbar-button-face                             ((t (:foreground "#0E0E0E"))))
   `(speedbar-directory-face                          ((t (:foreground "#080808"))))
   `(speedbar-file-face                               ((t (:foreground "#080808"))))
   `(speedbar-highlight-face                          ((t (:foreground "#C2C2C2" :background "#0E0E0E"))))
   `(speedbar-selected-face                           ((t (:foreground "#161616"))))
   `(speedbar-separator-face                          ((t (:foreground "#C2C2C2" :background "#161616"))))
   `(speedbar-tag-face                                ((t (:foreground "#080808"))))
   ;; tabbar
   `(tabbar-button                                    ((t (:foreground "#080808" :background "#F0F0F0"))))
   `(tabbar-selected                                  ((t (:foreground "#080808" :background "#F0F0F0" :box (:line-width -1 :style pressed-button)))))
   `(tabbar-unselected                                ((t (:foreground "#080808" :background "#9D9D9D" :box (:line-width -1 :style released-button)))))
   ;; term
   `(term-color-black                                 ((t (:foreground "#C2C2C2" :background "#D9D9D9"))))
   `(term-color-red                                   ((t (:foreground "#252525" :background "#616161"))))
   `(term-color-green                                 ((t (:foreground "#252525" :background "#0E0E0E"))))
   `(term-color-yellow                                ((t (:foreground "#0E0E0E" :background "#080808"))))
   `(term-color-blue                                  ((t (:foreground "#161616" :background "#616161"))))
   `(term-color-magenta                               ((t (:foreground "#161616" :background "#161616"))))
   `(term-color-cyan                                  ((t (:foreground "#080808" :background "#0E0E0E"))))
   `(term-color-white                                 ((t (:foreground "#080808" :background "#616161"))))
   '(term-default-fg-color                            ((t (:inherit term-color-white))))
   '(term-default-bg-color                            ((t (:inherit term-color-black))))
   ;; undo-tree
   `(undo-tree-visualizer-active-branch-face          ((t (:foreground "#080808" :weight bold))))
   `(undo-tree-visualizer-current-face                ((t (:foreground "#252525" :weight bold))))
   `(undo-tree-visualizer-default-face                ((t (:foreground "#080808"))))
   `(undo-tree-visualizer-register-face               ((t (:foreground "#080808"))))
   `(undo-tree-visualizer-unmodified-face             ((t (:foreground "#080808"))))
   ;; volatile-highlights
   `(vhl/default-face                                 ((t (:background "#F0F0F0"))))
   ;; emacs-w3m
   `(w3m-anchor                                       ((t (:foreground "#080808" :background "#F0F0F0" :underline t :weight normal))))
   `(w3m-current-anchor                               ((t (:foreground "#080808" :background "#C2C2C2" :underline nil :weight bold))))
   `(w3m-arrived-anchor-face                          ((t (:foreground "#616161" :background "#C2C2C2" :underline t :weight normal))))
   `(w3m-image-anchor-face                            ((t (:foreground "#161616"  :background "#C2C2C2" :underline t :weight normal))))
   `(w3m-image-face                                   ((t (:foreground "#0E0E0E" :background "#C2C2C2" :underline t :weight normal))))
   `(w3m-image-anchor                                 ((t (:foreground "#0E0E0E" :background "#C2C2C2" :underline t :weight normal))))
   `(w3m-form                                         ((t (:foreground "#252525" :underline t))))
   `(w3m-header-line-location-title                   ((t (:foreground "#616161" :background "#C2C2C2" :underline nil :weight normal))))
   `(w3m-header-line-location-content                 ((t (:foreground "#080808" :background "#C2C2C2" :underline nil :weight normal))))
   `(w3m-history-current-url                          ((t (:inherit match))))
   `(w3m-tab-background                               ((t (:foreground "#C2C2C2" :background "#252525" :underline nil :weight normal))) )
   `(w3m-tab-unselected-retrieving                    ((t (:foreground "#C2C2C2" :background "#252525" :underline nil :weight normal))) )
   `(w3m-tab-selected-background-face                 ((t (:foreground "#C2C2C2" :background "#0E0E0E" :underline nil :weight bold))) )
   `(w3m-tab-selected-retrieving                      ((t (:foreground "#C2C2C2" :background "#0E0E0E" :underline nil :weight bold))) )
   `(w3m-lnum                                         ((t (:foreground "#0E0E0E" :background "#F0F0F0"))))
   `(w3m-lnum-match                                   ((t (:background "#D9D9D9" :foreground "#0E0E0E" :weight bold))))
   `(w3m-lnum-minibuffer-prompt                       ((t (:foreground "#080808"))))
   ;; web-mode
   `(web-mode-builtin-face                            ((t (:inherit ,font-lock-builtin-face))))
   `(web-mode-comment-face                            ((t (:inherit ,font-lock-comment-face))))
   `(web-mode-constant-face                           ((t (:inherit ,font-lock-constant-face))))
   `(web-mode-css-at-rule-face                        ((t (:foreground "#0E0E0E" ))))
   `(web-mode-css-prop-face                           ((t (:foreground "#0E0E0E"))))
   `(web-mode-css-pseudo-class-face                   ((t (:foreground "#080808" :weight bold))))
   `(web-mode-css-rule-face                           ((t (:foreground "#0E0E0E"))))
   `(web-mode-doctype-face                            ((t (:inherit ,font-lock-comment-face))))
   `(web-mode-folded-face                             ((t (:underline t))))
   `(web-mode-function-name-face                      ((t (:foreground "#0E0E0E"))))
   `(web-mode-html-attr-name-face                     ((t (:foreground "#0E0E0E"))))
   `(web-mode-html-attr-value-face                    ((t (:inherit ,font-lock-string-face))))
   `(web-mode-html-tag-face                           ((t (:foreground "#080808"))))
   `(web-mode-keyword-face                            ((t (:inherit ,font-lock-keyword-face))))
   `(web-mode-preprocessor-face                       ((t (:inherit ,font-lock-preprocessor-face))))
   `(web-mode-string-face                             ((t (:inherit ,font-lock-string-face))))
   `(web-mode-type-face                               ((t (:inherit ,font-lock-type-face))))
   `(web-mode-variable-name-face                      ((t (:inherit ,font-lock-variable-name-face))))
   `(web-mode-server-background-face                  ((t (:background "#F0F0F0"))))
   `(web-mode-server-comment-face                     ((t (:inherit web-mode-comment-face))))
   `(web-mode-server-string-face                      ((t (:inherit web-mode-string-face))))
   `(web-mode-symbol-face                             ((t (:inherit font-lock-constant-face))))
   `(web-mode-warning-face                            ((t (:inherit font-lock-warning-face))))
   `(web-mode-whitespaces-face                        ((t (:background "#161616"))))
   ;; whitespace-mode
   `(whitespace-space                                 ((t (:background "#9D9D9D" :foreground "#9D9D9D"))))
   `(whitespace-hspace                                ((t (:background "#9D9D9D" :foreground "#9D9D9D"))))
   `(whitespace-tab                                   ((t (:background "#252525"))))
   `(whitespace-newline                               ((t (:foreground "#9D9D9D"))))
   `(whitespace-trailing                              ((t (:background "#161616"))))
   `(whitespace-line                                  ((t (:background "#F0F0F0" :foreground "#161616"))))
   `(whitespace-space-before-tab                      ((t (:background "#0E0E0E" :foreground "#0E0E0E"))))
   `(whitespace-indentation                           ((t (:background "#080808" :foreground "#161616"))))
   `(whitespace-empty                                 ((t (:background "#080808"))))
   `(whitespace-space-after-tab                       ((t (:background "#080808" :foreground "#161616"))))
   ;; wanderlust
   `(wl-highlight-folder-few-face                     ((t (:foreground "#252525"))))
   `(wl-highlight-folder-many-face                    ((t (:foreground "#252525"))))
   `(wl-highlight-folder-path-face                    ((t (:foreground "#0E0E0E"))))
   `(wl-highlight-folder-unread-face                  ((t (:foreground "#0E0E0E"))))
   `(wl-highlight-folder-zero-face                    ((t (:foreground "#080808"))))
   `(wl-highlight-folder-unknown-face                 ((t (:foreground "#0E0E0E"))))
   `(wl-highlight-message-citation-header             ((t (:foreground "#252525"))))
   `(wl-highlight-message-cited-text-1                ((t (:foreground "#161616"))))
   `(wl-highlight-message-cited-text-2                ((t (:foreground "#0E0E0E"))))
   `(wl-highlight-message-cited-text-3                ((t (:foreground "#0E0E0E"))))
   `(wl-highlight-message-cited-text-4                ((t (:foreground "#0E0E0E"))))
   `(wl-highlight-message-header-contents-face        ((t (:foreground "#252525"))))
   `(wl-highlight-message-headers-face                ((t (:foreground "#0E0E0E"))))
   `(wl-highlight-message-important-header-contents   ((t (:foreground "#0E0E0E"))))
   `(wl-highlight-message-header-contents             ((t (:foreground "#161616"))))
   `(wl-highlight-message-important-header-contents2  ((t (:foreground "#0E0E0E"))))
   `(wl-highlight-message-signature                   ((t (:foreground "#252525"))))
   `(wl-highlight-message-unimportant-header-contents ((t (:foreground "#080808"))))
   `(wl-highlight-summary-answered-face               ((t (:foreground "#0E0E0E"))))
   `(wl-highlight-summary-disposed-face               ((t (:foreground "#080808" :slant italic))))
   `(wl-highlight-summary-new-face                    ((t (:foreground "#0E0E0E"))))
   `(wl-highlight-summary-normal-face                 ((t (:foreground "#080808"))))
   `(wl-highlight-summary-thread-top-face             ((t (:foreground "#080808"))))
   `(wl-highlight-thread-indent-face                  ((t (:foreground "#161616"))))
   `(wl-highlight-summary-refiled-face                ((t (:foreground "#080808"))))
   `(wl-highlight-summary-displaying-face             ((t (:underline t :weight bold))))
   ;; which-func-mode
   `(which-func                                       ((t (:foreground "#080808"))))
   ;; yascroll
   `(yascroll:thumb-text-area                         ((t (:background "#D9D9D9"))))
   `(yascroll:thumb-fringe                            ((t (:background "#D9D9D9" :foreground "#D9D9D9"))))
   `(minimap-active-region-background                 ((t (:background "#9D9D9D" :foreground "#616161"))))
   ;; html fold/unfold face
   `(html-fold-unfolded-face                          ((t (:background "#F0F0F0"))))
   `(html-fold-folded-face                            ((t (:foreground "#080808" :bold t))))
   ;; markdown mode
   `(markdown-header-delimiter-face                   ((t (:weight normal :foreground "#9D9D9D"))))
   `(markdown-header-face-1                           ((t (:inherit markdown-header-face ,@(when eziam-scale-non-headline-faces (list :height 1.5))))))
   `(markdown-header-face-2                           ((t (:inherit markdown-header-face ,@(when eziam-scale-non-headline-faces (list :height 1.3))))))
   `(markdown-header-face-3                           ((t (:inherit markdown-header-face :underline t ,@(when eziam-scale-non-headline-faces (list :height 1.2))))))
   `(markdown-header-face-4                           ((t (:inherit markdown-header-face :underline t ,@(when eziam-scale-non-headline-faces (list :height 1.1))))))
   `(markdown-header-face-5                           ((t (:inherit markdown-header-face :underline t))))
   `(markdown-header-face-6                           ((t (:inherit markdown-header-face :underline t))))
   `(markdown-link-face                               ((t (:underline t :foreground "#080808"))))
   `(markdown-url-face                                ((t (:underline t :foreground "#080808"))))
   `(markdown-pre-face                                ((t (:foreground "#080808" ,@(when eziam-scale-non-headline-faces (list :height .8))))))
   `(markdown-bold-face                               ((t (:foreground "#3C3C3C" :bold t ))))
   `(markdown-italic-face                             ((t (:foreground "#3C3C3C" :italic t ))))
   `(markdown-list-face                               ((t (:foreground "#080808"))))
   `(markdown-markup-face                             ((t (:foreground "#9D9D9D" ))))
   ;; swoop
   `(swoop-face-line-buffer-name                      ((t (:background "#252525" :foreground "#C2C2C2"))))
   `(swoop-face-target-line                           ((t (:background "#616161" :foreground "#080808"))))
   `(swoop-face-line-number                           ((t (:background "#F0F0F0" :foreground "#9D9D9D"))))
   `(swoop-face-header-format-line                    ((t (:background "#9D9D9D" :foreground "#C2C2C2"))))
   `(swoop-face-target-words                          ((t (:background "#9D9D9D" :foreground "#080808"))))
   `(highlight-indentation-face                       ((t (:background "#C2C2C2"))))
   `(highlight-indentation-current-column-face        ((t (:background "#D9D9D9"))))
   ;; company
   `(company-echo-common                              ((t (:foreground "#080808"))))
   `(company-preview                                  ((t (:background "#9D9D9D" :foreground "#0E0E0E"))))
   `(company-preview-common                           ((t (:inherit company-preview :foreground "#080808" :weight bold))))
   `(company-scrollbar-fg                             ((t (:background "#616161"))))
   `(company-tooltip                                  ((t (:background "#9D9D9D" :foreground "#0E0E0E"))))
   `(company-tooltip-annotation                       ((t (:inherit company-tooltip :foreground "#E8E8E8"))))
   `(company-tooltip-common                           ((t (:inherit company-tooltip :foreground "#0E0E0E"))))
   `(company-tooltip-common-selection                 ((t (:inherit company-tooltip-selection :foreground "#080808"))))
   `(company-tooltip-selection                        ((t (:inherit company-tooltip :background "#3C3C3C" :foreground "#C2C2C2"))))
   `(company-scrollbar-bg                             ((t (:inherit company-tooltip))))
   ;; eval-sexp-fu
   `(eval-sexp-fu-flash                               ((t (:background "#C2C2C2"))))
   `(eval-sexp-fu-flash-error                         ((t (:background "#0E0E0E" :foreground "#C2C2C2"))))
   ;; neotree
   `(neo-dir-link-face                                ((t (:inherit diredp-dir-priv))))
   `(neo-expand-btn-face                              ((t (:foreground "#0E0E0E" :bold t))))
   `(neo-file-link-face                               ((t (:foreground "#252525"))))
   `(neo-root-dir-face                                ((t (:foreground "#3C3C3C" :background "#E8E8E8"))))
   ;; geiser
   `(geiser-font-lock-doc-link                        ((t (:foreground "#0E0E0E" :underline t))))
   `(geiser-font-lock-error-link                        ((t (:foreground "#0E0E0E" :underline t))))
   `(geiser-font-lock-autodoc-identifier              ((t (:foreground "#3C3C3C" :bold t))))
   `(compilation-error                                ((t (:foreground "#080808" :underline t :bold t))))
   ;; elixir
   `(elixir-atom-face                                 ((t (:foreground "#080808" :bold t))))
   ;; tuareg
   `(tuareg-font-lock-operator-face                   ((t (:inherit ,font-lock-variable-name-face))))
   `(tuareg-font-lock-governing-face                  ((t (:inherit ,font-lock-keyword-face))))
   ;; avy
   `(avy-lead-face                                    ((t (:background "#3C3C3C" :foreground "#C2C2C2" :bold t))))
   `(avy-lead-face-0                                  ((t (:background "#252525"  :foreground "#C2C2C2"  :bold t))))
   `(avy-lead-face-1                                  ((t (:background "#161616"  :foreground "#C2C2C2" :bold t))))
   `(avy-lead-face-2                                  ((t (:background "#0E0E0E"  :foreground "#C2C2C2" :bold t))))
   `(avy-background-face                              ((t (:background "#D9D9D9"  :foreground "#616161" :bold t))))
   )
  )

;; Theme Variables
(custom-theme-set-variables
 'eziam-light
 ;; ansi-color
 `(ansi-color-names-vector ["#C2C2C2"
                            "#161616"
                            "#252525"
                            "#080808"
                            "#0E0E0E"
                            "#161616"
                            "#080808"
                            "#080808"])
 ;; fill-column-indicator
 `(fci-rule-color "#F0F0F0")
 ;; vc-annotate
 `(vc-annotate-color-map
   '(( 20. . "#616161")
     ( 40. . "#3C3C3C")
     ( 60. . "#3C3C3C")
     ( 80. . "#252525")
     (100. . "#252525")
     (120. . "#161616")
     (140. . "#161616")
     (160. . "#0E0E0E")
     (180. . "#0E0E0E")
     (200. . "#0E0E0E")
     (220. . "#080808")
     (240. . "#080808")
     (260. . "#080808")
     (280. . "#080808")
     (300. . "#080808")
     (320. . "#080808")
     (340. . "#080808")
     (360. . "#080808")))
 `(vc-annotate-very-old-color "#161616")
 `(vc-annotate-background "#D9D9D9")
 )

;;; Footer
(provide-theme 'eziam-light)

;;;###autoload

;; Local Variables:
;; mode: emacs-lisp;
;; no-byte-compile: t
;; indent-tabs-mode: nil
;; End:
;;; eziam-light-theme.el ends here
