
;;; eziam-light-theme.el --- The light Eziam theme for Emacs
;;;
;;; Commentary:
;;
;; This file was automatically generated, you should not edit it.  See
;; README.org for more information.
;;
;; Copyright and licence information in eziam-common.el
;;; Code:





(require 'eziam-common)

(deftheme eziam-light "The light Eziam color theme")

(let ((class '((class color) (min-colors 89)))

      ;; Eziam generic colors.
      (ol1                 `(,@(when eziam-scale-outline-headlines (list :height 1.8)) :overline t :background "#FFFFFF"  :weight bold ))
      (ol2                 `(,@(when eziam-scale-outline-headlines (list :height 1.5)) :overline t :background "#D6EAF4" ))
      (ol3                 `(,@(when eziam-scale-outline-headlines (list :height 1.2)) :overline t :weight bold :background "#B4C8D2" ))
      (ol4                 `(,@(when eziam-scale-outline-headlines (list :height 1.0)) :overline t :background "#92A6B0"))
      (ol5                 `(:overline t :overline t :weight bold :foreground "#800080"))
      (ol6                 `(:overline t :weight bold :slant italic :foreground "#008080"))
      (ol7                 `(:overline t :weight bold :slant italic :foreground "#000080"))
      (ol8                 `(:overline t :slant italic :foreground "#FF0000"))
      (highlight           `(:inverse-video t))
      (transient-highlight `(:background "#ffff00"))
      (info-text           `(:underline (:color "#2244ff")))
      (warning-text        `(:underline (:color "#ffaa00" :style wave)))
      (error-text          `(:underline (:color "#ff0000")))
      )

  (custom-theme-set-faces
   'eziam-light
   ;; Built-in
   `(bold                                             ((t (:weight bold))))
   `(default                                          ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(button                                           ((t (:underline t))))
   `(link                                             ((t (:foreground "#000000" :underline t :weight bold))))
   `(link-visited                                     ((t (:foreground "#000000" :underline t :weight normal))))
   `(hl-paren-face                                    ((t (:foreground "#000000" :background "#EEEEEE" :weight bold))))
   `(cursor                                           ((t (:foreground "#000000" :background "#000000"))))
   `(escape-glyph                                     ((t (:foreground "#000000" :bold t))))
   `(fringe                                           ((t (:foreground "#AAAAAA" :background "#DDDDDD","#FFFFFF"))))
   `(header-line                                      ((t (:inherit mode-line))))
   `(highlight                                        ((,class ,highlight)))
   `(region                                           ((t (:background "#CCCCCC" :foreground "#EEEEEE"))))
   `(shadow                                           ((t (:foreground "#CCCCCC"))))
   `(success                                          ((t (:foreground "#555555" :weight bold))))
   `(warning                                          ((t (:foreground "#000000" :weight bold))))
    ;; @FIXED - Don't set foreground for bold: it is used by some modes on a different background (eg tabulated-list-mode)

   ;; compilation
   `(compilation-column-face                          ((t (:foreground "#000000"))))
   `(compilation-enter-directory-face                 ((t (:foreground "#555555"))))
   `(compilation-error-face                           ((t (:foreground "#555555" :weight bold :underline t))))
   `(compilation-face                                 ((t (:foreground "#000000"))))
   `(compilation-info-face                            ((t (:foreground "#000000"))))
   `(compilation-info                                 ((t (:foreground "#000000" :underline t))))
   `(compilation-leave-directory-face                 ((t (:foreground "#555555"))))
   `(compilation-line-face                            ((t (:foreground "#000000"))))
   `(compilation-line-number                          ((t (:foreground "#000000"))))
   `(compilation-message-face                         ((t (:foreground "#000000"))))
   `(compilation-warning-face                         ((t (:foreground "#000000" :weight bold :underline t))))
   `(compilation-mode-line-exit                       ((t (:foreground "#000000" :weight bold))))
   `(compilation-mode-line-fail                       ((t (:foreground "#222222" :weight bold))))
   `(compilation-mode-line-run                        ((t (:foreground "#000000" :weight bold))))
   ;; grep
   `(grep-context-face                                ((t (:foreground "#000000"))))
   `(grep-error-face                                  ((t (:foreground "#555555" :weight bold :underline t))))
   `(grep-hit-face                                    ((t (:foreground "#000000"))))
   `(grep-match-face                                  ((t (:foreground "#000000" :weight bold))))
   `(match                                            ((t (:background "#EEEEEE" :foreground "#000000" :weight bold))))
   ;; haskell-mode @TODO: This is a work-in-progress
   `(haskell-literate-comment-face                    ((t (:background "#FFFFFF"))))
   ;; make
   `(makefile-space                                   ((t (:background "#EEEEEE"))))
   `(makefile-targets                                 ((t (:underline t))))
   `(makefile-shell                                   ((t (:slant italic))))
   ;; isearch
   `(isearch                                          ((,class ,transient-highlight)))
   `(isearch-fail                                     ((t (:foreground "#000000" :background "#AAAAAA"))))
   `(lazy-highlight                                   ((t (:foreground "#000000" :weight bold :background "#DDDDDD"))))
   `(menu                                             ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(minibuffer-prompt                                ((t (:foreground "#000000" :color "#EEEEEE"))))
   `(mode-line                                        ((t (:foreground "#EEEEEE" :background "#555555" :box nil ))))
   `(mode-line-inactive                               ((t (:foreground "#EEEEEE" :background "#AAAAAA" :box nil ))))
   `(mode-line-buffer-id                              ((t (:foreground "#EEEEEE" :weight bold))))
   `(secondary-selection                              ((t (:background "#EEEEEE"))))
   `(cua-rectangle                                    ((t (:background "#EEEEEE"))))
   `(trailing-whitespace                              ((t (:background "#222222"))))
   `(vertical-border                                  ((t (:foreground "#AAAAAA" :background "#EEEEEE"))))
   ;; font lock
   `(font-lock-builtin-face                           ((t (:foreground "#000000" :weight bold))))
   `(font-lock-comment-face                           ((t (:foreground "#888888" :slant italic))))
   `(font-lock-delimiter-face                         ((t (:foreground "#888888" :slant italic))))
   `(font-lock-constant-face                          ((t (:foreground "#888888" :weight bold))))
   `(font-lock-doc-face                               ((t (:foreground "#AAAAAA"))))
   `(font-lock-function-name-face                     ((t (:background "#FFFFFF" :box (:color "#DDDDDD")))))
   `(font-lock-keyword-face                           ((t (:foreground "#000000" :weight bold))))
   `(font-lock-negation-char-face                     ((t (:foreground "#000000" :weight bold))))
   `(font-lock-preprocessor-face                      ((t (:foreground "#000000"))))
   `(font-lock-regexp-grouping-construct              ((t (:foreground "#000000" :weight bold))))
   `(font-lock-regexp-grouping-backslash              ((t (:foreground "#555555" :weight bold))))
   `(font-lock-string-face                            ((t (:foreground "#888888"))))
   `(font-lock-type-face                              ((t (:foreground "#222222" :underline t))))
   `(font-lock-variable-name-face                     ((t (:foreground "#000000" ))))
   `(font-lock-warning-face                           ((t (:foreground "#000000" :weight bold))))
   `(c-annotation-face                                ((t (:inherit font-lock-constant-face))))
   ;; newsticker
   `(newsticker-date-face                             ((t (:foreground "#000000"))))
   `(newsticker-default-face                          ((t (:foreground "#000000"))))
   `(newsticker-enclosure-face                        ((t (:foreground "#000000"))))
   `(newsticker-extra-face                            ((t (:foreground "#AAAAAA" ,@(when eziam-scale-non-headline-faces (list :height 0.8)))))) ;; FIXME
   `(newsticker-feed-face ((t (:foreground "#000000"))))
   `(newsticker-immortal-item-face                    ((t (:foreground "#555555"))))
   `(newsticker-new-item-face                         ((t (:foreground "#000000"))))
   `(newstickerphone-obsolete-item-face               ((t (:foreground "#222222"))))
   `(newsticker-old-item-face                         ((t (:foreground "#888888"))))
   `(newsticker-statistics-face                       ((t (:foreground "#000000"))))
   `(newsticker-treeview-face                         ((t (:foreground "#000000"))))
   `(newsticker-treeview-immortal-face                ((t (:foreground "#555555"))))
   `(newsticker-treeview-listwindow-face              ((t (:foreground "#000000"))))
   `(newsticker-treeview-new-face                     ((t (:foreground "#000000" :weight bold))))
   `(newsticker-treeview-obsolete-face                ((t (:foreground "#222222"))))
   `(newsticker-treeview-old-face                     ((t (:foreground "#888888"))))
   `(newsticker-treeview-selection-face               ((t (:background "#EEEEEE" :foreground "#000000"))))
   ;; Third-party
   ;; highlight-symbol
   `(highlight-symbol-face                            ((t (:background "#EEEEEE"))))
   ;; ace-jump
   `(ace-jump-face-background                         ((t (:foreground "#CCCCCC" :background "#EEEEEE" :inverse-video nil))))
   `(ace-jump-face-foreground                         ((t (:foreground "#000000" :background "#EEEEEE" :inverse-video nil))))
   ;; anzu
   `(anzu-mode-line                                   ((t (:foreground "#000000" :weight bold))))
   ;; full-ack
   `(ack-separator                                    ((t (:foreground "#000000"))))
   `(ack-file                                         ((t (:foreground "#000000"))))
   `(ack-line                                         ((t (:foreground "#000000"))))
   `(ack-match                                        ((t (:foreground "#000000" :background "#EEEEEE" :weight bold))))
   ;; auctex
   `(font-latex-bold-face                             ((t (:inherit bold))))
   `(font-latex-warning-face                          ((t (:foreground nil :inherit font-lock-warning-face))))
   `(font-latex-sectioning-5-face                     ((t (:foreground "#222222" :weight bold ))))
   `(font-latex-sedate-face                           ((t (:foreground "#000000"))))
   `(font-latex-italic-face                           ((t (:foreground "#000000" :slant italic))))
   `(font-latex-string-face                           ((t (:inherit ,font-lock-string-face))))
   `(font-latex-math-face                             ((t (:foreground "#000000"))))
   ;; auto-complete
   `(ac-candidate-face                                ((t (:background "#888888" :foreground "#EEEEEE" :underline nil))))
   `(ac-selection-face                                ((t (:background "#AAAAAA" :foreground "#000000" :underline nil))))
   `(ac-yasnippet-candidate-face                      ((t (:background "#888888" :foreground "#EEEEEE"))))
   `(ac-yasnippet-selection-face                      ((t (:background "#AAAAAA" :foreground "#000000"))))
   `(ac-slime-menu-face                               ((t (:background "#888888" :foreground "#EEEEEE"))))
   `(ac-slime-selection-face                          ((t (:background "#AAAAAA" :foreground "#000000"))))
   `(ac-gtags-candidate-face                          ((t (:background "#888888" :foreground "#EEEEEE"))))
   `(ac-gtags-selection-face                          ((t (:background "#AAAAAA" :foreground "#000000"))))
   `(ac-emmet-candidate-face                          ((t (:background "#888888" :foreground "#EEEEEE"))))
   `(ac-emmet-selection-face                          ((t (:background "#AAAAAA" :foreground "#000000"))))

   `(popup-tip-face                                   ((t (:background "#000000" :foreground "#EEEEEE"))))
   `(popup-scroll-bar-foreground-face                 ((t (:background "#CCCCCC"))))
   `(popup-scroll-bar-background-face                 ((t (:background "#EEEEEE"))))
   `(popup-isearch-match                              ((t (:background "#EEEEEE" :foreground "#000000"))))
   ;; android mode
   `(android-mode-debug-face                          ((t (:foreground "#222222"))))
   `(android-mode-error-face                          ((t (:foreground "#000000" :weight bold))))
   `(android-mode-info-face                           ((t (:foreground "#000000"))))
   `(android-mode-verbose-face                        ((t (:foreground "#555555"))))
   `(android-mode-warning-face                        ((t (:foreground "#000000"))))
   ;; bm
   `(bm-face                                          ((t (:background "#000000" :foreground "#DDDDDD"))))
   `(bm-fringe-face                                   ((t (:background "#EEEEEE" :foreground "#EEEEEE"))))
   `(bm-fringe-persistent-face                        ((t (:background "#EEEEEE" :foreground "#EEEEEE"))))
   `(bm-persistent-face                               ((t (:background "#888888" :foreground "#DDDDDD"))))
   ;; clojure-test-mode
   `(clojure-test-failure-face                        ((t (:foreground "#000000" :weight bold :underline t))))
   `(clojure-test-error-face                          ((t (:foreground "#222222" :weight bold :underline t))))
   `(clojure-test-success-face                        ((t (:foreground "#222222" :weight bold :underline t))))
   ;; coq
   `(coq-solve-tactics-face                           ((t (:foreground nil :inherit font-lock-constant-face))))
   ;; ctable
   `(ctbl:face-cell-select                            ((t (:background "#000000" :foreground "#DDDDDD"))))
   `(ctbl:face-continue-bar                           ((t (:background "#EEEEEE" :foreground "#DDDDDD"))))
   `(ctbl:face-row-select                             ((t (:background "#000000" :foreground "#DDDDDD"))))
   ;; diff
   `(diff-added                                       ((,class (:foreground "#000000" :background nil)) (t (:foreground "#888888" :background nil))))
   `(diff-changed                                     ((t (:foreground "#000000"))))
   `(diff-removed                                     ((,class (:foreground "#222222" :background nil)) (t (:foreground "#888888" :background nil))))
   `(diff-refine-added                                ((t :inherit diff-added :weight bold)))
   `(diff-refine-change                               ((t :inherit diff-changed :weight bold)))
   `(diff-refine-removed                              ((t :inherit diff-removed :weight bold)))
   `(diff-header                                      ((,class (:background "#AAAAAA")) (t (:background "#000000" :foreground "#DDDDDD"))))
   `(diff-file-header                                 ((,class (:background "#AAAAAA" :foreground "#000000" :bold t)) (t (:background "#000000" :foreground "#DDDDDD" :bold t))))
   ;; dired
   `(dired-directory                                  ((t (:foreground "#000000" :bold t))))
   ;; dired+
   `(diredp-display-msg                               ((t (:foreground "#000000"))))
   `(diredp-compressed-file-suffix                    ((t (:foreground "#000000"))))
   `(diredp-date-time                                 ((t (:foreground "#222222"))))
   `(diredp-deletion                                  ((t (:foreground "#000000"))))
   `(diredp-deletion-file-name                        ((t (:foreground "#222222"))))
   `(diredp-dir-heading                               ((t (:foreground "#000000" :background "#EEEEEE" :bold t))))
   `(diredp-dir-priv                                  ((t (:foreground "#000000" :bold t))))
   `(diredp-dir-name                                  ((t (:foreground "#000000" :bold t))))
   `(diredp-exec-priv                                 ((t (:foreground "#222222"))))
   `(diredp-executable-tag                            ((t (:foreground "#222222"))))
   `(diredp-file-name                                 ((t (:foreground "#000000"))))
   `(diredp-file-suffix                               ((t (:foreground "#000000" :bold t))))
   `(diredp-flag-mark                                 ((t (:foreground "#000000"))))
   `(diredp-flag-mark-line                            ((t (:foreground "#000000"))))
   `(diredp-ignored-file-name                         ((t (:foreground "#CCCCCC"))))
   `(diredp-link-priv                                 ((t (:foreground "#000000"))))
   `(diredp-mode-line-flagged                         ((t (:foreground "#000000"))))
   `(diredp-mode-line-marked                          ((t (:foreground "#000000"))))
   `(diredp-no-priv                                   ((t (:foreground "#000000"))))
   `(diredp-number                                    ((t (:foreground "#222222"))))
   `(diredp-other-priv                                ((t (:foreground "#000000"))))
   `(diredp-rare-priv                                 ((t (:foreground "#555555"))))
   `(diredp-read-priv                                 ((t (:foreground "#888888"))))
   `(diredp-symlink                                   ((t (:foreground "#000000"))))
   `(diredp-write-priv                                ((t (:foreground "#222222"))))
   ;; ediff
   `(ediff-current-diff-A                             ((t (:foreground "#000000" :background "#AAAAAA"))))
   `(ediff-current-diff-Ancestor                      ((t (:foreground "#000000" :background "#AAAAAA"))))
   `(ediff-current-diff-B                             ((t (:foreground "#000000" :background "#888888"))))
   `(ediff-current-diff-C                             ((t (:foreground "#000000" :background "#CCCCCC"))))
   `(ediff-even-diff-A                                ((t (:background "#CCCCCC"))))
   `(ediff-even-diff-Ancestor                         ((t (:background "#CCCCCC"))))
   `(ediff-even-diff-B                                ((t (:background "#CCCCCC"))))
   `(ediff-even-diff-C                                ((t (:background "#CCCCCC"))))
   `(ediff-fine-diff-A                                ((t (:foreground "#000000" :background "#555555" :weight bold))))
   `(ediff-fine-diff-Ancestor                         ((t (:foreground "#000000" :background "#555555" :weight bold))))
   `(ediff-fine-diff-B                                ((t (:foreground "#000000" :background "#555555" :weight bold))))
   `(ediff-fine-diff-C                                ((t (:foreground "#000000" :background "#888888" :weight bold ))))
   `(ediff-odd-diff-A                                 ((t (:background "#AAAAAA"))))
   `(ediff-odd-diff-Ancestor                          ((t (:background "#AAAAAA"))))
   `(ediff-odd-diff-B                                 ((t (:background "#AAAAAA"))))
   `(ediff-odd-diff-C                                 ((t (:background "#AAAAAA"))))
   ;; ert
   `(ert-test-result-expected                         ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(ert-test-result-unexpected                       ((t (:foreground "#222222" :background "#EEEEEE"))))
   ;; eshell
   `(eshell-prompt                                    ((t (:foreground "#000000" :weight bold))))
   `(eshell-ls-archive                                ((t (:foreground "#555555" :weight bold))))
   `(eshell-ls-backup                                 ((t (:inherit font-lock-comment-face))))
   `(eshell-ls-clutter                                ((t (:inherit font-lock-comment-face))))
   `(eshell-ls-directory                              ((t (:foreground "#000000" :weight bold))))
   `(eshell-ls-executable                             ((t (:foreground "#000000" :weight bold))))
   `(eshell-ls-unreadable                             ((t (:foreground "#000000"))))
   `(eshell-ls-missing                                ((t (:inherit font-lock-warning-face))))
   `(eshell-ls-product                                ((t (:inherit font-lock-doc-face))))
   `(eshell-ls-special                                ((t (:foreground "#000000" :weight bold))))
   `(eshell-ls-symlink                                ((t (:foreground "#000000" :weight bold))))
   ;; flx
   `(flx-highlight-face                               ((t (:foreground "#000000" :weight bold))))
   ;; flycheck
   `(flycheck-error                                   ((t (:underline (:color "#ff0000")))))
   `(flycheck-warning                                 ((t (:underline (:color "#ffaa00")))))
   `(flycheck-info                                    ((t (:underline (:color "#2244ff")))))
   `(flycheck-fringe-error                            ((t (:foreground "#ff0000"))))
   `(flycheck-fringe-warning                          ((t (:foreground "#ffaa00"))))
   `(flycheck-fringe-info                             ((t (:foreground "#2244ff"))))
   ;; flymake
   `(flymake-errline                                  ((,class ,error-text)))
   `(flymake-warnline                                 ((,class ,warning-text)))
   `(flymake-infoline                                 ((,class ,info-text)))
   ;; flyspell
   `(flyspell-duplicate                               ((,class ,warning-text)))
   `(flyspell-incorrect                               ((,class ,warning-text)))
   ;; erc
   `(erc-action-face                                  ((t (:inherit erc-default-face))))
   `(erc-bold-face                                    ((t (:weight bold))))
   `(erc-current-nick-face                            ((t (:foreground "#000000" :weight bold))))
   `(erc-dangerous-host-face                          ((t (:inherit font-lock-warning-face))))
   `(erc-default-face                                 ((t (:foreground "#000000"))))
   `(erc-direct-msg-face                              ((t (:inherit erc-default))))
   `(erc-error-face                                   ((t (:inherit font-lock-warning-face))))
   `(erc-fool-face                                    ((t (:inherit erc-default))))
   `(erc-highlight-face                               ((t (:inherit hover-highlight))))
   `(erc-input-face                                   ((t (:foreground "#000000"))))
   `(erc-keyword-face                                 ((t (:foreground "#000000" :weight bold))))
   `(erc-nick-default-face                            ((t (:foreground "#000000" :weight bold))))
   `(erc-my-nick-face                                 ((t (:foreground "#222222" :weight bold))))
   `(erc-nick-msg-face                                ((t (:inherit erc-default))))
   `(erc-notice-face                                  ((t (:foreground "#555555"))))
   `(erc-pal-face                                     ((t (:foreground "#000000" :weight bold))))
   `(erc-prompt-face                                  ((t (:foreground "#000000" :background "#EEEEEE" :weight bold))))
   `(erc-timestamp-face                               ((t (:foreground "#000000"))))
   `(erc-underline-face                               ((t (:underline t))))
   ;; git-gutter
   `(git-gutter:added                                 ((t (:background "#EEEEEE" :foreground "#EEEEEE" :weight bold ))))
   `(git-gutter:deleted                               ((t (:background "#EEEEEE" :foreground "#EEEEEE" :weight bold ))))
   `(git-gutter:modified                              ((t (:background "#EEEEEE" :foreground "#EEEEEE" :weight bold ))))
   `(git-gutter:unchanged                             ((t (:background "#EEEEEE" :foreground "#EEEEEE" :weight bold ))))
   ;; git-gutter-fr
   `(git-gutter-fr:added                              ((t (:foreground "#EEEEEE" :weight bold))))
   `(git-gutter-fr:deleted                            ((t (:foreground "#EEEEEE" :weight bold))))
   `(git-gutter-fr:modified                           ((t (:foreground "#EEEEEE" :weight bold))))
   ;; gnus
   `(gnus-group-mail-1                                ((t (:bold t :inherit gnus-group-mail-1-empty))))
   `(gnus-group-mail-1-empty                          ((t (:inherit gnus-group-news-1-empty))))
   `(gnus-group-mail-2                                ((t (:bold t :inherit gnus-group-mail-2-empty))))
   `(gnus-group-mail-2-empty                          ((t (:inherit gnus-group-news-2-empty))))
   `(gnus-group-mail-3                                ((t (:bold t :inherit gnus-group-mail-3-empty))))
   `(gnus-group-mail-3-empty                          ((t (:inherit gnus-group-news-3-empty))))
   `(gnus-group-mail-4                                ((t (:bold t :inherit gnus-group-mail-4-empty))))
   `(gnus-group-mail-4-empty                          ((t (:inherit gnus-group-news-4-empty))))
   `(gnus-group-mail-5                                ((t (:bold t :inherit gnus-group-mail-5-empty))))
   `(gnus-group-mail-5-empty                          ((t (:inherit gnus-group-news-5-empty))))
   `(gnus-group-mail-6                                ((t (:bold t :inherit gnus-group-mail-6-empty))))
   `(gnus-group-mail-6-empty                          ((t (:inherit gnus-group-news-6-empty))))
   `(gnus-group-mail-low                              ((t (:bold t :inherit gnus-group-mail-low-empty))))
   `(gnus-group-mail-low-empty                        ((t (:inherit gnus-group-news-low-empty))))
   `(gnus-group-news-1                                ((t (:bold t :inherit gnus-group-news-1-empty))))
   `(gnus-group-news-2                                ((t (:bold t :inherit gnus-group-news-2-empty))))
   `(gnus-group-news-3                                ((t (:bold t :inherit gnus-group-news-3-empty))))
   `(gnus-group-news-4                                ((t (:bold t :inherit gnus-group-news-4-empty))))
   `(gnus-group-news-5                                ((t (:bold t :inherit gnus-group-news-5-empty))))
   `(gnus-group-news-6                                ((t (:bold t :inherit gnus-group-news-6-empty))))
   `(gnus-group-news-low                              ((t (:bold t :inherit gnus-group-news-low-empty))))
   `(gnus-header-content                              ((t (:inherit message-header-other))))
   `(gnus-header-from                                 ((t (:inherit message-header-from))))
   `(gnus-header-name                                 ((t (:inherit message-header-name))))
   `(gnus-header-newsgroups                           ((t (:inherit message-header-other))))
   `(gnus-header-subject                              ((t (:inherit message-header-subject))))
   `(gnus-summary-cancelled                           ((t (:foreground "#000000"))))
   `(gnus-summary-high-ancient                        ((t (:foreground "#000000"))))
   `(gnus-summary-high-read                           ((t (:foreground "#555555" :weight bold))))
   `(gnus-summary-high-ticked                         ((t (:foreground "#000000" :weight bold))))
   `(gnus-summary-high-unread                         ((t (:foreground "#000000" :weight bold))))
   `(gnus-summary-low-ancient                         ((t (:foreground "#000000"))))
   `(gnus-summary-low-read                            ((t (:foreground "#555555"))))
   `(gnus-summary-low-ticked                          ((t (:foreground "#000000" :weight bold))))
   `(gnus-summary-low-unread                          ((t (:foreground "#000000"))))
   `(gnus-summary-normal-ancient                      ((t (:foreground "#000000"))))
   `(gnus-summary-normal-read                         ((t (:foreground "#555555"))))
   `(gnus-summary-normal-ticked                       ((t (:foreground "#000000" :weight bold))))
   `(gnus-summary-normal-unread                       ((t (:foreground "#000000"))))
   `(gnus-summary-selected                            ((t (:foreground "#000000" :weight bold))))
   `(gnus-cite-1                                      ((t (:foreground "#000000"))))
   `(gnus-cite-10                                     ((t (:foreground "#000000"))))
   `(gnus-cite-11                                     ((t (:foreground "#000000"))))
   `(gnus-cite-2                                      ((t (:foreground "#222222"))))
   `(gnus-cite-3                                      ((t (:foreground "#555555"))))
   `(gnus-cite-4                                      ((t (:foreground "#000000"))))
   `(gnus-cite-5                                      ((t (:foreground "#222222"))))
   `(gnus-cite-6                                      ((t (:foreground "#555555"))))
   `(gnus-cite-7                                      ((t (:foreground "#222222"))))
   `(gnus-cite-8                                      ((t (:foreground "#555555"))))
   `(gnus-cite-9                                      ((t (:foreground "#555555"))))
   `(gnus-group-news-1-empty                          ((t (:foreground "#000000"))))
   `(gnus-group-news-2-empty                          ((t (:foreground "#000000"))))
   `(gnus-group-news-3-empty                          ((t (:foreground "#222222"))))
   `(gnus-group-news-4-empty                          ((t (:foreground "#555555"))))
   `(gnus-group-news-5-empty                          ((t (:foreground "#888888"))))
   `(gnus-group-news-6-empty                          ((t (:foreground "#AAAAAA"))))
   `(gnus-group-news-low-empty                        ((t (:foreground "#AAAAAA"))))
   `(gnus-signature                                   ((t (:foreground "#000000"))))
   `(gnus-x                                           ((t (:background "#000000" :foreground "#DDDDDD"))))
   ;; guide-key
   `(guide-key/highlight-command-face                 ((t (:foreground "#000000"))))
   `(guide-key/key-face                               ((t (:foreground "#555555"))))
   `(guide-key/prefix-command-face                    ((t (:foreground "#222222"))))
   ;; helm
   `(helm-header                                      ((t (:foreground "#555555" :background "#EEEEEE" :underline nil :box nil))))
   `(helm-source-header                               ((t (:foreground "#000000" :background "#EEEEEE" :underline nil :weight bold :box (:line-width -1 :style released-button)))))
   `(helm-selection                                   ((t (:background "#CCCCCC" :underline nil))))
   `(helm-selection-line                              ((t (:background "#CCCCCC"))))
   `(helm-visible-mark                                ((t (:foreground "#DDDDDD" :background "#000000"))))
   `(helm-candidate-number                            ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(helm-separator                                   ((t (:foreground "#222222" :background "#EEEEEE"))))
   `(helm-time-zone-current                           ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(helm-time-zone-home                              ((t (:foreground "#222222" :background "#EEEEEE"))))
   `(helm-bookmark-addressbook                        ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(helm-bookmark-directory                          ((t (:foreground nil :background nil :inherit helm-ff-directory))))
   `(helm-bookmark-file                               ((t (:foreground nil :background nil :inherit helm-ff-file))))
   `(helm-bookmark-gnus                               ((t (:foreground "#222222" :background "#EEEEEE"))))
   `(helm-bookmark-info                               ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(helm-bookmark-man                                ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(helm-bookmark-w3m                                ((t (:foreground "#222222" :background "#EEEEEE"))))
   `(helm-buffer-not-saved                            ((t (:foreground "#222222" :background "#EEEEEE"))))
   `(helm-buffer-process                              ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(helm-buffer-saved-out                            ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(helm-buffer-size                                 ((t (:foreground "#AAAAAA" :background "#EEEEEE"))))
   `(helm-buffer-directory                            ((t (:foreground "#222222" :background "#EEEEEE"))))
   `(helm-lisp-completion-info                        ((t (:foreground "#222222" :background "#EEEEEE"))))
   `(helm-lisp-show-completion                        ((t (:foreground "#000000" :background "#CCCCCC"))))
   `(helm-locate-finish                               ((t (:foreground "#888888" :background "#EEEEEE"))))
   `(helm-dotted-symlink-directory                    ((t (:foreground "#AAAAAA" :background "#DDDDDD"))))
   `(helm-ff-dotted-symlink-directory                 ((t (:foreground "#AAAAAA" :background "#DDDDDD"))))
   `(helm-ff-directory                                ((t (:foreground "#000000" :background "#EEEEEE" :weight bold))))
   `(helm-ff-file                                     ((t (:foreground "#000000" :background "#EEEEEE" :weight normal))))
   `(helm-ff-executable                               ((t (:foreground "#000000" :background "#EEEEEE" :weight normal))))
   `(helm-ff-invalid-symlink                          ((t (:foreground "#222222" :background "#EEEEEE" :weight bold))))
   `(helm-ff-symlink                                  ((t (:foreground "#000000" :background "#EEEEEE" :weight bold))))
   `(helm-ff-prefix                                   ((t (:foreground "#DDDDDD" :background "#000000" :weight normal))))
   `(helm-grep-cmd-line                               ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(helm-grep-file                                   ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(helm-grep-finish                                 ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(helm-grep-lineno                                 ((t (:foreground "#AAAAAA" :background "#EEEEEE"))))
   `(helm-match                                       ((t (:foreground "#000000" :background "#DDDDDD"))))
   `(helm-grep-match                                  ((t ( :inherit helm-match))))
   `(helm-grep-running                                ((t (:foreground "#222222" :background "#EEEEEE"))))
   `(helm-moccur-buffer                               ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(helm-mu-contacts-address-face                    ((t (:foreground "#AAAAAA" :background "#EEEEEE"))))
   `(helm-mu-contacts-name-face                       ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(helm-M-x-key                                     ((t (:foreground "#000000" :background "#EEEEEE" :weight bold))))
   ;; hl-line-mode FIXME Looks weird
   `(hl-line                                          ((,class ,highlight)))
   `(hl-line-face                                     ((,class ,highlight)))
   ;; hl-sexp
   `(hl-sexp-face                                     ((,class (:background "#CCCCCC")) (t :weight bold)))
   ;; ido-mode
   `(ido-first-match                                  ((t (:foreground "#000000" :weight bold))))
   `(ido-only-match                                   ((t (:foreground "#000000" :weight bold))))
   `(ido-subdir                                       ((t (:foreground "#000000"))))
   `(ido-indicator                                    ((t (:foreground "#000000" :background "#AAAAAA"))))
   ;; iedit-mode
   `(iedit-occurrence                                 ((t (:background "#AAAAAA" :weight bold))))
   ;; js2-mode

   `(js2-warning                                      ((t (:underline "#EEEEEE"))))
   `(js2-error                                        ((t (:foreground "#222222" :weight bold))))
   `(js2-jsdoc-tag                                    ((t (:foreground "#888888"))))
   `(js2-jsdoc-type                                   ((t (:foreground "#000000"))))
   `(js2-jsdoc-value                                  ((t (:foreground "#000000"))))
   `(js2-jsdoc-html-tag-name                          ((t (:foreground "#000000"))))
   `(js2-jsdoc-html-tag-delimiter                     ((t (:foreground "#000000"))))
   `(js2-function-param                               ((t (:foreground, "#000000"))))
   `(js2-function-call                                ((t (:foreground, "#000000" :underline t))))
   `(js2-object-property                              ((t (:foreground, "#000000"  :slant italic))))
   `(js2-external-variable                            ((t (:foreground "#AAAAAA"))))

   ;; jabber-mode
   `(jabber-roster-user-away                          ((t (:foreground "#000000"))))
   `(jabber-roster-user-online                        ((t (:foreground "#222222"))))
   `(jabber-roster-user-dnd                           ((t (:foreground "#000000"))))
   `(jabber-rare-time-face                            ((t (:foreground "#222222"))))
   `(jabber-chat-prompt-local                         ((t (:foreground "#222222"))))
   `(jabber-chat-prompt-foreign                       ((t (:foreground "#000000"))))
   `(jabber-activity-face                             ((t (:foreground "#000000"))))
   `(jabber-activity-personal-face                    ((t (:foreground "#000000"))))
   `(jabber-title-small                               ((t (,@(when eziam-scale-non-headline-faces (list :height 1.1)) :weight bold))))
   `(jabber-title-medium                              ((t (,@(when eziam-scale-non-headline-faces (list :height 1.2)) :weight bold))))
   `(jabber-title-large                               ((t (,@(when eziam-scale-non-headline-faces (list :height 1.3)) :weight bold))))
   ;; ledger-mode
   `(ledger-font-payee-uncleared-face                 ((t (:foreground "#555555" :weight bold))))
   `(ledger-font-payee-cleared-face                   ((t (:foreground "#000000" :weight normal))))
   `(ledger-font-xact-highlight-face                  ((t (:background "#CCCCCC"))))
   `(ledger-font-pending-face                         ((t (:foreground "#000000" :weight normal))))
   `(ledger-font-other-face                           ((t (:foreground "#000000"))))
   `(ledger-font-posting-account-face                 ((t (:foreground "#222222"))))
   `(ledger-font-posting-account-cleared-face         ((t (:foreground "#000000"))))
   `(ledger-font-posting-account-pending-face         ((t (:foreground "#000000"))))
   `(ledger-font-posting-amount-face                  ((t (:foreground "#000000"))))
   `(ledger-font-posting-account-pending-face         ((t (:foreground "#000000"))))
   `(ledger-occur-narrowed-face                       ((t (:foreground "#AAAAAA" :invisible t))))
   `(ledger-occur-xact-face                           ((t (:background "#CCCCCC"))))
   `(ledger-font-comment-face                         ((t (:foreground "#555555"))))
   `(ledger-font-reconciler-uncleared-face            ((t (:foreground "#555555" :weight bold))))
   `(ledger-font-reconciler-cleared-face              ((t (:foreground "#000000" :weight normal))))
   `(ledger-font-reconciler-pending-face              ((t (:foreground "#000000" :weight normal))))
   `(ledger-font-report-clickable-face                ((t (:foreground "#000000" :weight normal))))
   ;; linum-mode
   `(linum                                            ((t (:background "#DDDDDD" :foreground "#555555" :inherit default)))) ;; @fringe
   ;; linum-relative-mode
   `(linum-relative-current-face                      ((t (:background "#EEEEEE" :foreground "#000000" :weight bold :inherit default)))) ;; @fringe
   ;; macrostep
   `(macrostep-gensym-1                               ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(macrostep-gensym-2                               ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(macrostep-gensym-3                               ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(macrostep-gensym-4                               ((t (:foreground "#222222" :background "#EEEEEE"))))
   `(macrostep-gensym-5                               ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(macrostep-expansion-highlight-face               ((t (:inherit highlight))))
   `(macrostep-macro-face                             ((t (:underline t))))
   ;; magit
   `(magit-section-title                              ((t (:foreground "#000000" :weight bold))))
   `(magit-branch                                     ((t (:foreground "#000000" :weight bold))))
   `(magit-item-highlight                             ((t (:inverse-video t))))
   ;; egg
   `(egg-text-base                                    ((t (:foreground "#000000"))))
   `(egg-help-header-1                                ((t (:foreground "#000000"))))
   `(egg-help-header-2                                ((t (:foreground "#000000"))))
   `(egg-branch                                       ((t (:foreground "#000000"))))
   `(egg-branch-mono                                  ((t (:foreground "#000000"))))
   `(egg-term                                         ((t (:foreground "#000000"))))
   `(egg-diff-add                                     ((t (:foreground "#000000"))))
   `(egg-diff-del                                     ((t (:foreground "#000000"))))
   `(egg-diff-file-header                             ((t (:foreground "#000000"))))
   `(egg-section-title                                ((t (:foreground "#000000"))))
   `(egg-stash-mono                                   ((t (:foreground "#000000"))))
   ;; message-mode
   `(message-cited-text                               ((t (:inherit font-lock-comment-face))))
   `(message-header-name                              ((t (:foreground "#222222"))))
   `(message-header-other                             ((t (:foreground "#555555"))))
   `(message-header-to                                ((t (:foreground "#000000" :weight bold))))
   `(message-header-from                              ((t (:foreground "#000000" :weight bold))))
   `(message-header-cc                                ((t (:foreground "#000000" :weight bold))))
   `(message-header-newsgroups                        ((t (:foreground "#000000" :weight bold))))
   `(message-header-subject                           ((t (:foreground "#000000" :weight bold))))
   `(message-header-xheader                           ((t (:foreground "#555555"))))
   `(message-mml                                      ((t (:foreground "#000000" :weight bold))))
   `(message-separator                                ((t (:inherit font-lock-comment-face))))
   ;; mew
   `(mew-face-header-subject                          ((t (:foreground "#000000"))))
   `(mew-face-header-from                             ((t (:foreground "#000000"))))
   `(mew-face-header-date                             ((t (:foreground "#555555"))))
   `(mew-face-header-to                               ((t (:foreground "#222222"))))
   `(mew-face-header-key                              ((t (:foreground "#555555"))))
   `(mew-face-header-private                          ((t (:foreground "#555555"))))
   `(mew-face-header-important                        ((t (:foreground "#000000"))))
   `(mew-face-header-marginal                         ((t (:foreground "#000000" :weight bold))))
   `(mew-face-header-warning                          ((t (:foreground "#222222"))))
   `(mew-face-header-xmew                             ((t (:foreground "#555555"))))
   `(mew-face-header-xmew-bad                         ((t (:foreground "#222222"))))
   `(mew-face-body-url                                ((t (:foreground "#000000"))))
   `(mew-face-body-comment                            ((t (:foreground "#000000" :slant italic))))
   `(mew-face-body-cite1                              ((t (:foreground "#555555"))))
   `(mew-face-body-cite2                              ((t (:foreground "#000000"))))
   `(mew-face-body-cite3                              ((t (:foreground "#000000"))))
   `(mew-face-body-cite4                              ((t (:foreground "#000000"))))
   `(mew-face-body-cite5                              ((t (:foreground "#222222"))))
   `(mew-face-mark-review                             ((t (:foreground "#000000"))))
   `(mew-face-mark-escape                             ((t (:foreground "#555555"))))
   `(mew-face-mark-delete                             ((t (:foreground "#222222"))))
   `(mew-face-mark-unlink                             ((t (:foreground "#000000"))))
   `(mew-face-mark-refile                             ((t (:foreground "#555555"))))
   `(mew-face-mark-unread                             ((t (:foreground "#555555"))))
   `(mew-face-eof-message                             ((t (:foreground "#555555"))))
   `(mew-face-eof-part                                ((t (:foreground "#000000"))))
   ;; mic-paren
   `(paren-face-match                                 ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(paren-face-mismatch                              ((t (:foreground "#EEEEEE" :background "#EEEEEE"))))
   `(paren-face-no-match                              ((t (:foreground "#CCCCCC" :background "#EEEEEE"))))
   ;; mingus
   `(mingus-directory-face                            ((t (:foreground "#000000"))))
   `(mingus-pausing-face                              ((t (:foreground "#222222"))))
   `(mingus-playing-face                              ((t (:foreground "#000000"))))
   `(mingus-playlist-face                             ((t (:foreground "#000000" ))))
   `(mingus-song-file-face                            ((t (:foreground "#000000"))))
   `(mingus-stopped-face                              ((t (:foreground "#222222"))))
   ;; nav
   `(nav-face-heading                                 ((t (:foreground "#000000"))))
   `(nav-face-button-num                              ((t (:foreground "#000000"))))
   `(nav-face-dir                                     ((t (:foreground "#555555"))))
   `(nav-face-hdir                                    ((t (:foreground "#222222"))))
   `(nav-face-file                                    ((t (:foreground "#000000"))))
   `(nav-face-hfile                                   ((t (:foreground "#AAAAAA"))))
   ;; mu4e
   `(mu4e-header-highlight-face                       ((, class ,highlight)))
   `(mu4e-cited-1-face                                ((t (:foreground "#000000"    :slant italic))))
   `(mu4e-cited-2-face                                ((t (:foreground "#000000" :slant italic))))
   `(mu4e-cited-3-face                                ((t (:foreground "#555555"  :slant italic))))
   `(mu4e-cited-4-face                                ((t (:foreground "#555555"   :slant italic))))
   `(mu4e-cited-5-face                                ((t (:foreground "#AAAAAA"  :slant italic))))
   `(mu4e-cited-6-face                                ((t (:foreground "#888888" :slant italic))))
   `(mu4e-cited-7-face                                ((t (:foreground "#000000"    :slant italic))))
   `(mu4e-replied-face                                ((t (:foreground "#888888"))))
   `(mu4e-trashed-face                                ((t (:foreground "#888888" :strike-through t))))
   ;; mumamo
   `(mumamo-background-chunk-major                    ((t (:background nil))))
   `(mumamo-background-chunk-submode1                 ((t (:background "#EEEEEE"))))
   `(mumamo-background-chunk-submode2                 ((t (:background "#AAAAAA"))))
   `(mumamo-background-chunk-submode3                 ((t (:background "#888888"))))
   `(mumamo-background-chunk-submode4                 ((t (:background "#CCCCCC"))))
   ;; org-mode
   `(org-agenda-date-today                            ((t (:foreground "#000000" :slant italic :weight bold))) t)
   `(org-agenda-structure                             ((t (:inherit font-lock-comment-face))))
   `(org-archived                                     ((t (:foreground "#000000" :weight bold))))
   `(org-checkbox                                     ((t (:background "#AAAAAA" :foreground "#000000" :box (:line-width 1 :style released-button)))))
   `(org-date                                         ((t (:foreground "#000000" :underline t))))
   `(org-deadline-announce                            ((t (:foreground "#555555"))))
   `(org-formula                                      ((t (:foreground "#AAAAAA"))))
   `(org-headline-done                                ((t (:foreground "#000000"))))
   `(org-hide                                         ((t (:foreground "#EEEEEE"))))
   `(org-document-title                               ((t (:foreground "#000000" ,@(when eziam-scale-non-headline-faces (list :height 1.9)) :bold t))))
   `(org-document-info                                ((t (:inherit default))))
   `(org-level-1                                      ((,class ,ol1)))
   `(org-level-2                                      ((,class ,ol2)))
   `(org-level-3                                      ((,class ,ol3)))
   `(org-level-4                                      ((,class ,ol4)))
   `(org-level-5                                      ((,class ,ol5)))
   `(org-level-6                                      ((,class ,ol6)))
   `(org-level-7                                      ((,class ,ol7)))
   `(org-level-8                                      ((,class ,ol8)))
   `(org-link                                         ((t (:foreground "#000000" :underline t))))
   `(org-list-dt                                      ((t (:weight bold))))
   `(org-property-value                               ((t (:foreground "#888888" :slant italic))))
   `(org-scheduled                                    ((t (:foreground "#000000"))))
   `(org-scheduled-previously                         ((t (:foreground "#222222"))))
   `(org-scheduled-today                              ((t (:foreground "#000000"))))
   `(org-sexp-date                                    ((t (:foreground "#000000" :underline t))))
   `(org-special-keyword                              ((t (:foreground "#888888"))))
   `(org-table                                        ((t (:foreground "#000000"))))
   `(org-tag                                          ((t (,@(when eziam-scale-outline-headlines (list :height 1.0)) :foreground "#AAAAAA"))))
   `(org-time-grid                                    ((t (:foreground "#000000"))))
   `(org-done                                         ((t (:bold t :background "#222222" :foreground "#EEEEEE" :weight bold))))
   `(org-todo                                         ((t (:bold t :inverse-video t))))
   `(org-upcoming-deadline                            ((t (:inherit font-lock-keyword-face))))
   `(org-warning                                      ((t (:bold t :foreground "#222222" :weight bold :underline nil))))
   `(org-column                                       ((t (:background "#EEEEEE"))))
   `(org-column-title                                 ((t (:background "#EEEEEE" :underline t :weight bold))))
   `(org-mode-line-clock                              ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(org-mode-line-clock-overrun                      ((t (:foreground "#DDDDDD" :background "#555555"))))
   `(org-ellipsis                                     ((t (:foreground "#000000" :underline t))))
   `(org-footnote                                     ((t (:foreground "#000000" :underline t))))
   `(org-meta-line                                    ((t (:foreground "#AAAAAA"))))
   ;; I believe the difference between org-block-background and
   ;; org-block is that org 8.x uses the former, 9.x the latter.  Both
   ;; should then be identical.
   `(org-block-background                             ((t (:background "#FFFFFF"))))
   `(org-block                                        ((t (:background "#FFFFFF"))))
   `(org-block-begin-line                             ((t (:foreground "#222222" :background "#CCCCCC"))))
   `(org-block-end-line                               ((t (:foreground "#222222" :background "#CCCCCC"))))
   ;; outline
   `(outline-1                                        ((t (:foreground "#000000"))))
   `(outline-2                                        ((t (:foreground "#000000"))))
   `(outline-3                                        ((t (:foreground "#222222"))))
   `(outline-4                                        ((t (:foreground "#000000"))))
   `(outline-5                                        ((t (:foreground "#000000"))))
   `(outline-6                                        ((t (:foreground "#000000"))))
   `(outline-7                                        ((t (:foreground "#AAAAAA"))))
   `(outline-8                                        ((t (:foreground "#AAAAAA"))))
   ;; p4
   `(p4-depot-added-face                              ((t :inherit diff-added)))
   `(p4-depot-branch-op-face                          ((t :inherit diff-changed)))
   `(p4-depot-deleted-face                            ((t :inherit diff-removed)))
   `(p4-depot-unmapped-face                           ((t :inherit diff-changed)))
   `(p4-diff-change-face                              ((t :inherit diff-changed)))
   `(p4-diff-del-face                                 ((t :inherit diff-removed)))
   `(p4-diff-file-face                                ((t :inherit diff-file-header)))
   `(p4-diff-head-face                                ((t :inherit diff-header)))
   `(p4-diff-ins-face                                 ((t :inherit diff-added)))
   ;; perspective
   `(persp-selected-face                              ((t (:foreground "#000000" :inherit mode-line))))
   ;; powerline
   `(powerline-active1                                ((t (:background "#CCCCCC" :foreground "#000000" :box nil :inherit mode-line ))))
   `(powerline-active2                                ((t (:background "#EEEEEE" :foreground "#888888" :box nil :inherit mode-line ))))
   `(powerline-inactive1                              ((t (:background "#EEEEEE" :foreground "#CCCCCC" :inherit mode-line-inactive))))
   `(powerline-inactive2                              ((t (:background "#EEEEEE" :foreground "#AAAAAA" :inherit mode-line-inactive))))
   ;; proofgeneral
   `(proof-active-area-face                           ((t (:underline t))))
   `(proof-boring-face                                ((t (:foreground "#000000" :background "#AAAAAA"))))
   `(proof-command-mouse-highlight-face               ((t (:inherit proof-mouse-highlight-face))))
   `(proof-debug-message-face                         ((t (:inherit proof-boring-face))))
   `(proof-declaration-name-face                      ((t (:inherit font-lock-keyword-face :foreground nil))))
   `(proof-eager-annotation-face                      ((t (:foreground "#DDDDDD" :background "#000000"))))
   `(proof-error-face                                 ((t (:foreground "#000000" :background "#AAAAAA"))))
   `(proof-highlight-dependency-face                  ((t (:foreground "#DDDDDD" :background "#000000"))))
   `(proof-highlight-dependent-face                   ((t (:foreground "#DDDDDD" :background "#000000"))))
   `(proof-locked-face                                ((t (:background "#CCCCCC"))))
   `(proof-mouse-highlight-face                       ((t (:foreground "#DDDDDD" :background "#000000"))))
   `(proof-queue-face                                 ((t (:background "#AAAAAA"))))
   `(proof-region-mouse-highlight-face                ((t (:inherit proof-mouse-highlight-face))))
   `(proof-script-highlight-error-face                ((t (:background "#555555"))))
   `(proof-tacticals-name-face                        ((t (:inherit font-lock-constant-face :foreground nil :background "#EEEEEE"))))
   `(proof-tactics-name-face                          ((t (:inherit font-lock-constant-face :foreground nil :background "#EEEEEE"))))
   `(proof-warning-face                               ((t (:foreground "#DDDDDD" :background "#000000"))))
   ;; rainbow-delimiters
   `(rainbow-delimiters-depth-1-face                  ((t (:background "#FF0000"))))
   `(rainbow-delimiters-depth-2-face                  ((t (:background "#FF7700"))))
   `(rainbow-delimiters-depth-3-face                  ((t (:background "#FFFF00"))))
   `(rainbow-delimiters-depth-4-face                  ((t (:background "#00FF00"))))
   `(rainbow-delimiters-depth-5-face                  ((t (:background "#0000FF"))))
   `(rainbow-delimiters-depth-6-face                  ((t (:background "#8F00FF"))))
   `(rainbow-delimiters-depth-7-face                  ((t (:foreground "#FF0000"))))
   `(rainbow-delimiters-depth-8-face                  ((t (:foreground "#FF7700"))))
   `(rainbow-delimiters-depth-9-face                  ((t (:foreground "#FFFF00"))))
   `(rainbow-delimiters-depth-10-face                 ((t (:foreground "#00FF00"))))
   `(rainbow-delimiters-depth-11-face                 ((t (:foreground "#0000FF"))))
   `(rainbow-delimiters-depth-12-face                 ((t (:foreground "#8F00FF"))))
   ;; rcirc
   `(rcirc-my-nick                                    ((t (:foreground "#000000"))))
   `(rcirc-other-nick                                 ((t (:foreground "#000000"))))
   `(rcirc-bright-nick                                ((t (:foreground "#000000"))))
   `(rcirc-dim-nick                                   ((t (:foreground "#555555"))))
   `(rcirc-server                                     ((t (:foreground "#555555"))))
   `(rcirc-server-prefix                              ((t (:foreground "#222222"))))
   `(rcirc-timestamp                                  ((t (:foreground "#000000"))))
   `(rcirc-nick-in-message                            ((t (:foreground "#000000"))))
   `(rcirc-nick-in-message-full-line                  ((t (:bold t))))
   `(rcirc-prompt                                     ((t (:foreground "#000000" :bold t))))
   `(rcirc-track-nick                                 ((t (:inverse-video t))))
   `(rcirc-track-keyword                              ((t (:bold t))))
   `(rcirc-url                                        ((t (:bold t))))
   `(rcirc-keyword                                    ((t (:foreground "#000000" :bold t))))
   ;; rpm-mode
   `(rpm-spec-dir-face                                ((t (:foreground "#555555"))))
   `(rpm-spec-doc-face                                ((t (:foreground "#555555"))))
   `(rpm-spec-ghost-face                              ((t (:foreground "#222222"))))
   `(rpm-spec-macro-face                              ((t (:foreground "#000000"))))
   `(rpm-spec-obsolete-tag-face                       ((t (:foreground "#222222"))))
   `(rpm-spec-package-face                            ((t (:foreground "#222222"))))
   `(rpm-spec-section-face                            ((t (:foreground "#000000"))))
   `(rpm-spec-tag-face                                ((t (:foreground "#000000"))))
   `(rpm-spec-var-face                                ((t (:foreground "#222222"))))
   ;; rst-mode
   `(rst-level-1-face                                 ((t (:foreground "#000000"))))
   `(rst-level-2-face                                 ((t (:foreground "#222222"))))
   `(rst-level-3-face                                 ((t (:foreground "#222222"))))
   `(rst-level-4-face                                 ((t (:foreground "#000000"))))
   `(rst-level-5-face                                 ((t (:foreground "#000000"))))
   `(rst-level-6-face                                 ((t (:foreground "#888888"))))
   ;; sh-mode
   `(sh-heredoc                                       ((t (:foreground "#000000" :bold t))))
   `(sh-quoted-exec                                   ((t (:foreground "#222222"))))
   ;; show-paren
   `(show-paren-mismatch                         ((t (:foreground "#EEEEEE" :background "#AAAAAA" :weight bold))))
   `(show-paren-match                            ((t (:foreground "#000000" :background "#EEEEEE" :weight bold))))
   ;; smartparens
   `(sp-show-pair-mismatch-face                       ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(sp-show-pair-match-face                          ((t (:foreground "#000000" :background "#CCCCCC" :underline nil))))
   ;; sml-mode-line
   `(sml-modeline-end-face                            ((t :inherit default :width condensed)))
   ;; SLIME
   `(slime-repl-output-face                           ((t (:foreground "#222222"))))
   `(slime-repl-inputed-output-face                   ((t (:foreground "#555555"))))
   `(slime-error-face                                 ((((supports :underline (:style wave))) (:underline (:style wave :color "#222222"))) (t (:underline "#222222"))))
   `(slime-warning-face                               ((((supports :underline (:style wave))) (:underline (:style wave :color "#000000"))) (t (:underline "#000000"))))
   `(slime-style-warning-face                         ((((supports :underline (:style wave))) (:underline (:style wave :color "#000000"))) (t (:underline "#000000"))))
   `(slime-note-face                                  ((((supports :underline (:style wave))) (:underline (:style wave :color "#555555"))) (t (:underline "#555555"))))
   `(slime-highlight-face                             ((t (:inherit highlight))))
   ;; speedbar
   `(speedbar-button-face                             ((t (:foreground "#000000"))))
   `(speedbar-directory-face                          ((t (:foreground "#000000"))))
   `(speedbar-file-face                               ((t (:foreground "#000000"))))
   `(speedbar-highlight-face                          ((t (:foreground "#DDDDDD" :background "#000000"))))
   `(speedbar-selected-face                           ((t (:foreground "#222222"))))
   `(speedbar-separator-face                          ((t (:foreground "#DDDDDD" :background "#222222"))))
   `(speedbar-tag-face                                ((t (:foreground "#000000"))))
   ;; tabbar
   `(tabbar-button                                    ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(tabbar-selected                                  ((t (:foreground "#000000" :background "#EEEEEE" :box (:line-width -1 :style pressed-button)))))
   `(tabbar-unselected                                ((t (:foreground "#000000" :background "#CCCCCC" :box (:line-width -1 :style released-button)))))
   ;; term
   `(term-color-black                                 ((t (:foreground "#DDDDDD" :background "#EEEEEE"))))
   `(term-color-red                                   ((t (:foreground "#555555" :background "#AAAAAA"))))
   `(term-color-green                                 ((t (:foreground "#555555" :background "#000000"))))
   `(term-color-yellow                                ((t (:foreground "#000000" :background "#000000"))))
   `(term-color-blue                                  ((t (:foreground "#222222" :background "#AAAAAA"))))
   `(term-color-magenta                               ((t (:foreground "#222222" :background "#222222"))))
   `(term-color-cyan                                  ((t (:foreground "#000000" :background "#000000"))))
   `(term-color-white                                 ((t (:foreground "#000000" :background "#AAAAAA"))))
   '(term-default-fg-color                            ((t (:inherit term-color-white))))
   '(term-default-bg-color                            ((t (:inherit term-color-black))))
   ;; undo-tree
   `(undo-tree-visualizer-active-branch-face          ((t (:foreground "#000000" :weight bold))))
   `(undo-tree-visualizer-current-face                ((t (:foreground "#555555" :weight bold))))
   `(undo-tree-visualizer-default-face                ((t (:foreground "#000000"))))
   `(undo-tree-visualizer-register-face               ((t (:foreground "#000000"))))
   `(undo-tree-visualizer-unmodified-face             ((t (:foreground "#000000"))))
   ;; volatile-highlights
   `(vhl/default-face                                 ((t (:background "#EEEEEE"))))
   ;; emacs-w3m
   `(w3m-anchor                                       ((t (:foreground "#000000" :background "#EEEEEE" :underline t :weight normal))))
   `(w3m-current-anchor                               ((t (:foreground "#000000" :background "#EEEEEE" :underline nil :weight bold))))
   `(w3m-arrived-anchor-face                          ((t (:foreground "#AAAAAA" :background "#DDDDDD" :underline t :weight normal))))
   `(w3m-image-anchor-face                            ((t (:foreground "#222222"  :background "#DDDDDD" :underline t :weight normal))))
   `(w3m-image-face                                   ((t (:foreground "#000000" :background "#DDDDDD" :underline t :weight normal))))
   `(w3m-image-anchor                                 ((t (:foreground "#000000" :background "#DDDDDD" :underline t :weight normal))))
   `(w3m-form                                         ((t (:foreground "#555555" :underline t))))
   `(w3m-header-line-location-title                   ((t (:foreground "#AAAAAA" :background "#DDDDDD" :underline nil :weight normal))))
   `(w3m-header-line-location-content                 ((t (:foreground "#000000" :background "#DDDDDD" :underline nil :weight normal))))
   `(w3m-history-current-url                          ((t (:inherit match))))
   `(w3m-tab-background                               ((t (:foreground "#EEEEEE" :background "#555555" :underline nil :weight normal))) )
   `(w3m-tab-unselected-retrieving                    ((t (:foreground "#EEEEEE" :background "#555555" :underline nil :weight normal))) )
   `(w3m-tab-selected-background-face                 ((t (:foreground "#EEEEEE" :background "#000000" :underline nil :weight bold))) )
   `(w3m-tab-selected-retrieving                      ((t (:foreground "#EEEEEE" :background "#000000" :underline nil :weight bold))) )
   `(w3m-lnum                                         ((t (:foreground "#000000" :background "#EEEEEE"))))
   `(w3m-lnum-match                                   ((t (:background "#EEEEEE" :foreground "#000000" :weight bold))))
   `(w3m-lnum-minibuffer-prompt                       ((t (:foreground "#000000"))))
   ;; web-mode
   `(web-mode-builtin-face                            ((t (:inherit ,font-lock-builtin-face))))
   `(web-mode-comment-face                            ((t (:inherit ,font-lock-comment-face))))
   `(web-mode-constant-face                           ((t (:inherit ,font-lock-constant-face))))
   `(web-mode-css-at-rule-face                        ((t (:foreground "#000000" ))))
   `(web-mode-css-prop-face                           ((t (:foreground "#000000"))))
   `(web-mode-css-pseudo-class-face                   ((t (:foreground "#000000" :weight bold))))
   `(web-mode-css-rule-face                           ((t (:foreground "#000000"))))
   `(web-mode-doctype-face                            ((t (:inherit ,font-lock-comment-face))))
   `(web-mode-folded-face                             ((t (:underline t))))
   `(web-mode-function-name-face                      ((t (:foreground "#000000"))))
   `(web-mode-html-attr-name-face                     ((t (:foreground "#000000"))))
   `(web-mode-html-attr-value-face                    ((t (:inherit ,font-lock-string-face))))
   `(web-mode-html-tag-face                           ((t (:foreground "#000000"))))
   `(web-mode-keyword-face                            ((t (:inherit ,font-lock-keyword-face))))
   `(web-mode-preprocessor-face                       ((t (:inherit ,font-lock-preprocessor-face))))
   `(web-mode-string-face                             ((t (:inherit ,font-lock-string-face))))
   `(web-mode-type-face                               ((t (:inherit ,font-lock-type-face))))
   `(web-mode-variable-name-face                      ((t (:inherit ,font-lock-variable-name-face))))
   `(web-mode-server-background-face                  ((t (:background "#EEEEEE"))))
   `(web-mode-server-comment-face                     ((t (:inherit web-mode-comment-face))))
   `(web-mode-server-string-face                      ((t (:inherit web-mode-string-face))))
   `(web-mode-symbol-face                             ((t (:inherit font-lock-constant-face))))
   `(web-mode-warning-face                            ((t (:inherit font-lock-warning-face))))
   `(web-mode-whitespaces-face                        ((t (:background "#222222"))))
   ;; whitespace-mode
   `(whitespace-space                                 ((t (:background "#CCCCCC" :foreground "#CCCCCC"))))
   `(whitespace-hspace                                ((t (:background "#CCCCCC" :foreground "#CCCCCC"))))
   `(whitespace-tab                                   ((t (:background "#555555"))))
   `(whitespace-newline                               ((t (:foreground "#CCCCCC"))))
   `(whitespace-trailing                              ((t (:background "#222222"))))
   `(whitespace-line                                  ((t (:background "#EEEEEE" :foreground "#222222"))))
   `(whitespace-space-before-tab                      ((t (:background "#000000" :foreground "#000000"))))
   `(whitespace-indentation                           ((t (:background "#000000" :foreground "#222222"))))
   `(whitespace-empty                                 ((t (:background "#000000"))))
   `(whitespace-space-after-tab                       ((t (:background "#000000" :foreground "#222222"))))
   ;; wanderlust
   `(wl-highlight-folder-few-face                     ((t (:foreground "#555555"))))
   `(wl-highlight-folder-many-face                    ((t (:foreground "#555555"))))
   `(wl-highlight-folder-path-face                    ((t (:foreground "#000000"))))
   `(wl-highlight-folder-unread-face                  ((t (:foreground "#000000"))))
   `(wl-highlight-folder-zero-face                    ((t (:foreground "#000000"))))
   `(wl-highlight-folder-unknown-face                 ((t (:foreground "#000000"))))
   `(wl-highlight-message-citation-header             ((t (:foreground "#555555"))))
   `(wl-highlight-message-cited-text-1                ((t (:foreground "#222222"))))
   `(wl-highlight-message-cited-text-2                ((t (:foreground "#000000"))))
   `(wl-highlight-message-cited-text-3                ((t (:foreground "#000000"))))
   `(wl-highlight-message-cited-text-4                ((t (:foreground "#000000"))))
   `(wl-highlight-message-header-contents-face        ((t (:foreground "#555555"))))
   `(wl-highlight-message-headers-face                ((t (:foreground "#000000"))))
   `(wl-highlight-message-important-header-contents   ((t (:foreground "#000000"))))
   `(wl-highlight-message-header-contents             ((t (:foreground "#222222"))))
   `(wl-highlight-message-important-header-contents2  ((t (:foreground "#000000"))))
   `(wl-highlight-message-signature                   ((t (:foreground "#555555"))))
   `(wl-highlight-message-unimportant-header-contents ((t (:foreground "#000000"))))
   `(wl-highlight-summary-answered-face               ((t (:foreground "#000000"))))
   `(wl-highlight-summary-disposed-face               ((t (:foreground "#000000" :slant italic))))
   `(wl-highlight-summary-new-face                    ((t (:foreground "#000000"))))
   `(wl-highlight-summary-normal-face                 ((t (:foreground "#000000"))))
   `(wl-highlight-summary-thread-top-face             ((t (:foreground "#000000"))))
   `(wl-highlight-thread-indent-face                  ((t (:foreground "#222222"))))
   `(wl-highlight-summary-refiled-face                ((t (:foreground "#000000"))))
   `(wl-highlight-summary-displaying-face             ((t (:underline t :weight bold))))
   ;; which-func-mode
   `(which-func                                       ((t (:foreground "#000000"))))
   ;; yascroll
   `(yascroll:thumb-text-area                         ((t (:background "#EEEEEE"))))
   `(yascroll:thumb-fringe                            ((t (:background "#EEEEEE" :foreground "#EEEEEE"))))
   `(minimap-active-region-background                 ((t (:background "#CCCCCC" :foreground "#AAAAAA"))))
   ;; html fold/unfold face
   `(html-fold-unfolded-face                          ((t (:background "#EEEEEE"))))
   `(html-fold-folded-face                            ((t (:foreground "#000000" :bold t))))
   ;; markdown mode
   `(markdown-header-delimiter-face                   ((t (:weight normal :foreground "#CCCCCC"))))
   `(markdown-header-face-1                           ((,class ,ol1)))
   `(markdown-header-face-2                           ((,class ,ol2)))
   `(markdown-header-face-3                           ((,class ,ol3)))
   `(markdown-header-face-4                           ((,class ,ol4)))
   `(markdown-header-face-5                           ((,class ,ol5)))
   `(markdown-header-face-6                           ((,class ,ol6)))
   `(markdown-link-face                               ((t (:underline t :foreground "#000000"))))
   `(markdown-url-face                                ((t (:underline t :foreground "#000000"))))
   `(markdown-pre-face                                ((t (:foreground "#000000" ,@(when eziam-scale-non-headline-faces (list :height .8))))))
   `(markdown-bold-face                               ((t (:foreground "#888888" :bold t ))))
   `(markdown-italic-face                             ((t (:foreground "#888888" :italic t ))))
   `(markdown-list-face                               ((t (:foreground "#000000"))))
   `(markdown-markup-face                             ((t (:foreground "#CCCCCC" ))))
   ;; swoop
   `(swoop-face-line-buffer-name                      ((t (:background "#555555" :foreground "#EEEEEE"))))
   `(swoop-face-target-line                           ((t (:background "#AAAAAA" :foreground "#000000"))))
   `(swoop-face-line-number                           ((t (:background "#EEEEEE" :foreground "#CCCCCC"))))
   `(swoop-face-header-format-line                    ((t (:background "#CCCCCC" :foreground "#EEEEEE"))))
   `(swoop-face-target-words                          ((t (:background "#CCCCCC" :foreground "#000000"))))
   `(highlight-indentation-face                       ((t (:background "#DDDDDD"))))
   `(highlight-indentation-current-column-face        ((t (:background "#EEEEEE"))))
   ;; company
   `(company-echo-common                              ((t (:foreground "#000000"))))
   `(company-preview                                  ((t (:background "#CCCCCC" :foreground "#000000"))))
   `(company-preview-common                           ((t (:inherit company-preview :foreground "#000000" :weight bold))))
   `(company-scrollbar-fg                             ((t (:background "#AAAAAA"))))
   `(company-tooltip                                  ((t (:background "#CCCCCC" :foreground "#000000"))))
   `(company-tooltip-annotation                       ((t (:inherit company-tooltip :foreground "#EEEEEE"))))
   `(company-tooltip-common                           ((t (:inherit company-tooltip :foreground "#000000"))))
   `(company-tooltip-common-selection                 ((t (:inherit company-tooltip-selection :foreground "#000000"))))
   `(company-tooltip-selection                        ((t (:inherit company-tooltip :background "#888888" :foreground "#EEEEEE"))))
   `(company-scrollbar-bg                             ((t (:inherit company-tooltip))))
   ;; eval-sexp-fu
   `(eval-sexp-fu-flash                               ((t (:background "#DDDDDD"))))
   `(eval-sexp-fu-flash-error                         ((t (:background "#000000" :foreground "#EEEEEE"))))
   ;; neotree
   `(neo-dir-link-face                                ((t (:inherit diredp-dir-priv))))
   `(neo-expand-btn-face                              ((t (:foreground "#000000" :bold t))))
   `(neo-file-link-face                               ((t (:foreground "#555555"))))
   `(neo-root-dir-face                                ((t (:foreground "#888888" :background "#EEEEEE"))))
   ;; geiser
   `(geiser-font-lock-doc-link                        ((t (:foreground "#000000" :underline t))))
   `(geiser-font-lock-error-link                      ((t (:foreground "#000000" :underline t))))
   `(geiser-font-lock-autodoc-identifier              ((t (:foreground "#888888" :bold t))))
   `(compilation-error                                ((t (:foreground "#000000" :underline t :bold t))))
   ;; elixir
   `(elixir-atom-face                                 ((t (:foreground "#000000" :bold t))))
   ;; tuareg
   `(tuareg-font-lock-operator-face                   ((t (:inherit ,font-lock-variable-name-face))))
   `(tuareg-font-lock-governing-face                  ((t (:inherit ,font-lock-keyword-face))))
   ;; avy
   `(avy-lead-face                                    ((t (:background "#888888" :foreground "#EEEEEE" :bold t))))
   `(avy-lead-face-0                                  ((t (:background "#555555"  :foreground "#EEEEEE"  :bold t))))
   `(avy-lead-face-1                                  ((t (:background "#222222"  :foreground "#EEEEEE" :bold t))))
   `(avy-lead-face-2                                  ((t (:background "#000000"  :foreground "#EEEEEE" :bold t))))
   `(avy-background-face                              ((t (:background "#EEEEEE" :foreground "#AAAAAA" :bold t))))
   ;; highlight-indent-guides has been removed: newer versions automatically compute faces.
   )
  )

(custom-theme-set-variables
 'eziam-light
 ;; ansi-color
 `(ansi-color-names-vector ["#DDDDDD"
                            "#222222"
                            "#555555"
                            "#000000"
                            "#000000"
                            "#222222"
                            "#000000"
                            "#000000"])
 ;; fill-column-indicator
 `(fci-rule-color "#EEEEEE"
                  ;; vc-annotate
                  `(vc-annotate-color-map
                    '(( 20. . "#AAAAAA")
                      ( 40. . "#888888")
                      ( 60. . "#888888")
                      ( 80. . "#555555")
                      (100. . "#555555")
                      (120. . "#222222")
                      (140. . "#222222")
                      (160. . "#000000")
                      (180. . "#000000")
                      (200. . "#000000")
                      (220. . "#000000")
                      (240. . "#000000")
                      (260. . "#000000")
                      (280. . "#000000")
                      (300. . "#000000")
                      (320. . "#000000")
                      (340. . "#000000")
                      (360. . "#000000")))
                  `(vc-annotate-very-old-color "#222222")
                  `(vc-annotate-background "#EEEEEE"))
 )

;;; Footer
(provide-theme 'eziam-light)

;;;###autoload

                  ;; Local Variables:
                  ;; mode: emacs-lisp;
                  ;; no-byte-compile: t
                  ;; indent-tabs-mode: nil
                  ;; End:
;;; eziam-light-theme.el ends here
