;;; eziam-VARIANT-theme.el --- The VARIANT Eziam theme for Emacs

;; Copyright (C) 2016 Thibault Polge <thibault@thb.lt>
;; Heavily based on Tao Theme (C) 2014 Peter  <11111000000 at email.com>,
;; with contributions from Jasonm23 <jasonm23@gmail.com>
;; Original faces taken from Zenburn theme port (c) by Bozhidar Batsov
;;
;; Package-Requires:            ((cl-lib "0.5"))
;;
;; URL: http://github.com/thblt/eziam-theme-emacs
;; Version: 0.0

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:
;;; Code:


#ifdef DARK_MODE
#define LIGHT_DARK(a,b) b
#else
#define LIGHT_DARK(a,b) a
#endif

#define OL_HEIGHT(h) ,@(when eziam-scale-outline-headlines (list :height h))

(require 'eziam-common)

(deftheme eziam-VARIANT "The VARIANT Eziam color theme")

(let ((class '((class color) (min-colors 89)))

      ;; Eziam generic colors.
      (ol1 `(OL_HEIGHT(1.9) :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0"))
      (ol2 '(:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB"))
      (ol3 '(:height 1.0 :weight bold :foreground "#005522" :background "#EFFFEF"))
      (ol4 '(:height 1.0 :weight bold :slant normal :foreground "#EA6300"))
      (ol5 '(:height 1.0 :weight bold :slant normal :foreground "#E3258D"))
      (ol6 '(:height 1.0 :weight bold :slant italic :foreground "#0077CC"))
      (ol7 '(:height 1.0 :weight bold :slant italic :foreground "#2EAE2C"))
      (ol8 '(:height 1.0 :weight bold :slant italic :foreground "#FD8008"))
      )
  
  (custom-theme-set-faces
   'eziam-VARIANT
   ;; Built-in
   `(button                                           ((t (:underline t))))
   `(link                                             ((t (:foreground COLOR_13 :underline t :weight bold))))
   `(link-visited                                     ((t (:foreground COLOR_11 :underline t :weight normal))))
   `(default                                          ((t (:foreground COLOR_9 :background COLOR_4))))
   `(hl-paren-face                                    ((t (:foreground COLOR_12 :background COLOR_3 :weight bold))))
   `(cursor                                           ((t (:foreground COLOR_13 :background COLOR_14))))
   `(escape-glyph                                     ((t (:foreground COLOR_13 :bold t))))
   `(fringe                                           ((t (:foreground COLOR_2 :background COLOR_4))))
   `(header-line                                      ((t (:inherit mode-line))))
   `(highlight                                        ((t (:background COLOR_4))))
   `(success                                          ((t (:foreground COLOR_9 :weight bold))))
   `(warning                                          ((t (:foreground COLOR_11 :weight bold))))
   ;; compilation
   `(compilation-column-face                          ((t (:foreground COLOR_13))))
   `(compilation-enter-directory-face                 ((t (:foreground COLOR_9))))
   `(compilation-error-face                           ((t (:foreground COLOR_9 :weight bold :underline t))))
   `(compilation-face                                 ((t (:foreground COLOR_13))))
   `(compilation-info-face                            ((t (:foreground COLOR_11))))
   `(compilation-info                                 ((t (:foreground COLOR_13 :underline t))))
   `(compilation-leave-directory-face                 ((t (:foreground COLOR_9))))
   `(compilation-line-face                            ((t (:foreground COLOR_13))))
   `(compilation-line-number                          ((t (:foreground COLOR_13))))
   `(compilation-message-face                         ((t (:foreground COLOR_11))))
   `(compilation-warning-face                         ((t (:foreground COLOR_11 :weight bold :underline t))))
   `(compilation-mode-line-exit                       ((t (:foreground COLOR_11 :weight bold))))
   `(compilation-mode-line-fail                       ((t (:foreground COLOR_10 :weight bold))))
   `(compilation-mode-line-run                        ((t (:foreground COLOR_13 :weight bold))))
   ;; grep
   `(grep-context-face                                ((t (:foreground COLOR_13))))
   `(grep-error-face                                  ((t (:foreground COLOR_9 :weight bold :underline t))))
   `(grep-hit-face                                    ((t (:foreground COLOR_11))))
   `(grep-match-face                                  ((t (:foreground COLOR_11 :weight bold))))
   `(match                                            ((t (:background COLOR_3 :foreground COLOR_11 :weight bold))))
   ;; make
   `(makefile-space                                   ((t (:background COLOR_4))))
   `(makefile-targets                                 ((t (:underline t))))
   `(makefile-shell                                   ((t (:slant italic))))
   ;; isearch
   `(isearch                                          ((t (:background ,STRONG_HIGHLIGHT :foreground LIGHT_DARK(COLOR_10,COLOR_2) :weight normal))))
   `(isearch-fail                                     ((t (:foreground COLOR_13 :background COLOR_7))))
   `(lazy-highlight                                   ((t (:foreground COLOR_11 :weight bold :background COLOR_5))))
   `(menu                                             ((t (:foreground COLOR_13 :background COLOR_4))))
   `(minibuffer-prompt                                ((t (:foreground COLOR_13 :color COLOR_1))))
   `(mode-line                                        ((,class (:foreground COLOR_2 :background COLOR_8 :box nil )) (t :inverse-video t)))
   `(mode-line-inactive                               ((t (:foreground COLOR_3 :background COLOR_6 :box nil))))
   `(mode-line-buffer-id                              ((t (:foreground COLOR_4 :weight bold))))
   `(region                                           ((,class (:background COLOR_9 :foreground COLOR_3)) (t :inverse-video t)))
   `(secondary-selection                              ((t (:background COLOR_4))))
   `(cua-rectangle                                    ((t (:background COLOR_4))))
   `(trailing-whitespace                              ((t (:background COLOR_10))))
   `(vertical-border                                  ((t (:foreground COLOR_7 :background COLOR_4))))
   ;; font lock
   `(font-lock-builtin-face                           ((t (:foreground COLOR_13 :weight bold))))
   `(font-lock-comment-face                           ((t (:foreground COLOR_7 :weight bold))))
   `(font-lock-comment-delimiter-face                 ((t (:foreground COLOR_8))))
   `(font-lock-constant-face                          ((t (:foreground COLOR_8 :weight bold))))
   `(font-lock-doc-face                               ((t (:foreground COLOR_7))))
   `(font-lock-function-name-face                     ((t (:background FUNCTION_NAME :box (:color FUNCTION_NAME_BOX)))))
   `(font-lock-keyword-face                           ((t (:foreground COLOR_13 :weight bold))))
   `(font-lock-negation-char-face                     ((t (:foreground COLOR_13 :weight bold))))
   `(font-lock-preprocessor-face                      ((t (:foreground COLOR_11))))
   `(font-lock-regexp-grouping-construct              ((t (:foreground COLOR_13 :weight bold))))
   `(font-lock-regexp-grouping-backslash              ((t (:foreground COLOR_9 :weight bold))))
   `(font-lock-string-face                            ((t (:foreground COLOR_8 :slant oblique))))
   `(font-lock-type-face                              ((t (:foreground COLOR_10 :underline t))))
   `(font-lock-variable-name-face                     ((t (:foreground COLOR_14 ))))
   `(font-lock-warning-face                           ((t (:foreground COLOR_11 :weight bold))))
   `(c-annotation-face                                ((t (:inherit font-lock-constant-face))))
   ;; newsticker
   `(newsticker-date-face                             ((t (:foreground COLOR_13))))
   `(newsticker-default-face                          ((t (:foreground COLOR_13))))
   `(newsticker-enclosure-face                        ((t (:foreground COLOR_12))))
   `(newsticker-extra-face                            ((t (:foreground COLOR_7 :height ,(eziam-theme-height 0.8)))))
   `(newsticker-feed-face                             ((t (:foreground COLOR_13))))
   `(newsticker-immortal-item-face                    ((t (:foreground COLOR_9))))
   `(newsticker-new-item-face                         ((t (:foreground COLOR_11))))
   `(newstickerphone-obsolete-item-face                    ((t (:foreground COLOR_10))))
   `(newsticker-old-item-face                         ((t (:foreground COLOR_8))))
   `(newsticker-statistics-face                       ((t (:foreground COLOR_13))))
   `(newsticker-treeview-face                         ((t (:foreground COLOR_13))))
   `(newsticker-treeview-immortal-face                ((t (:foreground COLOR_9))))
   `(newsticker-treeview-listwindow-face              ((t (:foreground COLOR_13))))
   `(newsticker-treeview-new-face                     ((t (:foreground COLOR_11 :weight bold))))
   `(newsticker-treeview-obsolete-face                ((t (:foreground COLOR_10))))
   `(newsticker-treeview-old-face                     ((t (:foreground COLOR_8))))
   `(newsticker-treeview-selection-face               ((t (:background COLOR_3 :foreground COLOR_13))))
   ;; Third-party
   ;; highlight-symbol
   `(highlight-symbol-face                            ((t (:background COLOR_4) )))
   ;; ace-jump
   `(ace-jump-face-background                         ((t (:foreground COLOR_6 :background COLOR_2 :inverse-video nil))))
   `(ace-jump-face-foreground                         ((t (:foreground COLOR_11 :background COLOR_1 :inverse-video nil))))
   ;; anzu
   `(anzu-mode-line                                   ((t (:foreground COLOR_12 :weight bold))))
   ;; full-ack
   `(ack-separator                                    ((t (:foreground COLOR_13))))
   `(ack-file                                         ((t (:foreground COLOR_11))))
   `(ack-line                                         ((t (:foreground COLOR_13))))
   `(ack-match                                        ((t (:foreground COLOR_11 :background COLOR_3 :weight bold))))
   ;; auctex
   `(font-latex-bold-face                             ((t (:inherit bold))))
   `(font-latex-warning-face                          ((t (:foreground nil :inherit font-lock-warning-face))))
   `(font-latex-sectioning-5-face                     ((t (:foreground COLOR_10 :weight bold ))))
   `(font-latex-sedate-face                           ((t (:foreground COLOR_13))))
   `(font-latex-italic-face                           ((t (:foreground COLOR_12 :slant italic))))
   `(font-latex-string-face                           ((t (:inherit ,font-lock-string-face))))
   `(font-latex-math-face                             ((t (:foreground COLOR_11))))
   ;; auto-complete
   `(ac-candidate-face                                ((t (:background COLOR_8 :foreground COLOR_2 :underline nil))))
   `(ac-selection-face                                ((t (:background COLOR_7 :foreground COLOR_13 :underline nil))))
   `(ac-yasnippet-candidate-face                      ((t (:background COLOR_8 :foreground COLOR_3))))
   `(ac-yasnippet-selection-face                      ((t (:background COLOR_7 :foreground COLOR_12))))
   `(ac-slime-menu-face                               ((t (:background COLOR_8 :foreground COLOR_1))))
   `(ac-slime-selection-face                          ((t (:background COLOR_7 :foreground COLOR_12))))
   `(ac-gtags-candidate-face                          ((t (:background COLOR_8 :foreground COLOR_1))))
   `(ac-gtags-selection-face                          ((t (:background COLOR_7 :foreground COLOR_12))))
   `(ac-emmet-candidate-face                          ((t (:background COLOR_8 :foreground COLOR_2))))
   `(ac-emmet-selection-face                          ((t (:background COLOR_7 :foreground COLOR_12))))

   `(popup-tip-face                                   ((t (:background COLOR_11 :foreground COLOR_2))))
   `(popup-scroll-bar-foreground-face                 ((t (:background COLOR_6))))
   `(popup-scroll-bar-background-face                 ((t (:background COLOR_3))))
   `(popup-isearch-match                              ((t (:background COLOR_4 :foreground COLOR_13))))
   ;; android mode
   `(android-mode-debug-face                          ((t (:foreground COLOR_10))))
   `(android-mode-error-face                          ((t (:foreground COLOR_11 :weight bold))))
   `(android-mode-info-face                           ((t (:foreground COLOR_13))))
   `(android-mode-verbose-face                        ((t (:foreground COLOR_9))))
   `(android-mode-warning-face                        ((t (:foreground COLOR_13))))
   ;; bm
   `(bm-face                                          ((t (:background COLOR_12 :foreground COLOR_5))))
   `(bm-fringe-face                                   ((t (:background COLOR_4 :foreground COLOR_2))))
   `(bm-fringe-persistent-face                        ((t (:background COLOR_4 :foreground COLOR_2))))
   `(bm-persistent-face                               ((t (:background COLOR_8 :foreground COLOR_5))))
   ;; clojure-test-mode
   `(clojure-test-failure-face                        ((t (:foreground COLOR_11 :weight bold :underline t))))
   `(clojure-test-error-face                          ((t (:foreground COLOR_10 :weight bold :underline t))))
   `(clojure-test-success-face                        ((t (:foreground COLOR_10 :weight bold :underline t))))
   ;; coq
   `(coq-solve-tactics-face                           ((t (:foreground nil :inherit font-lock-constant-face))))
   ;; ctable
   `(ctbl:face-cell-select                            ((t (:background COLOR_11 :foreground COLOR_5))))
   `(ctbl:face-continue-bar                           ((t (:background COLOR_4 :foreground COLOR_5))))
   `(ctbl:face-row-select                             ((t (:background COLOR_12 :foreground COLOR_5))))
   ;; diff
   `(diff-added                                       ((,class (:foreground COLOR_13 :background nil)) (t (:foreground COLOR_8 :background nil))))
   `(diff-changed                                     ((t (:foreground COLOR_13))))
   `(diff-removed                                     ((,class (:foreground COLOR_10 :background nil)) (t (:foreground COLOR_8 :background nil))))
   `(diff-refine-added                                ((t :inherit diff-added :weight bold)))
   `(diff-refine-change                               ((t :inherit diff-changed :weight bold)))
   `(diff-refine-removed                              ((t :inherit diff-removed :weight bold)))
   `(diff-header                                      ((,class (:background COLOR_7)) (t (:background COLOR_13 :foreground COLOR_5))))
   `(diff-file-header                                 ((,class (:background COLOR_7 :foreground COLOR_13 :bold t)) (t (:background COLOR_13 :foreground COLOR_5 :bold t))))
   ;; dired
   `(dired-directory                                  ((t (:foreground COLOR_14 :bold t))))
   ;; dired+
   `(diredp-display-msg                               ((t (:foreground COLOR_11))))
   `(diredp-compressed-file-suffix                    ((t (:foreground COLOR_11))))
   `(diredp-date-time                                 ((t (:foreground COLOR_10))))
   `(diredp-deletion                                  ((t (:foreground COLOR_13))))
   `(diredp-deletion-file-name                        ((t (:foreground COLOR_10))))
   `(diredp-dir-heading                               ((t (:foreground COLOR_13 :background COLOR_3 :bold t))))
   `(diredp-dir-priv                                  ((t (:foreground COLOR_14 :bold t))))
   `(diredp-dir-name                                  ((t (:foreground COLOR_14 :bold t))))
   `(diredp-exec-priv                                 ((t (:foreground COLOR_10))))
   `(diredp-executable-tag                            ((t (:foreground COLOR_10))))
   `(diredp-file-name                                 ((t (:foreground COLOR_11))))
   `(diredp-file-suffix                               ((t (:foreground COLOR_11 :bold t))))
   `(diredp-flag-mark                                 ((t (:foreground COLOR_13))))
   `(diredp-flag-mark-line                            ((t (:foreground COLOR_11))))
   `(diredp-ignored-file-name                         ((t (:foreground COLOR_6))))
   `(diredp-link-priv                                 ((t (:foreground COLOR_13))))
   `(diredp-mode-line-flagged                         ((t (:foreground COLOR_13))))
   `(diredp-mode-line-marked                          ((t (:foreground COLOR_11))))
   `(diredp-no-priv                                   ((t (:foreground COLOR_13))))
   `(diredp-number                                    ((t (:foreground COLOR_10))))
   `(diredp-other-priv                                ((t (:foreground COLOR_12))))
   `(diredp-rare-priv                                 ((t (:foreground COLOR_9))))
   `(diredp-read-priv                                 ((t (:foreground COLOR_8))))
   `(diredp-symlink                                   ((t (:foreground COLOR_13))))
   `(diredp-write-priv                                ((t (:foreground COLOR_10))))
   ;; ediff
   `(ediff-current-diff-A                             ((t (:foreground COLOR_13 :background COLOR_7))))
   `(ediff-current-diff-Ancestor                      ((t (:foreground COLOR_13 :background COLOR_7))))
   `(ediff-current-diff-B                             ((t (:foreground COLOR_13 :background COLOR_8))))
   `(ediff-current-diff-C                             ((t (:foreground COLOR_13 :background COLOR_6))))
   `(ediff-even-diff-A                                ((t (:background COLOR_6))))
   `(ediff-even-diff-Ancestor                         ((t (:background COLOR_6))))
   `(ediff-even-diff-B                                ((t (:background COLOR_6))))
   `(ediff-even-diff-C                                ((t (:background COLOR_6))))
   `(ediff-fine-diff-A                                ((t (:foreground COLOR_13 :background COLOR_9 :weight bold))))
   `(ediff-fine-diff-Ancestor                         ((t (:foreground COLOR_13 :background COLOR_9 :weight bold))))
   `(ediff-fine-diff-B                                ((t (:foreground COLOR_13 :background COLOR_9 :weight bold))))
   `(ediff-fine-diff-C                                ((t (:foreground COLOR_13 :background COLOR_8 :weight bold ))))
   `(ediff-odd-diff-A                                 ((t (:background COLOR_7))))
   `(ediff-odd-diff-Ancestor                          ((t (:background COLOR_7))))
   `(ediff-odd-diff-B                                 ((t (:background COLOR_7))))
   `(ediff-odd-diff-C                                 ((t (:background COLOR_7))))
   ;; ert
   `(ert-test-result-expected                         ((t (:foreground COLOR_13 :background COLOR_4))))
   `(ert-test-result-unexpected                       ((t (:foreground COLOR_10 :background COLOR_4))))
   ;; eshell
   `(eshell-prompt                                    ((t (:foreground COLOR_13 :weight bold))))
   `(eshell-ls-archive                                ((t (:foreground COLOR_9 :weight bold))))
   `(eshell-ls-backup                                 ((t (:inherit font-lock-comment-face))))
   `(eshell-ls-clutter                                ((t (:inherit font-lock-comment-face))))
   `(eshell-ls-directory                              ((t (:foreground COLOR_11 :weight bold))))
   `(eshell-ls-executable                             ((t (:foreground COLOR_11 :weight bold))))
   `(eshell-ls-unreadable                             ((t (:foreground COLOR_13))))
   `(eshell-ls-missing                                ((t (:inherit font-lock-warning-face))))
   `(eshell-ls-product                                ((t (:inherit font-lock-doc-face))))
   `(eshell-ls-special                                ((t (:foreground COLOR_13 :weight bold))))
   `(eshell-ls-symlink                                ((t (:foreground COLOR_12 :weight bold))))
   ;; flx
   `(flx-highlight-face                               ((t (:foreground COLOR_11 :weight bold))))
   ;; flycheck
   `(flycheck-error                                   ((((supports :underline (:style wave))) (:underline (:style wave :color COLOR_7) :inherit unspecified)) (t (:foreground COLOR_13 :weight bold :underline t))))
   `(flycheck-warning                                 ((((supports :underline (:style wave))) (:underline (:style wave :color COLOR_6) :inherit unspecified)) (t (:foreground COLOR_11 :weight bold :underline t))))
   `(flycheck-info                                    ((((supports :underline (:style wave))) (:underline (:style wave :color COLOR_5) :inherit unspecified)) (t (:foreground COLOR_10 :weight bold :underline t))))
   `(flycheck-fringe-error                            ((t (:foreground COLOR_1 :weight bold))))
   `(flycheck-fringe-warning                          ((t (:foreground COLOR_4 :weight bold))))
   `(flycheck-fringe-info                             ((t (:foreground COLOR_4 :weight bold))))
   ;; flymake
   `(flymake-errline                                  ((((supports :underline (:style wave))) (:underline (:style wave :color COLOR_10) :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground COLOR_9 :weight bold :underline t))))
   `(flymake-warnline                                 ((((supports :underline (:style wave))) (:underline (:style wave :color COLOR_11) :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground COLOR_11 :weight bold :underline t))))
   `(flymake-infoline                                 ((((supports :underline (:style wave))) (:underline (:style wave :color COLOR_9) :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground COLOR_8 :weight bold :underline t))))
   ;; flyspell
   `(flyspell-duplicate                               ((((supports :underline (:style wave))) (:underline (:style wave :color COLOR_11) :inherit unspecified)) (t (:foreground COLOR_11 :weight bold :underline t))))
   `(flyspell-incorrect                               ((((supports :underline (:style wave))) (:underline (:style wave :color COLOR_10) :inherit unspecified)) (t (:foreground COLOR_9 :weight bold :underline t))))
   ;; erc
   `(erc-action-face                                  ((t (:inherit erc-default-face))))
   `(erc-bold-face                                    ((t (:weight bold))))
   `(erc-current-nick-face                            ((t (:foreground COLOR_11 :weight bold))))
   `(erc-dangerous-host-face                          ((t (:inherit font-lock-warning-face))))
   `(erc-default-face                                 ((t (:foreground COLOR_13))))
   `(erc-direct-msg-face                              ((t (:inherit erc-default))))
   `(erc-error-face                                   ((t (:inherit font-lock-warning-face))))
   `(erc-fool-face                                    ((t (:inherit erc-default))))
   `(erc-highlight-face                               ((t (:inherit hover-highlight))))
   `(erc-input-face                                   ((t (:foreground COLOR_13))))
   `(erc-keyword-face                                 ((t (:foreground COLOR_11 :weight bold))))
   `(erc-nick-default-face                            ((t (:foreground COLOR_13 :weight bold))))
   `(erc-my-nick-face                                 ((t (:foreground COLOR_10 :weight bold))))
   `(erc-nick-msg-face                                ((t (:inherit erc-default))))
   `(erc-notice-face                                  ((t (:foreground COLOR_9))))
   `(erc-pal-face                                     ((t (:foreground COLOR_11 :weight bold))))
   `(erc-prompt-face                                  ((t (:foreground COLOR_11 :background COLOR_4 :weight bold))))
   `(erc-timestamp-face                               ((t (:foreground COLOR_13))))
   `(erc-underline-face                               ((t (:underline t))))
   ;; git-gutter
   `(git-gutter:added                                 ((t (:background COLOR_4 :foreground COLOR_1 :weight bold ))))
   `(git-gutter:deleted                               ((t (:background COLOR_4 :foreground COLOR_1 :weight bold ))))
   `(git-gutter:modified                              ((t (:background COLOR_4 :foreground COLOR_1 :weight bold ))))
   `(git-gutter:unchanged                             ((t (:background COLOR_4 :foreground COLOR_1 :weight bold ))))
   ;; git-gutter-fr
   `(git-gutter-fr:added                              ((t (:foreground COLOR_2 :weight bold))))
   `(git-gutter-fr:deleted                            ((t (:foreground COLOR_2 :weight bold))))
   `(git-gutter-fr:modified                           ((t (:foreground COLOR_2 :weight bold))))
   ;; gnus
   `(gnus-group-mail-1                                ((t (:bold t :inherit gnus-group-mail-1-empty))))
   `(gnus-group-mail-1-empty                          ((t (:inherit gnus-group-news-1-empty))))
   `(gnus-group-mail-2                                ((t (:bold t :inherit gnus-group-mail-2-empty))))
   `(gnus-group-mail-2-empty                          ((t (:inherit gnus-group-news-2-empty))))
   `(gnus-group-mail-3                                ((t (:bold t :inherit gnus-group-mail-3-empty))))
   `(gnus-group-mail-3-empty                          ((t (:inherit gnus-group-news-3-empty))))
   `(gnus-group-mail-4                                ((t (:bold t :inherit gnus-group-mail-4-empty))))
   `(gnus-group-mail-4-empty                          ((t (:inherit gnus-group-news-4-empty))))
   `(gnus-group-mail-5                                ((t (:bold t :inherit gnus-group-mail-5-empty))))
   `(gnus-group-mail-5-empty                          ((t (:inherit gnus-group-news-5-empty))))
   `(gnus-group-mail-6                                ((t (:bold t :inherit gnus-group-mail-6-empty))))
   `(gnus-group-mail-6-empty                          ((t (:inherit gnus-group-news-6-empty))))
   `(gnus-group-mail-low                              ((t (:bold t :inherit gnus-group-mail-low-empty))))
   `(gnus-group-mail-low-empty                        ((t (:inherit gnus-group-news-low-empty))))
   `(gnus-group-news-1                                ((t (:bold t :inherit gnus-group-news-1-empty))))
   `(gnus-group-news-2                                ((t (:bold t :inherit gnus-group-news-2-empty))))
   `(gnus-group-news-3                                ((t (:bold t :inherit gnus-group-news-3-empty))))
   `(gnus-group-news-4                                ((t (:bold t :inherit gnus-group-news-4-empty))))
   `(gnus-group-news-5                                ((t (:bold t :inherit gnus-group-news-5-empty))))
   `(gnus-group-news-6                                ((t (:bold t :inherit gnus-group-news-6-empty))))
   `(gnus-group-news-low                              ((t (:bold t :inherit gnus-group-news-low-empty))))
   `(gnus-header-content                              ((t (:inherit message-header-other))))
   `(gnus-header-from                                 ((t (:inherit message-header-from))))
   `(gnus-header-name                                 ((t (:inherit message-header-name))))
   `(gnus-header-newsgroups                           ((t (:inherit message-header-other))))
   `(gnus-header-subject                              ((t (:inherit message-header-subject))))
   `(gnus-summary-cancelled                           ((t (:foreground COLOR_11))))
   `(gnus-summary-high-ancient                        ((t (:foreground COLOR_11))))
   `(gnus-summary-high-read                           ((t (:foreground COLOR_9 :weight bold))))
   `(gnus-summary-high-ticked                         ((t (:foreground COLOR_11 :weight bold))))
   `(gnus-summary-high-unread                         ((t (:foreground COLOR_13 :weight bold))))
   `(gnus-summary-low-ancient                         ((t (:foreground COLOR_11))))
   `(gnus-summary-low-read                            ((t (:foreground COLOR_9))))
   `(gnus-summary-low-ticked                          ((t (:foreground COLOR_11 :weight bold))))
   `(gnus-summary-low-unread                          ((t (:foreground COLOR_13))))
   `(gnus-summary-normal-ancient                      ((t (:foreground COLOR_11))))
   `(gnus-summary-normal-read                         ((t (:foreground COLOR_9))))
   `(gnus-summary-normal-ticked                       ((t (:foreground COLOR_11 :weight bold))))
   `(gnus-summary-normal-unread                       ((t (:foreground COLOR_13))))
   `(gnus-summary-selected                            ((t (:foreground COLOR_13 :weight bold))))
   `(gnus-cite-1                                      ((t (:foreground COLOR_11))))
   `(gnus-cite-10                                     ((t (:foreground COLOR_12))))
   `(gnus-cite-11                                     ((t (:foreground COLOR_13))))
   `(gnus-cite-2                                      ((t (:foreground COLOR_10))))
   `(gnus-cite-3                                      ((t (:foreground COLOR_9))))
   `(gnus-cite-4                                      ((t (:foreground COLOR_11))))
   `(gnus-cite-5                                      ((t (:foreground COLOR_10))))
   `(gnus-cite-6                                      ((t (:foreground COLOR_9))))
   `(gnus-cite-7                                      ((t (:foreground COLOR_10))))
   `(gnus-cite-8                                      ((t (:foreground COLOR_9))))
   `(gnus-cite-9                                      ((t (:foreground COLOR_9))))
   `(gnus-group-news-1-empty                          ((t (:foreground COLOR_13))))
   `(gnus-group-news-2-empty                          ((t (:foreground COLOR_12))))
   `(gnus-group-news-3-empty                          ((t (:foreground COLOR_10))))
   `(gnus-group-news-4-empty                          ((t (:foreground COLOR_9))))
   `(gnus-group-news-5-empty                          ((t (:foreground COLOR_8))))
   `(gnus-group-news-6-empty                          ((t (:foreground COLOR_7))))
   `(gnus-group-news-low-empty                        ((t (:foreground COLOR_7))))
   `(gnus-signature                                   ((t (:foreground COLOR_13))))
   `(gnus-x                                           ((t (:background COLOR_13 :foreground COLOR_5))))
   ;; guide-key
   `(guide-key/highlight-command-face                 ((t (:foreground COLOR_11))))
   `(guide-key/key-face                               ((t (:foreground COLOR_9))))
   `(guide-key/prefix-command-face                    ((t (:foreground COLOR_10))))
   ;; helm
   `(helm-header                                      ((t (:foreground COLOR_9 :background COLOR_4 :underline nil :box nil))))
   `(helm-source-header                               ((t (:foreground COLOR_13 :background COLOR_3 :underline nil :weight bold :box (:line-width -1 :style released-button)))))
   `(helm-selection                                   ((t (:background COLOR_6 :underline nil))))
   `(helm-selection-line                              ((t (:background COLOR_6))))
   `(helm-visible-mark                                ((t (:foreground COLOR_5 :background COLOR_11))))
   `(helm-candidate-number                            ((t (:foreground COLOR_13 :background COLOR_3))))
   `(helm-separator                                   ((t (:foreground COLOR_10 :background COLOR_4))))
   `(helm-time-zone-current                           ((t (:foreground COLOR_11 :background COLOR_4))))
   `(helm-time-zone-home                              ((t (:foreground COLOR_10 :background COLOR_4))))
   `(helm-bookmark-addressbook                        ((t (:foreground COLOR_11 :background COLOR_4))))
   `(helm-bookmark-directory                          ((t (:foreground nil :background nil :inherit helm-ff-directory))))
   `(helm-bookmark-file                               ((t (:foreground nil :background nil :inherit helm-ff-file))))
   `(helm-bookmark-gnus                               ((t (:foreground COLOR_10 :background COLOR_4))))
   `(helm-bookmark-info                               ((t (:foreground COLOR_11 :background COLOR_4))))
   `(helm-bookmark-man                                ((t (:foreground COLOR_13 :background COLOR_4))))
   `(helm-bookmark-w3m                                ((t (:foreground COLOR_10 :background COLOR_4))))
   `(helm-buffer-not-saved                            ((t (:foreground COLOR_10 :background COLOR_4))))
   `(helm-buffer-process                              ((t (:foreground COLOR_12 :background COLOR_4))))
   `(helm-buffer-saved-out                            ((t (:foreground COLOR_13 :background COLOR_4))))
   `(helm-buffer-size                                 ((t (:foreground COLOR_7 :background COLOR_4))))
   `(helm-buffer-directory                            ((t (:foreground COLOR_10 :background COLOR_4))))
   `(helm-lisp-completion-info                        ((t (:foreground COLOR_10 :background COLOR_4))))
   `(helm-lisp-show-completion                        ((t (:foreground COLOR_12 :background COLOR_6))))
   `(helm-locate-finish                               ((t (:foreground COLOR_8 :background COLOR_4))))
   `(helm-dotted-symlink-directory                    ((t (:foreground COLOR_7 :background COLOR_5))))
   `(helm-ff-dotted-symlink-directory                 ((t (:foreground COLOR_7 :background COLOR_5))))
   `(helm-ff-directory                                ((t (:foreground COLOR_12 :background COLOR_4 :weight bold))))
   `(helm-ff-file                                     ((t (:foreground COLOR_13 :background COLOR_4 :weight normal))))
   `(helm-ff-executable                               ((t (:foreground COLOR_11 :background COLOR_4 :weight normal))))
   `(helm-ff-invalid-symlink                          ((t (:foreground COLOR_10 :background COLOR_4 :weight bold))))
   `(helm-ff-symlink                                  ((t (:foreground COLOR_13 :background COLOR_4 :weight bold))))
   `(helm-ff-prefix                                   ((t (:foreground COLOR_5 :background COLOR_13 :weight normal))))
   `(helm-grep-cmd-line                               ((t (:foreground COLOR_12 :background COLOR_4))))
   `(helm-grep-file                                   ((t (:foreground COLOR_13 :background COLOR_4))))
   `(helm-grep-finish                                 ((t (:foreground COLOR_11 :background COLOR_4))))
   `(helm-grep-lineno                                 ((t (:foreground COLOR_7 :background COLOR_4))))
   `(helm-match                                       ((t (:foreground COLOR_12 :background COLOR_5))))
   `(helm-grep-match                                  ((t ( :inherit helm-match))))
   `(helm-grep-running                                ((t (:foreground COLOR_10 :background COLOR_4))))
   `(helm-moccur-buffer                               ((t (:foreground COLOR_12 :background COLOR_4))))
   `(helm-mu-contacts-address-face                    ((t (:foreground COLOR_7 :background COLOR_4))))
   `(helm-mu-contacts-name-face                       ((t (:foreground COLOR_13 :background COLOR_4))))
   `(helm-M-x-key                                     ((t (:foreground COLOR_12 :background COLOR_4 :weight bold))))
   ;; hl-line-mode
   `(hl-line-face                                     ((,class (:background COLOR_3)) (t :weight bold)))
   `(hl-line                                          ((,class (:background COLOR_3)) (t :weight bold)))
   ;; hl-sexp
   `(hl-sexp-face                                     ((,class (:background COLOR_6)) (t :weight bold)))
   ;; ido-mode
   `(ido-first-match                                  ((t (:foreground COLOR_13 :weight bold))))
   `(ido-only-match                                   ((t (:foreground COLOR_11 :weight bold))))
   `(ido-subdir                                       ((t (:foreground COLOR_13))))
   `(ido-indicator                                    ((t (:foreground COLOR_13 :background COLOR_7))))
   ;; iedit-mode
   `(iedit-occurrence                                 ((t (:background COLOR_7 :weight bold))))
   ;; js2-mode

   `(js2-warning                                      ((t (:underline COLOR_3))))
   `(js2-error                                        ((t (:foreground COLOR_10 :weight bold))))
   `(js2-jsdoc-tag                                    ((t (:foreground COLOR_8))))
   `(js2-jsdoc-type                                   ((t (:foreground COLOR_11))))
   `(js2-jsdoc-value                                  ((t (:foreground COLOR_12))))
   `(js2-jsdoc-html-tag-name                          ((t (:foreground COLOR_11))))
   `(js2-jsdoc-html-tag-delimiter                     ((t (:foreground COLOR_12))))
   `(js2-function-param                               ((t (:foreground, COLOR_12))))
   `(js2-function-call                                ((t (:foreground, COLOR_12 :underline t))))
   `(js2-object-property                              ((t (:foreground, COLOR_12  :slant italic))))
   `(js2-external-variable                            ((t (:foreground COLOR_7))))

   ;; jabber-mode
   `(jabber-roster-user-away                          ((t (:foreground COLOR_11))))
   `(jabber-roster-user-online                        ((t (:foreground COLOR_10))))
   `(jabber-roster-user-dnd                           ((t (:foreground COLOR_11))))
   `(jabber-rare-time-face                            ((t (:foreground COLOR_10))))
   `(jabber-chat-prompt-local                         ((t (:foreground COLOR_10))))
   `(jabber-chat-prompt-foreign                       ((t (:foreground COLOR_11))))
   `(jabber-activity-face                             ((t (:foreground COLOR_11))))
   `(jabber-activity-personal-face                    ((t (:foreground COLOR_11))))
   `(jabber-title-small                               ((t (:height ,(eziam-theme-height 1.1) :weight bold))))
   `(jabber-title-medium                              ((t (:height ,(eziam-theme-height 1.2) :weight bold))))
   `(jabber-title-large                               ((t (:height ,(eziam-theme-height 1.3) :weight bold))))
   ;; ledger-mode
   `(ledger-font-payee-uncleared-face                 ((t (:foreground COLOR_9 :weight bold))))
   `(ledger-font-payee-cleared-face                   ((t (:foreground COLOR_13 :weight normal))))
   `(ledger-font-xact-highlight-face                  ((t (:background COLOR_6))))
   `(ledger-font-pending-face                         ((t (:foreground COLOR_11 :weight normal))))
   `(ledger-font-other-face                           ((t (:foreground COLOR_13))))
   `(ledger-font-posting-account-face                 ((t (:foreground COLOR_10))))
   `(ledger-font-posting-account-cleared-face         ((t (:foreground COLOR_13))))
   `(ledger-font-posting-account-pending-face         ((t (:foreground COLOR_11))))
   `(ledger-font-posting-amount-face                  ((t (:foreground COLOR_11))))
   `(ledger-font-posting-account-pending-face         ((t (:foreground COLOR_11))))
   `(ledger-occur-narrowed-face                       ((t (:foreground COLOR_7 :invisible t))))
   `(ledger-occur-xact-face                           ((t (:background COLOR_6))))
   `(ledger-font-comment-face                         ((t (:foreground COLOR_9))))
   `(ledger-font-reconciler-uncleared-face            ((t (:foreground COLOR_9 :weight bold))))
   `(ledger-font-reconciler-cleared-face              ((t (:foreground COLOR_13 :weight normal))))
   `(ledger-font-reconciler-pending-face              ((t (:foreground COLOR_11 :weight normal))))
   `(ledger-font-report-clickable-face                ((t (:foreground COLOR_11 :weight normal))))
   ;; linum-mode
   `(linum                                            ((t (:foreground COLOR_11 :background COLOR_4))))
   ;; macrostep
   `(macrostep-gensym-1                               ((t (:foreground COLOR_11 :background COLOR_3))))
   `(macrostep-gensym-2                               ((t (:foreground COLOR_11 :background COLOR_3))))
   `(macrostep-gensym-3                               ((t (:foreground COLOR_11 :background COLOR_3))))
   `(macrostep-gensym-4                               ((t (:foreground COLOR_10 :background COLOR_3))))
   `(macrostep-gensym-5                               ((t (:foreground COLOR_13 :background COLOR_3))))
   `(macrostep-expansion-highlight-face               ((t (:inherit highlight))))
   `(macrostep-macro-face                             ((t (:underline t))))
   ;; magit
   `(magit-section-title                              ((t (:foreground COLOR_13 :weight bold))))
   `(magit-branch                                     ((t (:foreground COLOR_11 :weight bold))))
   `(magit-item-highlight                             ((t (:inverse-video t))))
   ;; egg
   `(egg-text-base                                    ((t (:foreground COLOR_13))))
   `(egg-help-header-1                                ((t (:foreground COLOR_13))))
   `(egg-help-header-2                                ((t (:foreground COLOR_12))))
   `(egg-branch                                       ((t (:foreground COLOR_13))))
   `(egg-branch-mono                                  ((t (:foreground COLOR_13))))
   `(egg-term                                         ((t (:foreground COLOR_13))))
   `(egg-diff-add                                     ((t (:foreground COLOR_13))))
   `(egg-diff-del                                     ((t (:foreground COLOR_11))))
   `(egg-diff-file-header                             ((t (:foreground COLOR_11))))
   `(egg-section-title                                ((t (:foreground COLOR_13))))
   `(egg-stash-mono                                   ((t (:foreground COLOR_13))))
   ;; message-mode
   `(message-cited-text                               ((t (:inherit font-lock-comment-face))))
   `(message-header-name                              ((t (:foreground COLOR_10))))
   `(message-header-other                             ((t (:foreground COLOR_9))))
   `(message-header-to                                ((t (:foreground COLOR_13 :weight bold))))
   `(message-header-from                              ((t (:foreground COLOR_13 :weight bold))))
   `(message-header-cc                                ((t (:foreground COLOR_13 :weight bold))))
   `(message-header-newsgroups                        ((t (:foreground COLOR_13 :weight bold))))
   `(message-header-subject                           ((t (:foreground COLOR_11 :weight bold))))
   `(message-header-xheader                           ((t (:foreground COLOR_9))))
   `(message-mml                                      ((t (:foreground COLOR_13 :weight bold))))
   `(message-separator                                ((t (:inherit font-lock-comment-face))))
   ;; mew
   `(mew-face-header-subject                          ((t (:foreground COLOR_11))))
   `(mew-face-header-from                             ((t (:foreground COLOR_13))))
   `(mew-face-header-date                             ((t (:foreground COLOR_9))))
   `(mew-face-header-to                               ((t (:foreground COLOR_10))))
   `(mew-face-header-key                              ((t (:foreground COLOR_9))))
   `(mew-face-header-private                          ((t (:foreground COLOR_9))))
   `(mew-face-header-important                        ((t (:foreground COLOR_11))))
   `(mew-face-header-marginal                         ((t (:foreground COLOR_13 :weight bold))))
   `(mew-face-header-warning                          ((t (:foreground COLOR_10))))
   `(mew-face-header-xmew                             ((t (:foreground COLOR_9))))
   `(mew-face-header-xmew-bad                         ((t (:foreground COLOR_10))))
   `(mew-face-body-url                                ((t (:foreground COLOR_11))))
   `(mew-face-body-comment                            ((t (:foreground COLOR_13 :slant italic))))
   `(mew-face-body-cite1                              ((t (:foreground COLOR_9))))
   `(mew-face-body-cite2                              ((t (:foreground COLOR_11))))
   `(mew-face-body-cite3                              ((t (:foreground COLOR_11))))
   `(mew-face-body-cite4                              ((t (:foreground COLOR_13))))
   `(mew-face-body-cite5                              ((t (:foreground COLOR_10))))
   `(mew-face-mark-review                             ((t (:foreground COLOR_11))))
   `(mew-face-mark-escape                             ((t (:foreground COLOR_9))))
   `(mew-face-mark-delete                             ((t (:foreground COLOR_10))))
   `(mew-face-mark-unlink                             ((t (:foreground COLOR_13))))
   `(mew-face-mark-refile                             ((t (:foreground COLOR_9))))
   `(mew-face-mark-unread                             ((t (:foreground COLOR_9))))
   `(mew-face-eof-message                             ((t (:foreground COLOR_9))))
   `(mew-face-eof-part                                ((t (:foreground COLOR_13))))
   ;; mic-paren
   `(paren-face-match                                 ((t (:foreground COLOR_12 :background COLOR_3 ))))
   `(paren-face-mismatch                              ((t (:foreground COLOR_2 :background COLOR_3 ))))
   `(paren-face-no-match                              ((t (:foreground COLOR_6 :background COLOR_3 ))))
   ;; mingus
   `(mingus-directory-face                            ((t (:foreground COLOR_11))))
   `(mingus-pausing-face                              ((t (:foreground COLOR_10))))
   `(mingus-playing-face                              ((t (:foreground COLOR_12))))
   `(mingus-playlist-face                             ((t (:foreground COLOR_12 ))))
   `(mingus-song-file-face                            ((t (:foreground COLOR_13))))
   `(mingus-stopped-face                              ((t (:foreground COLOR_10))))
   ;; nav
   `(nav-face-heading                                 ((t (:foreground COLOR_13))))
   `(nav-face-button-num                              ((t (:foreground COLOR_12))))
   `(nav-face-dir                                     ((t (:foreground COLOR_9))))
   `(nav-face-hdir                                    ((t (:foreground COLOR_10))))
   `(nav-face-file                                    ((t (:foreground COLOR_13))))
   `(nav-face-hfile                                   ((t (:foreground COLOR_7))))
   ;; mu4e
   `(mu4e-header-highlight-face                       ((t (:inverse-video t))))
   `(mu4e-cited-1-face                                ((t (:foreground COLOR_11    :slant italic))))
   `(mu4e-cited-2-face                                ((t (:foreground COLOR_11 :slant italic))))
   `(mu4e-cited-3-face                                ((t (:foreground COLOR_9  :slant italic))))
   `(mu4e-cited-4-face                                ((t (:foreground COLOR_9   :slant italic))))
   `(mu4e-cited-5-face                                ((t (:foreground COLOR_7  :slant italic))))
   `(mu4e-cited-6-face                                ((t (:foreground COLOR_8 :slant italic))))
   `(mu4e-cited-7-face                                ((t (:foreground COLOR_11    :slant italic))))
   `(mu4e-replied-face                                ((t (:foreground COLOR_8))))
   `(mu4e-trashed-face                                ((t (:foreground COLOR_8 :strike-through t))))
   ;; mumamo
   `(mumamo-background-chunk-major                    ((t (:background nil))))
   `(mumamo-background-chunk-submode1                 ((t (:background COLOR_3))))
   `(mumamo-background-chunk-submode2                 ((t (:background COLOR_7))))
   `(mumamo-background-chunk-submode3                 ((t (:background COLOR_8))))
   `(mumamo-background-chunk-submode4                 ((t (:background COLOR_6))))
   ;; org-mode
   `(org-agenda-date-today                            ((t (:foreground COLOR_14 :slant italic :weight bold))) t)
   `(org-agenda-structure                             ((t (:inherit font-lock-comment-face))))
   `(org-archived                                     ((t (:foreground COLOR_13 :weight bold))))
   `(org-checkbox                                     ((t (:background COLOR_7 :foreground COLOR_14 :box (:line-width 1 :style released-button)))))
   `(org-date                                         ((t (:foreground COLOR_11 :underline t))))
   `(org-deadline-announce                            ((t (:foreground COLOR_9))))
   `(org-formula                                      ((t (:foreground COLOR_11))))
   `(org-headline-done                                ((t (:foreground COLOR_12))))
   `(org-hide                                         ((t (:foreground COLOR_3))))
   `(org-document-title                               ((t (:foreground COLOR_12 :height ,(eziam-theme-height 1.9) :bold t))))
   `(org-level-1 ((,class ,ol1)))   
   ;;   `(org-level-1                                      ((t (:foreground COLOR_14 :height ,(eziam-theme-height 1.5)))))
   `(org-level-2                                      ((t (:foreground COLOR_10 :height ,(eziam-theme-height 1.2)))))
   `(org-level-3                                      ((t (:foreground COLOR_9 :height ,(eziam-theme-height 1.1)))))
   `(org-level-4                                      ((t (:foreground COLOR_9 :height ,(eziam-theme-height 1.0)))))
   `(org-level-5                                      ((t (:foreground COLOR_9 :height ,(eziam-theme-height 1.0)))))
   `(org-level-6                                      ((t (:foreground COLOR_9 :height ,(eziam-theme-height 1.0)))))
   `(org-level-7                                      ((t (:foreground COLOR_9 :height ,(eziam-theme-height 1.0)))))
   `(org-level-8                                      ((t (:foreground COLOR_8 :height ,(eziam-theme-height 1.0)))))
   `(org-link                                         ((t (:foreground COLOR_11 :underline t))))
   `(org-scheduled                                    ((t (:foreground COLOR_13))))
   `(org-scheduled-previously                         ((t (:foreground COLOR_10))))
   `(org-scheduled-today                              ((t (:foreground COLOR_11))))
   `(org-sexp-date                                    ((t (:foreground COLOR_11 :underline t))))
   `(org-special-keyword                              ((t (:inherit font-lock-comment-face))))
   `(org-table                                        ((t (:foreground COLOR_11))))
   `(org-tag                                          ((t (:bold t :weight bold))))
   `(org-time-grid                                    ((t (:foreground COLOR_11))))
   `(org-done                                         ((t (:bold t :background COLOR_10 :foreground COLOR_1 :weight bold))))
   `(org-todo                                         ((t (:bold t  :background COLOR_10  :foreground COLOR_4 :weight bold))))
   `(org-upcoming-deadline                            ((t (:inherit font-lock-keyword-face))))
   `(org-warning                                      ((t (:bold t :foreground COLOR_10 :weight bold :underline nil))))
   `(org-column                                       ((t (:background COLOR_3))))
   `(org-column-title                                 ((t (:background COLOR_3 :underline t :weight bold))))
   `(org-mode-line-clock                              ((t (:foreground COLOR_13 :background COLOR_3))))
   `(org-mode-line-clock-overrun                      ((t (:foreground COLOR_5 :background COLOR_9))))
   `(org-ellipsis                                     ((t (:foreground COLOR_12 :underline t))))
   `(org-footnote                                     ((t (:foreground COLOR_12 :underline t))))
   `(org-meta-line                                    ((t (:foreground COLOR_8 :height ,(eziam-theme-height 1.0)))))
   `(org-block-background                             ((t (:background COLOR_4 :height ,(eziam-theme-height 1.0)))))
   `(org-block                                        ((t (:foreground COLOR_7 :height ,(eziam-theme-height 1.0)))))
   `(org-block-begin-line                             ((t (:foreground COLOR_6 :height ,(eziam-theme-height .75)))))
   `(org-block-end-line                               ((t (:inherit org-block-begin-line))))

   ;; outline
   `(outline-1                                        ((t (:foreground COLOR_11))))
   `(outline-2                                        ((t (:foreground COLOR_13))))
   `(outline-3                                        ((t (:foreground COLOR_10))))
   `(outline-4                                        ((t (:foreground COLOR_11))))
   `(outline-5                                        ((t (:foreground COLOR_12))))
   `(outline-6                                        ((t (:foreground COLOR_11))))
   `(outline-7                                        ((t (:foreground COLOR_7))))
   `(outline-8                                        ((t (:foreground COLOR_7))))
   ;; p4
   `(p4-depot-added-face                              ((t :inherit diff-added)))
   `(p4-depot-branch-op-face                          ((t :inherit diff-changed)))
   `(p4-depot-deleted-face                            ((t :inherit diff-removed)))
   `(p4-depot-unmapped-face                           ((t :inherit diff-changed)))
   `(p4-diff-change-face                              ((t :inherit diff-changed)))
   `(p4-diff-del-face                                 ((t :inherit diff-removed)))
   `(p4-diff-file-face                                ((t :inherit diff-file-header)))
   `(p4-diff-head-face                                ((t :inherit diff-header)))
   `(p4-diff-ins-face                                 ((t :inherit diff-added)))
   ;; perspective
   `(persp-selected-face                              ((t (:foreground COLOR_11 :inherit mode-line))))
   ;; powerline
   `(powerline-active1                                ((t (:background COLOR_6 :foreground COLOR_11 :box nil :inherit mode-line ))))
   `(powerline-active2                                ((t (:background COLOR_3 :foreground COLOR_8 :box nil :inherit mode-line ))))
   `(powerline-inactive1                              ((t (:background COLOR_3 :foreground COLOR_6 :inherit mode-line-inactive))))
   `(powerline-inactive2                              ((t (:background COLOR_2 :foreground COLOR_7 :inherit mode-line-inactive))))
   ;; proofgeneral
   `(proof-active-area-face                           ((t (:underline t))))
   `(proof-boring-face                                ((t (:foreground COLOR_13 :background COLOR_7))))
   `(proof-command-mouse-highlight-face               ((t (:inherit proof-mouse-highlight-face))))
   `(proof-debug-message-face                         ((t (:inherit proof-boring-face))))
   `(proof-declaration-name-face                      ((t (:inherit font-lock-keyword-face :foreground nil))))
   `(proof-eager-annotation-face                      ((t (:foreground COLOR_5 :background COLOR_11))))
   `(proof-error-face                                 ((t (:foreground COLOR_13 :background COLOR_7))))
   `(proof-highlight-dependency-face                  ((t (:foreground COLOR_5 :background COLOR_12))))
   `(proof-highlight-dependent-face                   ((t (:foreground COLOR_5 :background COLOR_11))))
   `(proof-locked-face                                ((t (:background COLOR_6))))
   `(proof-mouse-highlight-face                       ((t (:foreground COLOR_5 :background COLOR_11))))
   `(proof-queue-face                                 ((t (:background COLOR_7))))
   `(proof-region-mouse-highlight-face                ((t (:inherit proof-mouse-highlight-face))))
   `(proof-script-highlight-error-face                ((t (:background COLOR_9))))
   `(proof-tacticals-name-face                        ((t (:inherit font-lock-constant-face :foreground nil :background COLOR_4))))
   `(proof-tactics-name-face                          ((t (:inherit font-lock-constant-face :foreground nil :background COLOR_4))))
   `(proof-warning-face                               ((t (:foreground COLOR_5 :background COLOR_12))))
   ;; rainbow-delimiters
   `(rainbow-delimiters-depth-1-face                  ((t (:foreground COLOR_7))))
   `(rainbow-delimiters-depth-2-face                  ((t (:foreground COLOR_8))))
   `(rainbow-delimiters-depth-3-face                  ((t (:foreground COLOR_9))))
   `(rainbow-delimiters-depth-4-face                  ((t (:foreground COLOR_10))))
   `(rainbow-delimiters-depth-5-face                  ((t (:foreground COLOR_11))))
   `(rainbow-delimiters-depth-6-face                  ((t (:foreground COLOR_12))))
   `(rainbow-delimiters-depth-7-face                  ((t (:foreground COLOR_13))))
   `(rainbow-delimiters-depth-8-face                  ((t (:foreground COLOR_14))))
   `(rainbow-delimiters-depth-9-face                  ((t (:foreground COLOR_14))))
   `(rainbow-delimiters-depth-10-face                 ((t (:foreground COLOR_14))))
   `(rainbow-delimiters-depth-11-face                 ((t (:foreground COLOR_14))))
   `(rainbow-delimiters-depth-12-face                 ((t (:foreground COLOR_14))))
   ;; rcirc
   `(rcirc-my-nick                                    ((t (:foreground COLOR_11))))
   `(rcirc-other-nick                                 ((t (:foreground COLOR_11))))
   `(rcirc-bright-nick                                ((t (:foreground COLOR_11))))
   `(rcirc-dim-nick                                   ((t (:foreground COLOR_9))))
   `(rcirc-server                                     ((t (:foreground COLOR_9))))
   `(rcirc-server-prefix                              ((t (:foreground COLOR_10))))
   `(rcirc-timestamp                                  ((t (:foreground COLOR_11))))
   `(rcirc-nick-in-message                            ((t (:foreground COLOR_13))))
   `(rcirc-nick-in-message-full-line                  ((t (:bold t))))
   `(rcirc-prompt                                     ((t (:foreground COLOR_13 :bold t))))
   `(rcirc-track-nick                                 ((t (:inverse-video t))))
   `(rcirc-track-keyword                              ((t (:bold t))))
   `(rcirc-url                                        ((t (:bold t))))
   `(rcirc-keyword                                    ((t (:foreground COLOR_13 :bold t))))
   ;; rpm-mode
   `(rpm-spec-dir-face                                ((t (:foreground COLOR_9))))
   `(rpm-spec-doc-face                                ((t (:foreground COLOR_9))))
   `(rpm-spec-ghost-face                              ((t (:foreground COLOR_10))))
   `(rpm-spec-macro-face                              ((t (:foreground COLOR_13))))
   `(rpm-spec-obsolete-tag-face                       ((t (:foreground COLOR_10))))
   `(rpm-spec-package-face                            ((t (:foreground COLOR_10))))
   `(rpm-spec-section-face                            ((t (:foreground COLOR_13))))
   `(rpm-spec-tag-face                                ((t (:foreground COLOR_11))))
   `(rpm-spec-var-face                                ((t (:foreground COLOR_10))))
   ;; rst-mode
   `(rst-level-1-face                                 ((t (:foreground COLOR_11))))
   `(rst-level-2-face                                 ((t (:foreground COLOR_10))))
   `(rst-level-3-face                                 ((t (:foreground COLOR_10))))
   `(rst-level-4-face                                 ((t (:foreground COLOR_11))))
   `(rst-level-5-face                                 ((t (:foreground COLOR_12))))
   `(rst-level-6-face                                 ((t (:foreground COLOR_8))))
   ;; sh-mode
   `(sh-heredoc                                       ((t (:foreground COLOR_13 :bold t))))
   `(sh-quoted-exec                                   ((t (:foreground COLOR_10))))
   ;; show-paren
   `(show-paren-mismatch                         ((t (:foreground COLOR_1 :background COLOR_7 :weight bold))))
   `(show-paren-match                            ((t (:foreground COLOR_11 :background COLOR_3  :weight bold))))
   ;; smartparens
   `(sp-show-pair-mismatch-face                       ((t (:foreground COLOR_14 :background COLOR_3))))
   `(sp-show-pair-match-face                          ((t (:foreground COLOR_14 :background COLOR_6 :underline nil))))
   ;; sml-mode-line
   `(sml-modeline-end-face                            ((t :inherit default :width condensed)))
   ;; SLIME
   `(slime-repl-output-face                           ((t (:foreground COLOR_10))))
   `(slime-repl-inputed-output-face                   ((t (:foreground COLOR_9))))
   `(slime-error-face                                 ((((supports :underline (:style wave))) (:underline (:style wave :color COLOR_10))) (t (:underline COLOR_10))))
   `(slime-warning-face                               ((((supports :underline (:style wave))) (:underline (:style wave :color COLOR_11))) (t (:underline COLOR_11))))
   `(slime-style-warning-face                         ((((supports :underline (:style wave))) (:underline (:style wave :color COLOR_13))) (t (:underline COLOR_13))))
   `(slime-note-face                                  ((((supports :underline (:style wave))) (:underline (:style wave :color COLOR_9))) (t (:underline COLOR_9))))
   `(slime-highlight-face                             ((t (:inherit highlight))))
   ;; speedbar
   `(speedbar-button-face                             ((t (:foreground COLOR_11))))
   `(speedbar-directory-face                          ((t (:foreground COLOR_12))))
   `(speedbar-file-face                               ((t (:foreground COLOR_13))))
   `(speedbar-highlight-face                          ((t (:foreground COLOR_5 :background COLOR_11))))
   `(speedbar-selected-face                           ((t (:foreground COLOR_10))))
   `(speedbar-separator-face                          ((t (:foreground COLOR_5 :background COLOR_10))))
   `(speedbar-tag-face                                ((t (:foreground COLOR_13))))
   ;; tabbar
   `(tabbar-button                                    ((t (:foreground COLOR_13 :background COLOR_4))))
   `(tabbar-selected                                  ((t (:foreground COLOR_13 :background COLOR_4 :box (:line-width -1 :style pressed-button)))))
   `(tabbar-unselected                                ((t (:foreground COLOR_13 :background COLOR_6 :box (:line-width -1 :style released-button)))))
   ;; term
   `(term-color-black                                 ((t (:foreground COLOR_5 :background COLOR_3))))
   `(term-color-red                                   ((t (:foreground COLOR_9 :background COLOR_7))))
   `(term-color-green                                 ((t (:foreground COLOR_9 :background COLOR_11))))
   `(term-color-yellow                                ((t (:foreground COLOR_11 :background COLOR_13))))
   `(term-color-blue                                  ((t (:foreground COLOR_10 :background COLOR_7))))
   `(term-color-magenta                               ((t (:foreground COLOR_10 :background COLOR_10))))
   `(term-color-cyan                                  ((t (:foreground COLOR_12 :background COLOR_11))))
   `(term-color-white                                 ((t (:foreground COLOR_13 :background COLOR_7))))
   '(term-default-fg-color                            ((t (:inherit term-color-white))))
   '(term-default-bg-color                            ((t (:inherit term-color-black))))
   ;; undo-tree
   `(undo-tree-visualizer-active-branch-face          ((t (:foreground COLOR_14 :weight bold))))
   `(undo-tree-visualizer-current-face                ((t (:foreground COLOR_9 :weight bold))))
   `(undo-tree-visualizer-default-face                ((t (:foreground COLOR_13))))
   `(undo-tree-visualizer-register-face               ((t (:foreground COLOR_13))))
   `(undo-tree-visualizer-unmodified-face             ((t (:foreground COLOR_12))))
   ;; volatile-highlights
   `(vhl/default-face                                 ((t (:background COLOR_4))))
   ;; emacs-w3m
   `(w3m-anchor                                       ((t (:foreground COLOR_12 :background COLOR_4 :underline t :weight normal))))
   `(w3m-current-anchor                               ((t (:foreground COLOR_14 :background COLOR_1 :underline nil :weight bold))))
   `(w3m-arrived-anchor-face                          ((t (:foreground COLOR_7 :background COLOR_5 :underline t :weight normal))))
   `(w3m-image-anchor-face                            ((t (:foreground COLOR_10  :background COLOR_5 :underline t :weight normal))))
   `(w3m-image-face                                   ((t (:foreground COLOR_11 :background COLOR_5 :underline t :weight normal))))
   `(w3m-image-anchor                                 ((t (:foreground COLOR_11 :background COLOR_5 :underline t :weight normal))))
   `(w3m-form                                         ((t (:foreground COLOR_9 :underline t))))
   `(w3m-header-line-location-title                   ((t (:foreground COLOR_7 :background COLOR_5 :underline nil :weight normal))))
   `(w3m-header-line-location-content                 ((t (:foreground COLOR_13 :background COLOR_5 :underline nil :weight normal))))
   `(w3m-history-current-url                          ((t (:inherit match))))
   `(w3m-tab-background                               ((t (:foreground COLOR_1 :background COLOR_9 :underline nil :weight normal))) )
   `(w3m-tab-unselected-retrieving                    ((t (:foreground COLOR_1 :background COLOR_9 :underline nil :weight normal))) )
   `(w3m-tab-selected-background-face                 ((t (:foreground COLOR_1 :background COLOR_11 :underline nil :weight bold))) )
   `(w3m-tab-selected-retrieving                      ((t (:foreground COLOR_1 :background COLOR_11 :underline nil :weight bold))) )
   `(w3m-lnum                                         ((t (:foreground COLOR_11 :background COLOR_4))))
   `(w3m-lnum-match                                   ((t (:background COLOR_3 :foreground COLOR_11 :weight bold))))
   `(w3m-lnum-minibuffer-prompt                       ((t (:foreground COLOR_13))))
   ;; web-mode
   `(web-mode-builtin-face                            ((t (:inherit ,font-lock-builtin-face))))
   `(web-mode-comment-face                            ((t (:inherit ,font-lock-comment-face))))
   `(web-mode-constant-face                           ((t (:inherit ,font-lock-constant-face))))
   `(web-mode-css-at-rule-face                        ((t (:foreground COLOR_11 ))))
   `(web-mode-css-prop-face                           ((t (:foreground COLOR_11))))
   `(web-mode-css-pseudo-class-face                   ((t (:foreground COLOR_12 :weight bold))))
   `(web-mode-css-rule-face                           ((t (:foreground COLOR_11))))
   `(web-mode-doctype-face                            ((t (:inherit ,font-lock-comment-face))))
   `(web-mode-folded-face                             ((t (:underline t))))
   `(web-mode-function-name-face                      ((t (:foreground COLOR_11))))
   `(web-mode-html-attr-name-face                     ((t (:foreground COLOR_11))))
   `(web-mode-html-attr-value-face                    ((t (:inherit ,font-lock-string-face))))
   `(web-mode-html-tag-face                           ((t (:foreground COLOR_12))))
   `(web-mode-keyword-face                            ((t (:inherit ,font-lock-keyword-face))))
   `(web-mode-preprocessor-face                       ((t (:inherit ,font-lock-preprocessor-face))))
   `(web-mode-string-face                             ((t (:inherit ,font-lock-string-face))))
   `(web-mode-type-face                               ((t (:inherit ,font-lock-type-face))))
   `(web-mode-variable-name-face                      ((t (:inherit ,font-lock-variable-name-face))))
   `(web-mode-server-background-face                  ((t (:background COLOR_4))))
   `(web-mode-server-comment-face                     ((t (:inherit web-mode-comment-face))))
   `(web-mode-server-string-face                      ((t (:inherit web-mode-string-face))))
   `(web-mode-symbol-face                             ((t (:inherit font-lock-constant-face))))
   `(web-mode-warning-face                            ((t (:inherit font-lock-warning-face))))
   `(web-mode-whitespaces-face                        ((t (:background COLOR_10))))
   ;; whitespace-mode
   `(whitespace-space                                 ((t (:background COLOR_6 :foreground COLOR_6))))
   `(whitespace-hspace                                ((t (:background COLOR_6 :foreground COLOR_6))))
   `(whitespace-tab                                   ((t (:background COLOR_9))))
   `(whitespace-newline                               ((t (:foreground COLOR_6))))
   `(whitespace-trailing                              ((t (:background COLOR_10))))
   `(whitespace-line                                  ((t (:background COLOR_4 :foreground COLOR_10))))
   `(whitespace-space-before-tab                      ((t (:background COLOR_11 :foreground COLOR_11))))
   `(whitespace-indentation                           ((t (:background COLOR_13 :foreground COLOR_10))))
   `(whitespace-empty                                 ((t (:background COLOR_13))))
   `(whitespace-space-after-tab                       ((t (:background COLOR_13 :foreground COLOR_10))))
   ;; wanderlust
   `(wl-highlight-folder-few-face                     ((t (:foreground COLOR_9))))
   `(wl-highlight-folder-many-face                    ((t (:foreground COLOR_9))))
   `(wl-highlight-folder-path-face                    ((t (:foreground COLOR_11))))
   `(wl-highlight-folder-unread-face                  ((t (:foreground COLOR_11))))
   `(wl-highlight-folder-zero-face                    ((t (:foreground COLOR_13))))
   `(wl-highlight-folder-unknown-face                 ((t (:foreground COLOR_11))))
   `(wl-highlight-message-citation-header             ((t (:foreground COLOR_9))))
   `(wl-highlight-message-cited-text-1                ((t (:foreground COLOR_10))))
   `(wl-highlight-message-cited-text-2                ((t (:foreground COLOR_11))))
   `(wl-highlight-message-cited-text-3                ((t (:foreground COLOR_11))))
   `(wl-highlight-message-cited-text-4                ((t (:foreground COLOR_11))))
   `(wl-highlight-message-header-contents-face        ((t (:foreground COLOR_9))))
   `(wl-highlight-message-headers-face                ((t (:foreground COLOR_11))))
   `(wl-highlight-message-important-header-contents   ((t (:foreground COLOR_11))))
   `(wl-highlight-message-header-contents             ((t (:foreground COLOR_10))))
   `(wl-highlight-message-important-header-contents2  ((t (:foreground COLOR_11))))
   `(wl-highlight-message-signature                   ((t (:foreground COLOR_9))))
   `(wl-highlight-message-unimportant-header-contents ((t (:foreground COLOR_13))))
   `(wl-highlight-summary-answered-face               ((t (:foreground COLOR_11))))
   `(wl-highlight-summary-disposed-face               ((t (:foreground COLOR_13 :slant italic))))
   `(wl-highlight-summary-new-face                    ((t (:foreground COLOR_11))))
   `(wl-highlight-summary-normal-face                 ((t (:foreground COLOR_13))))
   `(wl-highlight-summary-thread-top-face             ((t (:foreground COLOR_13))))
   `(wl-highlight-thread-indent-face                  ((t (:foreground COLOR_10))))
   `(wl-highlight-summary-refiled-face                ((t (:foreground COLOR_13))))
   `(wl-highlight-summary-displaying-face             ((t (:underline t :weight bold))))
   ;; which-func-mode
   `(which-func                                       ((t (:foreground COLOR_13))))
   ;; yascroll
   `(yascroll:thumb-text-area                         ((t (:background COLOR_3))))
   `(yascroll:thumb-fringe                            ((t (:background COLOR_3 :foreground COLOR_3))))
   `(minimap-active-region-background                 ((t (:background COLOR_6 :foreground COLOR_7))))
   ;; html fold/unfold face
   `(html-fold-unfolded-face                          ((t (:background COLOR_4))))
   `(html-fold-folded-face                            ((t (:foreground COLOR_14 :bold t))))
   ;; markdown mode
   `(markdown-header-delimiter-face                   ((t (:weight normal :foreground COLOR_6))))
   `(markdown-header-face-1                           ((t (:inherit markdown-header-face :height ,(eziam-theme-height 1.5)))))
   `(markdown-header-face-2                           ((t (:inherit markdown-header-face :height ,(eziam-theme-height 1.3)))))
   `(markdown-header-face-3                           ((t (:inherit markdown-header-face :underline t :height ,(eziam-theme-height 1.2)))))
   `(markdown-header-face-4                           ((t (:inherit markdown-header-face :underline t :height ,(eziam-theme-height 1.1)))))
   `(markdown-header-face-5                           ((t (:inherit markdown-header-face :underline t))))
   `(markdown-header-face-6                           ((t (:inherit markdown-header-face :underline t))))
   `(markdown-link-face                               ((t (:underline t :foreground COLOR_13))))
   `(markdown-url-face                                ((t (:underline t :foreground COLOR_12))))
   `(markdown-pre-face                                ((t (:foreground COLOR_13 :height ,(eziam-theme-height .8) ))))
   `(markdown-bold-face                               ((t (:foreground COLOR_8 :bold t ))))
   `(markdown-italic-face                             ((t (:foreground COLOR_8 :italic t ))))
   `(markdown-list-face                               ((t (:foreground COLOR_12))))
   `(markdown-markup-face                             ((t (:foreground COLOR_6 ))))
   ;; swoop
   `(swoop-face-line-buffer-name                      ((t (:background COLOR_9 :foreground COLOR_1))))
   `(swoop-face-target-line                           ((t (:background COLOR_7 :foreground COLOR_12))))
   `(swoop-face-line-number                           ((t (:background COLOR_4 :foreground COLOR_6))))
   `(swoop-face-header-format-line                    ((t (:background COLOR_6 :foreground COLOR_1))))
   `(swoop-face-target-words                          ((t (:background COLOR_6 :foreground COLOR_13))))
   `(highlight-indentation-face                       ((t (:background COLOR_5))))
   `(highlight-indentation-current-column-face        ((t (:background COLOR_3))))
   ;; company
   `(company-echo-common                              ((t (:foreground COLOR_13))))
   `(company-preview                                  ((t (:background COLOR_6 :foreground COLOR_11))))
   `(company-preview-common                           ((t (:inherit company-preview :foreground COLOR_13 :weight bold))))
   `(company-scrollbar-fg                             ((t (:background COLOR_7))))
   `(company-tooltip                                  ((t (:background COLOR_6 :foreground COLOR_11))))
   `(company-tooltip-annotation                       ((t (:inherit company-tooltip :foreground COLOR_2))))
   `(company-tooltip-common                           ((t (:inherit company-tooltip :foreground COLOR_11))))
   `(company-tooltip-common-selection                 ((t (:inherit company-tooltip-selection :foreground COLOR_13))))
   `(company-tooltip-selection                        ((t (:inherit company-tooltip :background COLOR_8 :foreground COLOR_1))))
   `(company-scrollbar-bg                             ((t (:inherit company-tooltip))))
   ;; eval-sexp-fu
   `(eval-sexp-fu-flash                               ((t (:background COLOR_5))))
   `(eval-sexp-fu-flash-error                         ((t (:background COLOR_11 :foreground COLOR_1))))
   ;; neotree
   `(neo-dir-link-face                                ((t (:inherit diredp-dir-priv))))
   `(neo-expand-btn-face                              ((t (:foreground COLOR_11 :bold t))))
   `(neo-file-link-face                               ((t (:foreground COLOR_9))))
   `(neo-root-dir-face                                ((t (:foreground COLOR_8 :background COLOR_2))))
   ;; geiser
   `(geiser-font-lock-doc-link                        ((t (:foreground COLOR_11 :underline t))))
   `(geiser-font-lock-error-link                        ((t (:foreground COLOR_11 :underline t))))
   `(geiser-font-lock-autodoc-identifier              ((t (:foreground COLOR_8 :bold t))))
   `(compilation-error                                ((t (:foreground COLOR_12 :underline t :bold t))))
   ;; elixir
   `(elixir-atom-face                                 ((t (:foreground COLOR_12 :bold t))))
   ;; tuareg
   `(tuareg-font-lock-operator-face                   ((t (:inherit ,font-lock-variable-name-face))))
   `(tuareg-font-lock-governing-face                  ((t (:inherit ,font-lock-keyword-face))))
   ;; avy
   `(avy-lead-face                                    ((t (:background COLOR_8 :foreground COLOR_1 :bold t))))
   `(avy-lead-face-0                                  ((t (:background COLOR_9  :foreground COLOR_1  :bold t))))
   `(avy-lead-face-1                                  ((t (:background COLOR_10  :foreground COLOR_1 :bold t))))
   `(avy-lead-face-2                                  ((t (:background COLOR_11  :foreground COLOR_1 :bold t))))
   `(avy-background-face                              ((t (:background COLOR_3  :foreground COLOR_7 :bold t))))
   )
  )

;; Theme Variables
(custom-theme-set-variables
 'eziam-VARIANT
 ;; ansi-color
 `(ansi-color-names-vector [COLOR_5
                            COLOR_10
                            COLOR_9
                            COLOR_13
                            COLOR_11
                            COLOR_10
                            COLOR_12
                            COLOR_13])
 ;; fill-column-indicator
 `(fci-rule-color COLOR_4)
 ;; vc-annotate
 `(vc-annotate-color-map
   '(( 20. . COLOR_7)
     ( 40. . COLOR_8)
     ( 60. . COLOR_8)
     ( 80. . COLOR_9)
     (100. . COLOR_9)
     (120. . COLOR_10)
     (140. . COLOR_10)
     (160. . COLOR_11)
     (180. . COLOR_11)
     (200. . COLOR_11)
     (220. . COLOR_12)
     (240. . COLOR_12)
     (260. . COLOR_12)
     (280. . COLOR_13)
     (300. . COLOR_13)
     (320. . COLOR_13)
     (340. . COLOR_14)
     (360. . COLOR_14)))
 `(vc-annotate-very-old-color COLOR_10)
 `(vc-annotate-background COLOR_3)
 )

;;; Footer
(provide-theme 'eziam-VARIANT)

;;;###autoload

;; Local Variables:
;; mode: emacs-lisp;
;; no-byte-compile: t
;; indent-tabs-mode: nil
;; End:
;;; eziam-VARIANT-theme.el ends here
