#+TITLE: Eziam Theme

[[#screenshots][Screenshots]] · [[#installation][Installation]] 

------

*State*: Eziam is almost usable.

Eziam is a theme for Emacs, which tries to combine the simplicity of [[https://github.com/11111000000/tao-theme-emacs][Tao]] with the org-mode goodness of [[https://github.com/fniessen/emacs-leuven-theme/issues][Leuven]].  Unlike Tao, it tries to keep some very minimal color indications, while remaining mainly grayscale and trying to avoid the “angry fruit salad” syndrome.

It colorizes:

 - org/markdown headings, in a a fashion that should be reminiscent of Leuven.
 - Flycheck/Flyspell indicators and faces.
 - Class/function names at declaration/definition to make code structure easier to scan.

** Screenshots

soon!

** Installation

Eziam is not yet in Melpa.

** Hacking

Eziam build script (=make.sh=) uses the [[https://logological.org/gpp][gpp]] preprocessor to apply palette values into a single template file and generate the theme's el files.  Each =*.palette= file corresponds to an Eziam variant.  

**** Palette

To define a palette, simply copy a =.palette= file to a new name and update its values.  

| Name    | Usage             | Notes |   |
|---------+-------------------+-------+---|
| COLOR_0 | Negative contrast |       |   |
| COLOR_1 | Background color  |       |   |
| COLOR_2 |                   |       |   |
| COLOR_2 |                   |       |   |
|         |                   |       |   |
|         |                   |       |   |
|         |                   |       |   |
|         |                   |       |   |
|         |                   |       |   |
|         |                   |       |   |


** What's in a name?

An extremely bad pun.
